[package]
name = "ssbm-disc"
description = "Loads and verifies a Super Smash Bros. Melee disc image"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
nod.workspace = true
sha1.workspace = true
ssbm-mem.workspace = true
thiserror.workspace = true
