// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from libs/dolphin/src/dolphin/thp/THPDec.c. Do not edit; fix the translator or port by hand.
// unit: dolphin/thp/THPDec
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn __THPPrepBitStream<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) {
    let mut info = info;
    let mut ptr_: Val<'a, u32> = null(ctx);
    let mut offset: u32 = 0;
    let mut i: u32 = 0;
    let mut j: u32 = 0;
    let mut k: u32 = 0;
    ptr_ = ptr::<Val<'a, u32>>(
        ctx,
        (Handle::addr((info).file()) & ((!3_i32) as u32)) as u32,
    );
    offset = (Handle::addr((info).file()) & (3_i32 as u32));
    if (info).cnt() != (33_i32 as u32) {
        (info).set_cnt(
            (info)
                .cnt()
                .wrapping_sub(((3_i32 as u32).wrapping_sub(offset)).wrapping_mul((8_i32 as u32))),
        );
    } else {
        (info).set_cnt((offset.wrapping_mul((8_i32 as u32))).wrapping_add((1_i32 as u32)));
    }
    (info).set_file(Handle::cast::<Val<'a, u8>>(ptr_));
    (info).set_currByte((ptr_).get());
    {
        i = (0_i32 as u32);
        'l1: while i < (4_i32 as u32) {
            'c2: {
                if ((((info).validHuffmanTabs() as i32) & (shl_i32(1_i32, i))) != 0) {
                    {
                        j = (0_i32 as u32);
                        'l3: while j < (32_i32 as u32) {
                            'c4: {
                                (info)
                                    .huffmanTabs()
                                    .get((i as i32))
                                    .quick()
                                    .at((j as i32))
                                    .set((255_i32 as u8));
                                {
                                    k = (0_i32 as u32);
                                    'l5: while k < (5_i32 as u32) {
                                        'c6: {
                                            let mut code: i32 = (shr_u32(
                                                j,
                                                ((5_i32 as u32)
                                                    .wrapping_sub(k)
                                                    .wrapping_sub((1_i32 as u32))),
                                            )
                                                as i32);
                                            if code
                                                <= (info)
                                                    .huffmanTabs()
                                                    .get((i as i32))
                                                    .maxCode()
                                                    .at((k.wrapping_add((1_i32 as u32)) as i32))
                                                    .get()
                                            {
                                                (info)
                                                    .huffmanTabs()
                                                    .get((i as i32))
                                                    .quick()
                                                    .at((j as i32))
                                                    .set(
                                                        (Handle::add(
                                                            (info)
                                                                .huffmanTabs()
                                                                .get((i as i32))
                                                                .Vij(),
                                                            (code.wrapping_add(
                                                                (info)
                                                                    .huffmanTabs()
                                                                    .get((i as i32))
                                                                    .valPtr()
                                                                    .at((k.wrapping_add(
                                                                        (1_i32 as u32),
                                                                    )
                                                                        as i32))
                                                                    .get(),
                                                            )),
                                                        ))
                                                        .get(),
                                                    );
                                                (info)
                                                    .huffmanTabs()
                                                    .get((i as i32))
                                                    .increment()
                                                    .at((j as i32))
                                                    .set((k.wrapping_add((1_i32 as u32)) as u8));
                                                k = (99_i32 as u32);
                                            }
                                        }
                                        k = k.wrapping_add(1);
                                    }
                                }
                            }
                            j = j.wrapping_add(1);
                        }
                    }
                }
            }
            i = i.wrapping_add(1);
        }
    }
    {
        let mut YdcTab: i32 = 0;
        let mut UdcTab: i32 = 0;
        let mut VdcTab: i32 = 0;
        let mut YacTab: i32 = 0;
        let mut UacTab: i32 = 0;
        let mut VacTab: i32 = 0;
        YdcTab = (shl_i32(
            ((info).components().get(0_i32).DCTableSelector() as i32),
            (1_i32 as u32),
        ));
        UdcTab = (shl_i32(
            ((info).components().get(1_i32).DCTableSelector() as i32),
            (1_i32 as u32),
        ));
        VdcTab = (shl_i32(
            ((info).components().get(2_i32).DCTableSelector() as i32),
            (1_i32 as u32),
        ));
        YacTab = (shl_i32(
            ((info).components().get(0_i32).ACTableSelector() as i32),
            (1_i32 as u32),
        ))
        .wrapping_add(1_i32);
        UacTab = (shl_i32(
            ((info).components().get(1_i32).ACTableSelector() as i32),
            (1_i32 as u32),
        ))
        .wrapping_add(1_i32);
        VacTab = (shl_i32(
            ((info).components().get(2_i32).ACTableSelector() as i32),
            (1_i32 as u32),
        ))
        .wrapping_add(1_i32);
        statics::dolphin__thp__THPDec::Ydchuff(ctx).set_value((info).huffmanTabs().get(YdcTab));
        statics::dolphin__thp__THPDec::Udchuff(ctx).set_value((info).huffmanTabs().get(UdcTab));
        statics::dolphin__thp__THPDec::Vdchuff(ctx).set_value((info).huffmanTabs().get(VdcTab));
        statics::dolphin__thp__THPDec::Yachuff(ctx).set_value((info).huffmanTabs().get(YacTab));
        statics::dolphin__thp__THPDec::Uachuff(ctx).set_value((info).huffmanTabs().get(UacTab));
        statics::dolphin__thp__THPDec::Vachuff(ctx).set_value((info).huffmanTabs().get(VacTab));
    }
}

pub fn THPDec_8032F8D4<'a>(ctx: &'a Ctx, data: Val<'a, u8>, out: THPDec_8032FD40_Data<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x58);
    let hSample: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x0);
    let vSample: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x4);
    let componentId: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x8);
    let quantizationSelector: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0xc);
    let tag: ArrV<'a, u8, 5> = frame_at(ctx, &__frame, 0x10);
    let mut data = data;
    let mut out = out;
    let mut marker: u8 = 0;
    let mut componentCount: u8 = 0;
    ctx.write_bytes(Handle::addr(tag), b"\x4a\x46\x49\x46\x00");
    let mut i: u8 = 0;
    let mut valid: u8 = 0;
    let mut j: u32 = 0;
    let mut length: u16 = 0;
    valid = (0_i32 as u8);
    let _ = fns::memset(ctx, Handle::cast::<Addr<'a>>(out), 0_i32, (12_i32 as u32));
    {
        let mut soi0: u8 = ({
            let __t1 = data;
            data = Handle::add(data, 1);
            __t1
        })
        .get();
        let mut soi1: u8 = ({
            let __t2 = data;
            data = Handle::add(data, 1);
            __t2
        })
        .get();
        if ((soi0 as i32) != 255_i32) || ((soi1 as i32) != 216_i32) {
            return 0_i32;
        }
    }
    {
        'l1: loop {
            'c2: {
                if (({
                    let __t3 = data;
                    data = Handle::add(data, 1);
                    __t3
                })
                .get() as i32)
                    != 255_i32
                {
                    return 0_i32;
                }
                'l3: while (((data).get() as i8) as i32) == 255_i32 {
                    'c4: {
                        data = Handle::add(data, 1);
                    }
                }
                marker = ({
                    let __t4 = data;
                    data = Handle::add(data, 1);
                    __t4
                })
                .get();
                if (marker as i32) == 192_i32 {
                    (out).set__pad(
                        ((((Handle::add(data, 4_i32)).get() as i32)
                            | (shl_i32(((Handle::add(data, 3_i32)).get() as i32), (8_i32 as u32))))
                            as u16),
                    );
                    (out).set_val1(
                        ((((Handle::add(data, 6_i32)).get() as i32)
                            | (shl_i32(((Handle::add(data, 5_i32)).get() as i32), (8_i32 as u32))))
                            as u16),
                    );
                    componentCount = (Handle::add(data, 7_i32)).get();
                    data = Handle::add(data, 8_i32);
                    if (componentCount as i32) != 3_i32 {
                        return 0_i32;
                    }
                    {
                        i = (0_i32 as u8);
                        'l5: while (i as i32) < (componentCount as i32) {
                            'c6: {
                                let mut factors: u8 = 0;
                                componentId.at((i as i32)).set(
                                    ({
                                        let __t5 = data;
                                        data = Handle::add(data, 1);
                                        __t5
                                    })
                                    .get(),
                                );
                                factors = ({
                                    let __t6 = data;
                                    data = Handle::add(data, 1);
                                    __t6
                                })
                                .get();
                                hSample
                                    .at((i as i32))
                                    .set(((sar_i32((factors as i32), (4_i32 as u32))) as u8));
                                vSample
                                    .at((i as i32))
                                    .set((((factors as i32) & 15_i32) as u8));
                                quantizationSelector.at((i as i32)).set(
                                    ({
                                        let __t7 = data;
                                        data = Handle::add(data, 1);
                                        __t7
                                    })
                                    .get(),
                                );
                            }
                            i = i.wrapping_add(1);
                        }
                    }
                    if (div_i32(
                        (hSample.at(0_i32).get() as i32),
                        (hSample.at(1_i32).get() as i32),
                    ) == 2_i32)
                        && (div_i32(
                            (hSample.at(0_i32).get() as i32),
                            (hSample.at(2_i32).get() as i32),
                        ) == 2_i32)
                    {
                        if (div_i32(
                            (vSample.at(0_i32).get() as i32),
                            (vSample.at(1_i32).get() as i32),
                        ) == 2_i32)
                            && (div_i32(
                                (vSample.at(0_i32).get() as i32),
                                (vSample.at(2_i32).get() as i32),
                            ) == 2_i32)
                        {
                            (out).set_val2((4_i32 as u8));
                        } else if ((vSample.at(0_i32).get() as i32)
                            == (vSample.at(1_i32).get() as i32))
                            && ((vSample.at(0_i32).get() as i32)
                                == (vSample.at(2_i32).get() as i32))
                        {
                            (out).set_val2((2_i32 as u8));
                        }
                    } else if ((hSample.at(0_i32).get() as i32) == (hSample.at(1_i32).get() as i32))
                        && ((hSample.at(0_i32).get() as i32) == (hSample.at(2_i32).get() as i32))
                    {
                        if ((vSample.at(0_i32).get() as i32) == (vSample.at(1_i32).get() as i32))
                            && ((vSample.at(0_i32).get() as i32)
                                == (vSample.at(2_i32).get() as i32))
                        {
                            (out).set_val2((1_i32 as u8));
                        }
                    } else {
                        return 0_i32;
                    }
                } else if (marker as i32) == 224_i32 {
                    length = (({
                        let __t8 = data;
                        data = Handle::add(data, 1);
                        __t8
                    })
                    .get() as u16);
                    length = (((shl_i32((length as i32), (8_i32 as u32)))
                        | (({
                            let __t9 = data;
                            data = Handle::add(data, 1);
                            __t9
                        })
                        .get() as i32)) as u16);
                    {
                        i = (0_i32 as u8);
                        'l7: while (i as i32) < 5_i32 {
                            'c8: {
                                componentCount = ({
                                    let __t10 = data;
                                    data = Handle::add(data, 1);
                                    __t10
                                })
                                .get();
                                if (componentCount as i32) != (tag.at((i as i32)).get() as i32) {
                                    return 0_i32;
                                }
                            }
                            i = i.wrapping_add(1);
                        }
                    }
                    valid = (1_i32 as u8);
                    {
                        j = (0_i32 as u32);
                        'l9: while j < (((length as i32).wrapping_sub(7_i32)) as u32) {
                            'c10: {
                                data = Handle::add(data, 1);
                            }
                            j = j.wrapping_add(1);
                        }
                    }
                } else if (marker as i32) == 218_i32 {
                    break 'l1;
                } else if (192_i32 <= (marker as i32)) && ((marker as i32) <= 254_i32) {
                    length = ((((Handle::add(data, 1_i32)).get() as i32)
                        | (shl_i32(((Handle::add(data, 0_i32)).get() as i32), (8_i32 as u32))))
                        as u16);
                    data = Handle::add(data, 2_i32);
                    {
                        j = (0_i32 as u32);
                        'l11: while j < (((length as i32).wrapping_sub(2_i32)) as u32) {
                            'c12: {
                                data = Handle::add(data, 1);
                            }
                            j = j.wrapping_add(1);
                        }
                    }
                }
                if (((out).val2() as i32) != 0_i32) && ((valid as i32) != 0_i32) {
                    break 'l1;
                }
            }
        }
    }
    return 1_i32;
}

pub fn THPDec_8032FD40<'a>(ctx: &'a Ctx, data: THPDec_8032FD40_Data<'a>, num: u16) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut data = data;
    let mut num = num;
    let mut base: i32 = (data).val0().wrapping_add(0x4028_i32);
    let mut a: i32 = 0;
    if ((data).val2() as i32) != 4_i32 {
        fns::OSReport(
            ctx,
            statics::dolphin__thp__THPDec::__THP420Error(ctx).at(0),
            &[],
        );
        return 0_i32;
    }
    a = (div_i32(((data).val1() as i32), 2_i32))
        .wrapping_mul((div_i32((num as i32), 2_i32)))
        .wrapping_mul(2_i32)
        .wrapping_add((((data).val1() as i32).wrapping_mul((num as i32))));
    base = base.wrapping_add(a);
    return base;
}

pub fn THPVideoDecode<'a>(
    ctx: &'a Ctx,
    hdr: Addr<'a>,
    status_out: Addr<'a>,
    work: _THPFileInfo<'a>,
    data: Addr<'a>,
    desc: THPDec_8032FD40_Data<'a>,
) -> _THPFileInfo<'a> {
    let __frame = ctx.stack_frame(0x38);
    let mut hdr = hdr;
    let mut status_out = status_out;
    let mut work = work;
    let mut data = data;
    let mut desc = desc;
    let mut done: u8 = 0;
    let mut info: _THPFileInfo<'a> = null(ctx);
    let mut header: THPVideoDecodeHeader<'a> = null(ctx);
    let mut statusOut: Val<'a, u8> = null(ctx);
    let mut status: u8 = 0;
    let mut length: i32 = 0;
    let mut i: u32 = 0;
    'goto__err_exit: {
        'goto__err_bad_status: {
            'goto__err_bad_syntax: {
                info = work;
                header = Handle::cast::<THPVideoDecodeHeader<'a>>(hdr);
                statusOut = Handle::cast::<Val<'a, u8>>(status_out);
                fns::DCZeroRange(ctx, Handle::cast::<Addr<'a>>(info), (0x920_i32 as u32));
                (info).set_scratch(Handle::cast::<Val<'a, u8>>(info));
                (info).set_scratch(Handle::add((info).scratch(), 0x920_i32));
                (info).set_xSize((header).xSize());
                (info).set_ySize((header).ySize());
                (info).set_file((info).scanStart());
                (info).set_cnt((33_i32 as u32));
                (info).set_x8EC((0_i32 as u16));
                (info).set_x8EE((0_i32 as u16));
                (info).set_x8D2((0_i32 as u16));
                (info).set_x8E8((0_i32 as u16));
                (info).set_x8EA((0_i32 as u16));
                (info).set_x7D((0_i32 as u8));
                (info).set_dataStart(Handle::cast::<Val<'a, u8>>(data));
                fns::THPDec_803300E0(ctx, info);
                done = (0_i32 as u8);
                (info).set_file((info).dataStart());
                {
                    'l1: loop {
                        'c2: {
                            if ((({
                                let __t1 = (info).file();
                                (info).set_file(Handle::add((info).file(), 1));
                                __t1
                            })
                            .get()) as i32)
                                != 255_i32
                            {
                                break 'goto__err_bad_syntax;
                            }
                            'l3: while (((info).file()).get() as i32) == 255_i32 {
                                'c4: {
                                    (info).set_file(Handle::add((info).file(), 1));
                                }
                            }
                            status = (({
                                let __t2 = (info).file();
                                (info).set_file(Handle::add((info).file(), 1));
                                __t2
                            })
                            .get());
                            if (status as i32) <= 215_i32 {
                                if (status as i32) == 196_i32 {
                                    status = statics::dolphin__thp__THPDec::__THPReadHuffmanTableSpecification(ctx, info);
                                    if (status as i32) != 0_i32 {
                                        break 'goto__err_bad_status;
                                    }
                                } else if (status as i32) == 192_i32 {
                                    status = statics::dolphin__thp__THPDec::__THPReadFrameHeader(
                                        ctx, info,
                                    );
                                    if (status as i32) != 0_i32 {
                                        break 'goto__err_bad_status;
                                    }
                                } else {
                                    (statusOut).set((11_i32 as u8));
                                    return null::<_THPFileInfo<'a>>(ctx);
                                }
                            } else if (216_i32 <= (status as i32)) && ((status as i32) <= 223_i32) {
                                if (status as i32) == 221_i32 {
                                    let _ = statics::dolphin__thp__THPDec::__THPRestartDefinition(
                                        ctx, info,
                                    );
                                } else if (status as i32) == 219_i32 {
                                    status =
                                        statics::dolphin__thp__THPDec::__THPReadQuantizationTable(
                                            ctx, info,
                                        );
                                    if (status as i32) != 0_i32 {
                                        break 'goto__err_bad_status;
                                    }
                                } else if (status as i32) == 218_i32 {
                                    status = statics::dolphin__thp__THPDec::__THPReadScaneHeader(
                                        ctx, info,
                                    );
                                    if (status as i32) != 0_i32 {
                                        break 'goto__err_bad_status;
                                    }
                                    done = (1_i32 as u8);
                                    (info).set_scanStart((info).file());
                                } else if (status as i32) != 216_i32 {
                                    (statusOut).set((11_i32 as u8));
                                    return null::<_THPFileInfo<'a>>(ctx);
                                }
                            } else if 224_i32 <= (status as i32) {
                                if (status as i32) == 224_i32 {
                                    status = fns::THPDec_80330158(ctx, info);
                                    if (status as i32) != 0_i32 {
                                        break 'goto__err_bad_status;
                                    }
                                } else if (225_i32 <= (status as i32))
                                    && ((status as i32) <= 239_i32)
                                {
                                    let _ = fns::THPDec_803302EC(ctx, (info).file_ref());
                                } else if (status as i32) == 254_i32 {
                                    length = ((shl_i32(
                                        ((Handle::add((info).file(), 0_i32)).get() as i32),
                                        (8_i32 as u32),
                                    )) | ((Handle::add((info).file(), 1_i32)).get()
                                        as i32));
                                    (info).set_file(Handle::add((info).file(), 2_i32));
                                    {
                                        i = (0_i32 as u32);
                                        'l5: while i < (length.wrapping_sub(2_i32) as u32) {
                                            'c6: {
                                                (info).set_file(Handle::add((info).file(), 1));
                                            }
                                            i = i.wrapping_add(1);
                                        }
                                    }
                                } else {
                                    (statusOut).set((11_i32 as u8));
                                    return null::<_THPFileInfo<'a>>(ctx);
                                }
                            }
                            if (done != 0) {
                                (statusOut).set((0_i32 as u8));
                                return work;
                            }
                        }
                    }
                }
            }
            (statusOut).set((3_i32 as u8));
            break 'goto__err_exit;
        }
        (statusOut).set(status);
    }
    return null::<_THPFileInfo<'a>>(ctx);
    #[allow(unreachable_code)]
    return null(ctx);
}

pub fn THPDec_803300E0<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) {
    let mut info = info;
    let mut p: Val<'a, u8> = null(ctx);
    let mut i: u8 = 0;
    p = ptr::<Val<'a, u8>>(
        ctx,
        ((Handle::addr(((info).scratch()))
            .wrapping_add((32_i32 as u32))
            .wrapping_sub((1_i32 as u32)))
            & ((!(32_i32.wrapping_sub(1_i32))) as u32)) as u32,
    );
    (info).set_scratch(Handle::add(p, 16_i32.wrapping_mul(128_i32)));
    {
        i = (0_i32 as u8);
        'l1: while (i as i32) < 16_i32 {
            'c2: {
                (info)
                    .mcuBuffer()
                    .at((i as i32))
                    .set(Handle::cast::<Val<'a, i16>>(p));
                p = Handle::add(p, 128_i32);
            }
            i = i.wrapping_add(1);
        }
    }
}

pub fn THPDec_80330158<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let __frame = ctx.stack_frame(0x20);
    let tag: ArrV<'a, u8, 5> = frame_at(ctx, &__frame, 0x0);
    let mut info = info;
    ctx.write_bytes(Handle::addr(tag), b"\x4a\x46\x49\x46\x00");
    let mut length: u16 = 0;
    let mut i: u32 = 0;
    let mut xThumb: u8 = 0;
    let mut yThumb: u8 = 0;
    let mut version: u16 = 0;
    let mut units: u8 = 0;
    let mut segmentLength: u32 = 0;
    length = (((shl_i32(
        ((Handle::add((info).file(), 0_i32)).get() as i32),
        (8_i32 as u32),
    )) | ((Handle::add((info).file(), 1_i32)).get() as i32)) as u16);
    (info).set_file(Handle::add((info).file(), 2_i32));
    {
        i = (0_i32 as u32);
        'l1: while i < (5_i32 as u32) {
            'c2: {
                if (({
                    let __t1 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t1
                })
                .get() as i32)
                    != (tag.at((i as i32)).get() as i32)
                {
                    return (3_i32 as u8);
                }
            }
            i = i.wrapping_add(1);
        }
    }
    version = (((shl_i32(
        ((Handle::add((info).file(), 0_i32)).get() as i32),
        (8_i32 as u32),
    )) | ((Handle::add((info).file(), 1_i32)).get() as i32)) as u16);
    (info).set_file(Handle::add((info).file(), 2_i32));
    units = ({
        let __t2 = (info).file();
        (info).set_file(Handle::add((info).file(), 1));
        __t2
    })
    .get();
    (info).set_file(Handle::add((info).file(), 1_i32));
    (info).set_file(Handle::add((info).file(), 1_i32));
    (info).set_file(Handle::add((info).file(), 1_i32));
    (info).set_file(Handle::add((info).file(), 1_i32));
    xThumb = ({
        let __t3 = (info).file();
        (info).set_file(Handle::add((info).file(), 1));
        __t3
    })
    .get();
    yThumb = ({
        let __t4 = (info).file();
        (info).set_file(Handle::add((info).file(), 1));
        __t4
    })
    .get();
    if ((xThumb as i32) != 0_i32) || ((yThumb as i32) != 0_i32) {
        return (7_i32 as u8);
    }
    segmentLength = (((Handle::addr((info).file()).wrapping_sub(Handle::addr((info).dataStart()))
        as i32)
        / 1) as u32);
    if ((length as i32).wrapping_add(4_i32) as u32) != segmentLength {
        return (8_i32 as u8);
    }
    return (0_i32 as u8);
}

pub fn THPDec_803302EC<'a>(ctx: &'a Ctx, data: Ptr<'a, Val<'a, u8>>) -> i32 {
    let mut data = data;
    let mut i: u32 = 0;
    let mut ptr_: Val<'a, u8> = (data).get();
    let mut high: u16 = ((Handle::add(ptr_, 0_i32)).get() as u16);
    let mut low: u16 = ((Handle::add(ptr_, 1_i32)).get() as u16);
    let mut count: u16 = (((shl_i32((high as i32), (8_i32 as u32))) | (low as i32)) as u16);
    {
        i = (0_i32 as u32);
        'l1: while i < (count as u32) {
            'c2: {
                (data).set(Handle::add((data).get(), 1));
            }
            i = i.wrapping_add(1);
        }
    }
    return 0_i32;
}

pub fn __THPReadFrameHeader<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let mut info = info;
    let mut i: u8 = 0;
    let mut j: u8 = 0;
    let mut k: u8 = 0;
    let mut comp: _THPComponent<'a> = null(ctx);
    let mut utmp8: u8 = 0;
    let mut ySize: u16 = 0;
    (info).set_file(Handle::add((info).file(), 2_i32));
    utmp8 = (({
        let __t1 = (info).file();
        (info).set_file(Handle::add((info).file(), 1));
        __t1
    })
    .get());
    if (utmp8 as i32) != 8_i32 {
        return (10_i32 as u8);
    }
    (info).set_yPixelSize(
        ((shl_i32(
            ((Handle::add(((info).file()), 0_i32)).get() as i32),
            (8_i32 as u32),
        ) | ((Handle::add(((info).file()), 1_i32)).get() as i32)) as u16),
    );
    (info).set_file(Handle::add((info).file(), 2_i32));
    (info).set_xPixelSize(
        ((shl_i32(
            ((Handle::add(((info).file()), 0_i32)).get() as i32),
            (8_i32 as u32),
        ) | ((Handle::add(((info).file()), 1_i32)).get() as i32)) as u16),
    );
    (info).set_file(Handle::add((info).file(), 2_i32));
    (info).set_nComponents(
        (({
            let __t2 = (info).file();
            (info).set_file(Handle::add((info).file(), 1));
            __t2
        })
        .get()),
    );
    if (((info).nComponents() as i32) != 3_i32) && (((info).nComponents() as i32) != 1_i32) {
        return (12_i32 as u8);
    }
    {
        i = (0_i32 as u8);
        'l1: while (i as i32) < ((info).nComponents() as i32) {
            'c2: {
                (info).components().get((i as i32)).set_componentID(
                    (({
                        let __t3 = (info).file();
                        (info).set_file(Handle::add((info).file(), 1));
                        __t3
                    })
                    .get()),
                );
                utmp8 = (({
                    let __t4 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t4
                })
                .get());
                (info)
                    .components()
                    .get((i as i32))
                    .set_samplingH(((sar_i32((utmp8 as i32), (4_i32 as u32))) as u8));
                (info)
                    .components()
                    .get((i as i32))
                    .set_samplingV((((utmp8 as i32) & 15_i32) as u8));
                (info)
                    .components()
                    .get((i as i32))
                    .set_quantizationTableSelector(
                        (({
                            let __t5 = (info).file();
                            (info).set_file(Handle::add((info).file(), 1));
                            __t5
                        })
                        .get()),
                    );
            }
            i = i.wrapping_add(1);
        }
    }
    (info).set_samplingHMax((1_i32 as u8));
    (info).set_samplingVMax((1_i32 as u8));
    {
        j = (0_i32 as u8);
        'l3: while (j as i32) < ((info).nComponents() as i32) {
            'c4: {
                comp = (info).components().get((j as i32));
                (info).set_samplingHMax(
                    ((if ((info).samplingHMax() as i32) > ((comp).samplingH() as i32) {
                        ((info).samplingHMax() as i32)
                    } else {
                        ((comp).samplingH() as i32)
                    }) as u8),
                );
                (info).set_samplingVMax(
                    ((if ((info).samplingVMax() as i32) > ((comp).samplingV() as i32) {
                        ((info).samplingVMax() as i32)
                    } else {
                        ((comp).samplingV() as i32)
                    }) as u8),
                );
            }
            j = j.wrapping_add(1);
        }
    }
    ySize = (info).yPixelSize();
    (info).set_x8D4(
        ((div_i32(
            (((ySize) as i32).wrapping_add(
                ((div_i32(
                    (((ySize) as i32).wrapping_add(
                        ((((info).samplingVMax() as i32).wrapping_mul(8_i32)).wrapping_sub(1_i32)),
                    )),
                    (((info).samplingVMax() as i32).wrapping_mul(8_i32)),
                ))
                .wrapping_sub(1_i32)),
            )),
            (div_i32(
                (((ySize) as i32).wrapping_add(
                    ((((info).samplingVMax() as i32).wrapping_mul(8_i32)).wrapping_sub(1_i32)),
                )),
                (((info).samplingVMax() as i32).wrapping_mul(8_i32)),
            )),
        )) as u16),
    );
    {
        k = (0_i32 as u8);
        'l5: while (k as i32) < ((info).nComponents() as i32) {
            'c6: {
                (info).components().get((k as i32)).set_x08(
                    ((div_i32(
                        ((((info).xPixelSize() as i32).wrapping_mul(
                            ((info).components().get((k as i32)).samplingH() as i32),
                        ))
                        .wrapping_add(((((info).samplingHMax()) as i32).wrapping_sub(1_i32)))),
                        (((info).samplingHMax()) as i32),
                    )) as u32),
                );
                (info).components().get((k as i32)).set_x0C(
                    ((div_i32(
                        ((((info).yPixelSize() as i32).wrapping_mul(
                            ((info).components().get((k as i32)).samplingV() as i32),
                        ))
                        .wrapping_add(((((info).samplingVMax()) as i32).wrapping_sub(1_i32)))),
                        (((info).samplingVMax()) as i32),
                    )) as u32),
                );
            }
            k = k.wrapping_add(1);
        }
    }
    return (0_i32 as u8);
}

pub fn __THPReadQuantizationTable<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let __frame = ctx.stack_frame(0x190);
    let q_temp: ArrV<'a, F32, 64> = frame_at(ctx, &__frame, 0x0);
    let mut info = info;
    let mut length: u16 = 0;
    let mut id: u16 = 0;
    let mut i: u16 = 0;
    let mut row: u16 = 0;
    let mut col: u16 = 0;
    length = ((shl_i32(
        ((Handle::add(((info).file()), 0_i32)).get() as i32),
        (8_i32 as u32),
    ) | ((Handle::add(((info).file()), 1_i32)).get() as i32)) as u16);
    (info).set_file(Handle::add((info).file(), 2_i32));
    length = ((length as i32).wrapping_sub(2_i32) as u16);
    {
        'l1: loop {
            'c2: {
                id = ((({
                    let __t1 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t1
                })
                .get()) as u16);
                {
                    i = (0_i32 as u16);
                    'l3: while (i as i32) < 64_i32 {
                        'c4: {
                            q_temp
                                .at((statics::dolphin__thp__THPDec::__THPJpegNaturalOrder(ctx)
                                    .at((i as i32))
                                    .get() as i32))
                                .set(fp::frsp(
                                    (({
                                        let __t2 = (info).file();
                                        (info).set_file(Handle::add((info).file(), 1));
                                        __t2
                                    })
                                    .get()) as f64,
                                ));
                        }
                        i = i.wrapping_add(1);
                    }
                }
                (info).set_validQuantTabs(
                    ((((info).validQuantTabs() as i32) | shl_i32(1_i32, ((id as i32) as u32)))
                        as u8),
                );
                i = (0_i32 as u16);
                {
                    row = (0_i32 as u16);
                    'l5: while (row as i32) < 8_i32 {
                        'c6: {
                            {
                                col = (0_i32 as u16);
                                'l7: while (col as i32) < 8_i32 {
                                    'c8: {
                                        (info)
                                            .quantTabs()
                                            .get((id as i32))
                                            .at((i as i32))
                                            .set(fp::frsp(fp::fmul(
                                            fp::fmul(
                                                q_temp.at((i as i32)).get(),
                                                statics::dolphin__thp__THPDec::__THPAANScaleFactor(
                                                    ctx,
                                                )
                                                .at((row as i32))
                                                .get(),
                                            ),
                                            statics::dolphin__thp__THPDec::__THPAANScaleFactor(ctx)
                                                .at((col as i32))
                                                .get(),
                                        )));
                                        i = i.wrapping_add(1);
                                    }
                                    col = col.wrapping_add(1);
                                }
                            }
                        }
                        row = row.wrapping_add(1);
                    }
                }
                length = ((length as i32).wrapping_sub(65_i32) as u16);
                if !(length != 0) {
                    break 'l1;
                }
            }
        }
    }
    return (0_i32 as u8);
}

pub fn __THPReadHuffmanTableSpecification<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let __frame = ctx.stack_frame(0x28);
    let mut info = info;
    let mut t_class: u8 = 0;
    let mut id: u8 = 0;
    let mut i: u8 = 0;
    let mut tab_index: u8 = 0;
    let mut length: u16 = 0;
    let mut num_Vij: u16 = 0;
    let mut huffmanBits: Val<'a, u8> = null(ctx);
    let mut result: u8 = 0;
    length = ((shl_i32(
        ((Handle::add(((info).file()), 0_i32)).get() as i32),
        (8_i32 as u32),
    ) | ((Handle::add(((info).file()), 1_i32)).get() as i32)) as u16);
    (info).set_file(Handle::add((info).file(), 2_i32));
    length = ((length as i32).wrapping_sub(2_i32) as u16);
    {
        'l1: loop {
            'c2: {
                i = (({
                    let __t1 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t1
                })
                .get());
                id = (((i as i32) & 15_i32) as u8);
                t_class = ((sar_i32((i as i32), (4_i32 as u32))) as u8);
                huffmanBits = (info).file();
                tab_index =
                    (((shl_i32((id as i32), (1_i32 as u32))).wrapping_add((t_class as i32))) as u8);
                num_Vij = (0_i32 as u16);
                {
                    i = (0_i32 as u8);
                    'l3: while (i as i32) < 16_i32 {
                        'c4: {
                            num_Vij = ((num_Vij as i32).wrapping_add(
                                ((({
                                    let __t2 = (info).file();
                                    (info).set_file(Handle::add((info).file(), 1));
                                    __t2
                                })
                                .get()) as i32),
                            ) as u16);
                        }
                        i = i.wrapping_add(1);
                    }
                }
                (info)
                    .huffmanTabs()
                    .get((tab_index as i32))
                    .set_bits(huffmanBits);
                (info)
                    .huffmanTabs()
                    .get((tab_index as i32))
                    .set_Vij((info).file());
                (info)
                    .huffmanTabs()
                    .get((tab_index as i32))
                    .set_numVij(num_Vij);
                (info).set_file(Handle::add((info).file(), (num_Vij as i32)));
                result = statics::dolphin__thp__THPDec::__THPHuffGenerateSizeTable(
                    ctx,
                    info,
                    tab_index,
                    (Handle::addr(huffmanBits) as i32),
                );
                if (result != 0) {
                    return result;
                }
                result =
                    statics::dolphin__thp__THPDec::__THPHuffGenerateCodeTable(ctx, info, tab_index);
                if (result != 0) {
                    return result;
                }
                let _ = statics::dolphin__thp__THPDec::__THPHuffGenerateDecoderTables(
                    ctx, info, tab_index,
                );
                (info).set_validHuffmanTabs(
                    ((((info).validHuffmanTabs() as i32)
                        | shl_i32(1_i32, ((tab_index as i32) as u32))) as u8),
                );
                length =
                    ((length as i32).wrapping_sub(17_i32.wrapping_add((num_Vij as i32))) as u16);
                if (length as i32) == 0_i32 {
                    break 'l1;
                }
            }
        }
    }
    return (0_i32 as u8);
}

pub fn __THPReadScaneHeader<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let __frame = ctx.stack_frame(0x8);
    let mut info = info;
    let mut numComponents: u8 = 0;
    let mut i: u8 = 0;
    let mut ptr_: Val<'a, u8> = null(ctx);
    (info).set_file(Handle::add((info).file(), 2_i32));
    ptr_ = (info).file();
    (info).set_file(Handle::add((info).file(), 1));
    numComponents = (ptr_).get();
    if (numComponents as i32) != ((info).nComponents() as i32) {
        return (12_i32 as u8);
    }
    {
        i = (0_i32 as u8);
        'l1: while (i as i32) < (numComponents as i32) {
            'c2: {
                let mut selectors: u8 = 0;
                let mut blocksPerRow: u16 = 0;
                let mut rows: u16 = 0;
                let mut shift: i32 = 0;
                selectors = ({
                    let __t1 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t1
                })
                .get();
                selectors = ({
                    let __t2 = (info).file();
                    (info).set_file(Handle::add((info).file(), 1));
                    __t2
                })
                .get();
                (info)
                    .components()
                    .get((i as i32))
                    .set_DCTableSelector(((sar_i32((selectors as i32), (4_i32 as u32))) as u8));
                (info)
                    .components()
                    .get((i as i32))
                    .set_ACTableSelector((((selectors as i32) & 15_i32) as u8));
                if !((((info).validHuffmanTabs() as i32)
                    & (shl_i32(
                        1_i32,
                        ((sar_i32((selectors as i32), (4_i32 as u32))) as u32),
                    )))
                    != 0)
                {
                    return (15_i32 as u8);
                }
                if !((((info).validHuffmanTabs() as i32)
                    & (shl_i32(
                        1_i32,
                        ((((selectors as i32) & 15_i32).wrapping_add(1_i32)) as u32),
                    )))
                    != 0)
                {
                    return (15_i32 as u8);
                }
                (info).set_x74((info).xSize());
                (info).set_decompressedY((info).ySize());
                blocksPerRow = ((info).components().get((i as i32)).x08() as u16);
                rows = ((div_i32(
                    ((((info).decompressedY()) as i32)
                        .wrapping_add(((((info).x8D4()) as i32).wrapping_sub(1_i32)))),
                    (((info).x8D4()) as i32),
                )) as u16);
                rows = ((rows as i32).wrapping_add(
                    (if rem_i32(((info).decompressedY() as i32), ((info).x8D4() as i32)) == 0_i32 {
                        0_i32
                    } else {
                        1_i32
                    }),
                ) as u16);
                rows = ((rows as i32).wrapping_mul(((info).x8D4() as i32)) as u16);
                shift = ((info).samplingVMax() as i32)
                    .wrapping_sub(((info).components().get((i as i32)).samplingV() as i32));
                rows = (sar_i32((rows as i32), (shift as u32)) as u16);
                (info)
                    .components()
                    .get((i as i32))
                    .set_x10(Handle::addr((info).scratch()));
                (info).set_scratch(Handle::add(
                    (info).scratch(),
                    (blocksPerRow as i32).wrapping_mul((rows as i32)),
                ));
            }
            i = i.wrapping_add(1);
        }
    }
    (info).set_file(Handle::add((info).file(), 3_i32));
    return fns::THPDec_803310CC(ctx, info);
}

pub fn __THPHuffGenerateSizeTable<'a>(
    ctx: &'a Ctx,
    info: _THPFileInfo<'a>,
    tab_index: u8,
    huffmanBits: i32,
) -> u8 {
    let __frame = ctx.stack_frame(0x28);
    let mut info = info;
    let mut tab_index = tab_index;
    let mut huffmanBits = huffmanBits;
    let mut bits: Val<'a, u8> = null(ctx);
    let mut p: i32 = 0;
    let mut l: i32 = 0;
    let mut i: i32 = 0;
    bits = ptr::<Val<'a, u8>>(ctx, huffmanBits as u32);
    p = 0_i32;
    {
        l = 1_i32;
        'l1: while l <= 16_i32 {
            'c2: {
                p = p.wrapping_add(((Handle::add(bits, l.wrapping_sub(1_i32))).get() as i32));
            }
            l = l.wrapping_add(1);
        }
    }
    (info)
        .huffmanTabs()
        .get((tab_index as i32))
        .set_sizeTab(Handle::cast::<Val<'a, i8>>((info).scratch()));
    (info).set_scratch(Handle::add((info).scratch(), p.wrapping_add(1_i32)));
    p = 0_i32;
    {
        l = 1_i32;
        'l3: while l <= 16_i32 {
            'c4: {
                i = ((Handle::add(bits, l.wrapping_sub(1_i32))).get() as i32);
                'l5: while ({
                    let __t2 = i;
                    i = i.wrapping_sub(1);
                    __t2
                } != 0)
                {
                    'c6: {
                        (Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), {
                            let __t1 = p;
                            p = p.wrapping_add(1);
                            __t1
                        }))
                        .set((l as i8));
                    }
                }
            }
            l = l.wrapping_add(1);
        }
    }
    (Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), p)).set((0_i32 as i8));
    (info)
        .huffmanTabs()
        .get((tab_index as i32))
        .set_numCodes((p as u32));
    return (0_i32 as u8);
}

pub fn __THPHuffGenerateCodeTable<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>, tab_index: u8) -> u8 {
    let mut info = info;
    let mut tab_index = tab_index;
    let mut si: i32 = 0;
    let mut code: u32 = 0;
    let mut p: i32 = 0;
    p = 0_i32;
    si = ((Handle::add(
        (info).huffmanTabs().get((tab_index as i32)).sizeTab(),
        0_i32,
    ))
    .get() as i32);
    'l1: while ((Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), p)).get() != 0)
    {
        'c2: {
            'l3: while ((Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), p))
                .get() as i32)
                == si
            {
                'c4: {
                    p = p.wrapping_add(1);
                }
            }
            si = si.wrapping_add(1);
        }
    }
    (info)
        .huffmanTabs()
        .get((tab_index as i32))
        .set_codeTab(Handle::cast::<Val<'a, u32>>((info).scratch()));
    (info).set_scratch(Handle::add(
        (info).scratch(),
        ((p as u32).wrapping_mul(4_u32) as i32),
    ));
    p = 0_i32;
    code = (0_i32 as u32);
    si = ((Handle::add(
        (info).huffmanTabs().get((tab_index as i32)).sizeTab(),
        0_i32,
    ))
    .get() as i32);
    'l5: while ((Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), p)).get() != 0)
    {
        'c6: {
            'l7: while ((Handle::add((info).huffmanTabs().get((tab_index as i32)).sizeTab(), p))
                .get() as i32)
                == si
            {
                'c8: {
                    (Handle::add((info).huffmanTabs().get((tab_index as i32)).codeTab(), {
                        let __t1 = p;
                        p = p.wrapping_add(1);
                        __t1
                    }))
                    .set(code);
                    code = code.wrapping_add(1);
                }
            }
            code = shl_u32(code, (1_i32 as u32));
            si = si.wrapping_add(1);
        }
    }
    return (0_i32 as u8);
}

pub fn __THPHuffGenerateDecoderTables<'a>(
    ctx: &'a Ctx,
    info: _THPFileInfo<'a>,
    tabIndex: u8,
) -> i32 {
    let mut info = info;
    let mut tabIndex = tabIndex;
    let mut p: i32 = 0;
    let mut l: i32 = 0;
    let mut h: _THPHuffmanTab<'a> = null(ctx);
    p = 0_i32;
    h = (info).huffmanTabs().get((tabIndex as i32));
    {
        l = 1_i32;
        'l1: while l <= 16_i32 {
            'c2: {
                if ((Handle::add((h).bits(), l.wrapping_sub(1_i32))).get() != 0) {
                    (h).valPtr().at(l).set(
                        ((p as u32).wrapping_sub((Handle::add((h).codeTab(), p)).get()) as i32),
                    );
                    p = p.wrapping_add(
                        ((Handle::add((h).bits(), l.wrapping_sub(1_i32))).get() as i32),
                    );
                    (h).maxCode()
                        .at(l)
                        .set(((Handle::add((h).codeTab(), p.wrapping_sub(1_i32))).get() as i32));
                } else {
                    (h).maxCode().at(l).set(1_i32.wrapping_neg());
                    (h).valPtr().at(l).set(1_i32.wrapping_neg());
                }
            }
            l = l.wrapping_add(1);
        }
    }
    (h).maxCode().at(17_i32).set(0xfffff_i32);
    return 0_i32;
}

pub fn THPDec_803310CC<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let __frame = ctx.stack_frame(0x8);
    let mut info = info;
    let mut i: u32 = 0;
    let mut j: i32 = 0;
    (info).set_MCUsPerRow(
        ((div_i32(
            ((((info).xPixelSize()) as i32).wrapping_add(
                ((((info).samplingHMax() as i32).wrapping_mul(8_i32)).wrapping_sub(1_i32)),
            )),
            (((info).samplingHMax() as i32).wrapping_mul(8_i32)),
        )) as u16),
    );
    (info).set_x8D0(
        ((div_i32(
            ((((info).yPixelSize()) as i32).wrapping_add(
                ((((info).samplingVMax() as i32).wrapping_mul(8_i32)).wrapping_sub(1_i32)),
            )),
            (((info).samplingVMax() as i32).wrapping_mul(8_i32)),
        )) as u16),
    );
    (info).set_x8CE((0_i32 as u16));
    {
        i = (0_i32 as u32);
        'l1: while i < ((info).nComponents() as u32) {
            'c2: {
                let mut c: _THPComponent<'a> = (info).components().get((i as i32));
                (c).set_x28(
                    (div_i32(
                        ((((info).xPixelSize() as i32).wrapping_mul(((c).samplingH() as i32)))
                            .wrapping_add(
                                ((((info).samplingHMax() as i32).wrapping_mul(8_i32))
                                    .wrapping_sub(1_i32)),
                            )),
                        (((info).samplingHMax() as i32).wrapping_mul(8_i32)),
                    )),
                );
                (c).set_x24(
                    (div_i32(
                        ((((info).yPixelSize() as i32).wrapping_mul(((c).samplingV() as i32)))
                            .wrapping_add(
                                ((((info).samplingVMax() as i32).wrapping_mul(8_i32))
                                    .wrapping_sub(1_i32)),
                            )),
                        (((info).samplingVMax() as i32).wrapping_mul(8_i32)),
                    )),
                );
                (c).set_x14(((c).samplingH() as i32));
                (c).set_x18(((c).samplingV() as i32));
                (c).set_x1C((c).x14().wrapping_mul((c).x18()));
                (c).set_x20((c).x14().wrapping_mul(8_i32));
                j = (c).x1C();
                if ((info).x8CE() as i32).wrapping_add((c).x1C()) > 16_i32 {
                    return (17_i32 as u8);
                }
                'l3: while {
                    let __t2 = j;
                    j = j.wrapping_sub(1);
                    __t2
                } > 0_i32
                {
                    'c4: {
                        (info)
                            .x8BC()
                            .at(({
                                let __t1 = (info).x8CE();
                                (info).set_x8CE((info).x8CE().wrapping_add(1));
                                __t1
                            } as i32))
                            .set((i as u8));
                    }
                }
                if ((info).x8CE() as i32) > 6_i32 {
                    fns::OSReport(ctx, cstr(ctx, 0x80400b4c), &[]);
                    return (0_i32 as u8);
                }
                (c).set_predDC((0_i32 as i16));
            }
            i = i.wrapping_add(1);
        }
    }
    return (0_i32 as u8);
}

pub fn __THPRestartDefinition<'a>(ctx: &'a Ctx, info: _THPFileInfo<'a>) -> u8 {
    let mut info = info;
    (info).set_RST((1_i32 as u8));
    (info).set_file(Handle::add((info).file(), 2_i32));
    (info).set_nMCU(
        ((shl_i32(
            ((Handle::add(((info).file()), 0_i32)).get() as i32),
            (8_i32 as u32),
        ) | ((Handle::add(((info).file()), 1_i32)).get() as i32)) as u16),
    );
    (info).set_file(Handle::add((info).file(), 2_i32));
    (info).set_currMCU((info).nMCU());
    return (0_i32 as u8);
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x8032f630,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPPrepBitStream(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8032f8d4,
        |ctx| {
            let (a0, a1): (Val<'_, u8>, THPDec_8032FD40_Data<'_>) = Args::take_all(ctx);
            Ret::put(THPDec_8032F8D4(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8032fd40,
        |ctx| {
            let (a0, a1): (THPDec_8032FD40_Data<'_>, u16) = Args::take_all(ctx);
            Ret::put(THPDec_8032FD40(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8032fdb8,
        |ctx| {
            let (a0, a1, a2, a3, a4): (
                Addr<'_>,
                Addr<'_>,
                _THPFileInfo<'_>,
                Addr<'_>,
                THPDec_8032FD40_Data<'_>,
            ) = Args::take_all(ctx);
            Ret::put(THPVideoDecode(ctx, a0, a1, a2, a3, a4), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803300e0,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(THPDec_803300E0(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80330158,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(THPDec_80330158(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803302ec,
        |ctx| {
            let (a0,): (Ptr<'_, Val<'_, u8>>,) = Args::take_all(ctx);
            Ret::put(THPDec_803302EC(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803303c4,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPReadFrameHeader(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803305cc,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPReadQuantizationTable(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80330970,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPReadHuffmanTableSpecification(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80330b40,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPReadScaneHeader(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80330c98,
        |ctx| {
            let (a0, a1, a2): (_THPFileInfo<'_>, u8, i32) = Args::take_all(ctx);
            Ret::put(__THPHuffGenerateSizeTable(ctx, a0, a1, a2), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80330e30,
        |ctx| {
            let (a0, a1): (_THPFileInfo<'_>, u8) = Args::take_all(ctx);
            Ret::put(__THPHuffGenerateCodeTable(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80330f10,
        |ctx| {
            let (a0, a1): (_THPFileInfo<'_>, u8) = Args::take_all(ctx);
            Ret::put(__THPHuffGenerateDecoderTables(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803310cc,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(THPDec_803310CC(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803312f4,
        |ctx| {
            let (a0,): (_THPFileInfo<'_>,) = Args::take_all(ctx);
            Ret::put(__THPRestartDefinition(ctx, a0), ctx);
        },
        Returns::Int,
    );
}
