// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from libs/dolphin/src/dolphin/os/OS.c. Do not edit; fix the translator or port by hand.
// unit: dolphin/os/OS
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::manual::dolphin__os__OS as manual;
use crate::support::*;
use ssbm_rt::cpu as c;

pub fn OSGetConsoleType<'a>(ctx: &'a Ctx) -> u32 {
    if (!(!Handle::is_null(statics::dolphin__os__OS::BootInfo(ctx).get())))
        || ((statics::dolphin__os__OS::BootInfo(ctx).get()).consoleType() == (0_i32 as u32))
    {
        return (0x10000002_i32 as u32);
    }
    return (statics::dolphin__os__OS::BootInfo(ctx).get()).consoleType();
}

pub fn ClearArena<'a>(ctx: &'a Ctx) {
    let __frame = ctx.stack_frame(0x10);
    if ctx.call::<_, u32>(0x803486b4, ()) != 0x80000000_u32 {
        let _ = {
            let __t2 = {
                let __t1 = Handle::addr(fns::OSGetArenaLo(ctx));
                Handle::addr(fns::OSGetArenaHi(ctx)).wrapping_sub(__t1)
            };
            let __t3 = fns::OSGetArenaLo(ctx);
            fns::memset(ctx, __t3, 0_i32, __t2)
        };
    } else {
        let mut boot_region_start: u32 = ((ptr::<Val<'a, u32>>(ctx, 0x812fdff0_u32 as u32)).get());
        let mut boot_region_end: u32 = ((ptr::<Val<'a, u32>>(ctx, 0x812fdfec_u32 as u32)).get());
        if boot_region_start == (0_i32 as u32) {
            let _ = {
                let __t5 = {
                    let __t4 = Handle::addr(fns::OSGetArenaLo(ctx));
                    Handle::addr(fns::OSGetArenaHi(ctx)).wrapping_sub(__t4)
                };
                let __t6 = fns::OSGetArenaLo(ctx);
                fns::memset(ctx, __t6, 0_i32, __t5)
            };
        } else if Handle::addr(fns::OSGetArenaLo(ctx)) < boot_region_start {
            if Handle::addr(fns::OSGetArenaHi(ctx)) <= boot_region_start {
                let _ = {
                    let __t8 = {
                        let __t7 = Handle::addr(fns::OSGetArenaLo(ctx));
                        Handle::addr(fns::OSGetArenaHi(ctx)).wrapping_sub(__t7)
                    };
                    let __t9 = fns::OSGetArenaLo(ctx);
                    fns::memset(ctx, __t9, 0_i32, __t8)
                };
            } else {
                let _ = {
                    let __t10 =
                        boot_region_start.wrapping_sub(Handle::addr(fns::OSGetArenaLo(ctx)));
                    let __t11 = fns::OSGetArenaLo(ctx);
                    fns::memset(ctx, __t11, 0_i32, __t10)
                };
                if Handle::addr(fns::OSGetArenaHi(ctx)) > boot_region_end {
                    let _ = fns::memset(
                        ctx,
                        ptr::<Addr<'a>>(ctx, boot_region_end as u32),
                        0_i32,
                        Handle::addr(fns::OSGetArenaHi(ctx)).wrapping_sub(boot_region_end),
                    );
                }
            }
        }
    }
}

pub fn OSInit<'a>(ctx: &'a Ctx) {
    // Transliterated from its machine code: hardware register order.
    ().put_regs(ctx);
    asm_OSInit(ctx);
}

fn asm_OSInit(ctx: &Ctx) {
    let g = &ctx.regs.gpr;
    let f = &ctx.regs.fpr;
    let lr0 = ctx.regs.lr.get();
    let _ = (g, f, lr0);
    let mut pc: u32 = 0x80342fc8_u32;
    loop {
        match pc {
            0x80342fc8_u32 => {
                // mflr r0
                g[0].set(ctx.regs.get_spr(8));
                // stw r0, 0x4(r1)
                {
                    let ea = g[1].get().wrapping_add(0x4_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // stwu r1, -0x10(r1)
                {
                    let ea = g[1].get().wrapping_add(0xfffffff0_u32);
                    ctx.stack_allocated(ea, g[1].get());
                    ctx.write_u32(ea, g[1].get());
                    g[1].set(ea);
                }
                // stw r31, 0xc(r1)
                {
                    let ea = g[1].get().wrapping_add(0xc_u32);
                    ctx.write_u32(ea, g[31].get());
                }
                // stw r30, 0x8(r1)
                {
                    let ea = g[1].get().wrapping_add(0x8_u32);
                    ctx.write_u32(ea, g[30].get());
                }
                // lwz r0, AreWeInitialized@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbca4_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // lis r3, "@73"@ha
                g[3].set(0x80400000_u32);
                // addi r31, r3, "@73"@l
                g[31].set(g[3].get().wrapping_add(0x1618_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_803432F4
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803432f4_u32;
                    continue;
                }
                pc = 0x80342ff0_u32;
            }
            0x80342ff0_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // stw r0, AreWeInitialized@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbca4_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // bl __OSGetSystemTime
                c::call(ctx, 0x8034c410_u32, 0x80342ffc_u32);
                pc = 0x80342ffc_u32;
            }
            0x80342ffc_u32 => {
                // stw r4, __OSStartTime+0x4@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbcb4_u32);
                    ctx.write_u32(ea, g[4].get());
                }
                // stw r3, __OSStartTime@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbcb0_u32);
                    ctx.write_u32(ea, g[3].get());
                }
                // bl OSDisableInterrupts
                c::call(ctx, 0x80347364_u32, 0x80343008_u32);
                pc = 0x80343008_u32;
            }
            0x80343008_u32 => {
                // li r0, 0x0
                g[0].set(0_u32);
                // lis r4, 0x8000
                g[4].set(0x80000000_u32);
                // stw r0, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // stw r4, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    ctx.write_u32(ea, g[4].get());
                }
                // stw r0, __DVDLongFileNameFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbbec_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // lwz r3, 0xf4(r4)
                {
                    let ea = g[4].get().wrapping_add(0xf4_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343058
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343058_u32;
                    continue;
                }
                pc = 0x80343028_u32;
            }
            0x80343028_u32 => {
                // addi r0, r3, 0xc
                g[0].set(g[3].get().wrapping_add(0xc_u32));
                // stw r0, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // lwz r0, 0x24(r3)
                {
                    let ea = g[3].get().wrapping_add(0x24_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // lwz r3, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // stw r0, __PADSpec@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbd78_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // lwz r0, 0x0(r3)
                {
                    let ea = g[3].get();
                    g[0].set(ctx.read_u32(ea));
                }
                // clrlwi r0, r0, 24
                {
                    let v = g[0].get().rotate_left(0) & 0xff_u32;
                    g[0].set(v);
                }
                // stb r0, 0x30e8(r4)
                {
                    let ea = g[4].get().wrapping_add(0x30e8_u32);
                    ctx.write_u8(ea, g[0].get() as u8);
                }
                // lwz r0, __PADSpec@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbd78_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // clrlwi r0, r0, 24
                {
                    let v = g[0].get().rotate_left(0) & 0xff_u32;
                    g[0].set(v);
                }
                // stb r0, 0x30e9(r4)
                {
                    let ea = g[4].get().wrapping_add(0x30e9_u32);
                    ctx.write_u8(ea, g[0].get() as u8);
                }
                // b .L_8034307C
                pc = 0x8034307c_u32;
                continue;
                pc = 0x80343058_u32;
            }
            0x80343058_u32 => {
                // lwz r0, 0x34(r4)
                {
                    let ea = g[4].get().wrapping_add(0x34_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_8034307C
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x8034307c_u32;
                    continue;
                }
                pc = 0x80343064_u32;
            }
            0x80343064_u32 => {
                // lbz r3, 0x30e8(r4)
                {
                    let ea = g[4].get().wrapping_add(0x30e8_u32);
                    g[3].set(u32::from(ctx.read_u8(ea)));
                }
                // li r0, BI2DebugFlagHolder@sda21
                g[0].set(g[13].get().wrapping_add(0xffffbca0_u32));
                // stw r3, BI2DebugFlagHolder@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbca0_u32);
                    ctx.write_u32(ea, g[3].get());
                }
                // stw r0, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // lbz r0, 0x30e9(r4)
                {
                    let ea = g[4].get().wrapping_add(0x30e9_u32);
                    g[0].set(u32::from(ctx.read_u8(ea)));
                }
                // stw r0, __PADSpec@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbd78_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                pc = 0x8034307c_u32;
            }
            0x8034307c_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // lwz r3, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // stw r0, __DVDLongFileNameFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbbec_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // lwz r3, 0x30(r3)
                {
                    let ea = g[3].get().wrapping_add(0x30_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_803430A0
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803430a0_u32;
                    continue;
                }
                pc = 0x80343094_u32;
            }
            0x80343094_u32 => {
                // lis r3, __ArenaLo@ha
                g[3].set(0x804f0000_u32);
                // addi r3, r3, __ArenaLo@l
                g[3].set(g[3].get().wrapping_add(0xc00_u32));
                // b .L_803430A0
                pc = 0x803430a0_u32;
                continue;
                pc = 0x803430a0_u32;
            }
            0x803430a0_u32 => {
                // bl OSSetArenaLo
                c::call(ctx, 0x803444e0_u32, 0x803430a4_u32);
                pc = 0x803430a4_u32;
            }
            0x803430a4_u32 => {
                // lwz r3, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // lwz r0, 0x30(r3)
                {
                    let ea = g[3].get().wrapping_add(0x30_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_803430E0
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803430e0_u32;
                    continue;
                }
                pc = 0x803430b4_u32;
            }
            0x803430b4_u32 => {
                // lwz r3, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_803430E0
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x803430e0_u32;
                    continue;
                }
                pc = 0x803430c0_u32;
            }
            0x803430c0_u32 => {
                // lwz r0, 0x0(r3)
                {
                    let ea = g[3].get();
                    g[0].set(ctx.read_u32(ea));
                }
                // cmplwi r0, 0x2
                {
                    let (x, y) = (g[0].get(), 0x2_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bge .L_803430E0
                if (c::cr_bit(ctx, 0) == false) {
                    pc = 0x803430e0_u32;
                    continue;
                }
                pc = 0x803430cc_u32;
            }
            0x803430cc_u32 => {
                // lis r3, _stack_addr@ha
                g[3].set(0x804f0000_u32);
                // addi r3, r3, _stack_addr@l
                g[3].set(g[3].get().wrapping_add(0xffffec00_u32));
                // addi r0, r3, 0x1f
                g[0].set(g[3].get().wrapping_add(0x1f_u32));
                // clrrwi r3, r0, 5
                {
                    let v = g[0].get().rotate_left(0) & 0xffffffe0_u32;
                    g[3].set(v);
                }
                // bl OSSetArenaLo
                c::call(ctx, 0x803444e0_u32, 0x803430e0_u32);
                pc = 0x803430e0_u32;
            }
            0x803430e0_u32 => {
                // lwz r3, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // lwz r3, 0x34(r3)
                {
                    let ea = g[3].get().wrapping_add(0x34_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_803430FC
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803430fc_u32;
                    continue;
                }
                pc = 0x803430f0_u32;
            }
            0x803430f0_u32 => {
                // lis r3, __ArenaHi@ha
                g[3].set(0x81700000_u32);
                // addi r3, r3, __ArenaHi@l
                g[3].set(g[3].get());
                // b .L_803430FC
                pc = 0x803430fc_u32;
                continue;
                pc = 0x803430fc_u32;
            }
            0x803430fc_u32 => {
                // bl OSSetArenaHi
                c::call(ctx, 0x803444d8_u32, 0x80343100_u32);
                pc = 0x80343100_u32;
            }
            0x80343100_u32 => {
                // bl OSExceptionInit
                c::call(ctx, 0x8034330c_u32, 0x80343104_u32);
                pc = 0x80343104_u32;
            }
            0x80343104_u32 => {
                // bl __OSInitSystemCall
                c::call(ctx, 0x8034aba0_u32, 0x80343108_u32);
                pc = 0x80343108_u32;
            }
            0x80343108_u32 => {
                // bl OSInitAlarm
                c::call(ctx, 0x80343720_u32, 0x8034310c_u32);
                pc = 0x8034310c_u32;
            }
            0x8034310c_u32 => {
                // bl __OSModuleInit
                c::call(ctx, 0x80347bcc_u32, 0x80343110_u32);
                pc = 0x80343110_u32;
            }
            0x80343110_u32 => {
                // bl __OSInterruptInit
                c::call(ctx, 0x803473e0_u32, 0x80343114_u32);
                pc = 0x80343114_u32;
            }
            0x80343114_u32 => {
                // lis r3, __OSResetSWInterruptHandler@ha
                g[3].set(0x80350000_u32);
                // addi r4, r3, __OSResetSWInterruptHandler@l
                g[4].set(g[3].get().wrapping_add(0xffff86e4_u32));
                // li r3, 0x16
                g[3].set(0x16_u32);
                // bl __OSSetInterruptHandler
                c::call(ctx, 0x803473b0_u32, 0x80343124_u32);
                pc = 0x80343124_u32;
            }
            0x80343124_u32 => {
                // bl __OSContextInit
                c::call(ctx, 0x80345660_u32, 0x80343128_u32);
                pc = 0x80343128_u32;
            }
            0x80343128_u32 => {
                // bl __OSCacheInit
                c::call(ctx, 0x80344d3c_u32, 0x8034312c_u32);
                pc = 0x8034312c_u32;
            }
            0x8034312c_u32 => {
                // bl EXIInit
                c::call(ctx, 0x80346c6c_u32, 0x80343130_u32);
                pc = 0x80343130_u32;
            }
            0x80343130_u32 => {
                // bl SIInit
                c::call(ctx, 0x80349db0_u32, 0x80343134_u32);
                pc = 0x80343134_u32;
            }
            0x80343134_u32 => {
                // bl __OSInitSram
                c::call(ctx, 0x80348c08_u32, 0x80343138_u32);
                pc = 0x80343138_u32;
            }
            0x80343138_u32 => {
                // bl __OSThreadInit
                c::call(ctx, 0x8034ac04_u32, 0x8034313c_u32);
                pc = 0x8034313c_u32;
            }
            0x8034313c_u32 => {
                // bl __OSInitAudioSystem
                c::call(ctx, 0x80344534_u32, 0x80343140_u32);
                pc = 0x80343140_u32;
            }
            0x80343140_u32 => {
                // bl PPCMfhid2
                c::call(ctx, 0x80335ea8_u32, 0x80343144_u32);
                pc = 0x80343144_u32;
            }
            0x80343144_u32 => {
                // rlwinm r3, r3, 0, 2, 0
                {
                    let v = g[3].get().rotate_left(0) & 0xbfffffff_u32;
                    g[3].set(v);
                }
                // bl PPCMthid2
                c::call(ctx, 0x80335eb0_u32, 0x8034314c_u32);
                pc = 0x8034314c_u32;
            }
            0x8034314c_u32 => {
                // lwz r3, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // addi r4, r3, 0x2c
                g[4].set(g[3].get().wrapping_add(0x2c_u32));
                // lwz r0, 0x0(r4)
                {
                    let ea = g[4].get();
                    g[0].set(ctx.read_u32(ea));
                }
                // rlwinm r0, r0, 0, 3, 3
                {
                    let v = g[0].get().rotate_left(0) & 0x10000000_u32;
                    g[0].set(v);
                }
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343174
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343174_u32;
                    continue;
                }
                pc = 0x80343164_u32;
            }
            0x80343164_u32 => {
                // lis r3, 0x1000
                g[3].set(0x10000000_u32);
                // addi r0, r3, 0x4
                g[0].set(g[3].get().wrapping_add(0x4_u32));
                // stw r0, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[0].get());
                }
                // b .L_8034317C
                pc = 0x8034317c_u32;
                continue;
                pc = 0x80343174_u32;
            }
            0x80343174_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // stw r0, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[0].get());
                }
                pc = 0x8034317c_u32;
            }
            0x8034317c_u32 => {
                // lis r3, 0xcc00
                g[3].set(0xcc000000_u32);
                // lwz r4, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[4].set(ctx.read_u32(ea));
                }
                // addi r3, r3, 0x3000
                g[3].set(g[3].get().wrapping_add(0x3000_u32));
                // lwz r0, 0x2c(r3)
                {
                    let ea = g[3].get().wrapping_add(0x2c_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // lwz r3, 0x2c(r4)
                {
                    let ea = g[4].get().wrapping_add(0x2c_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // clrrwi r0, r0, 28
                {
                    let v = g[0].get().rotate_left(0) & 0xf0000000_u32;
                    g[0].set(v);
                }
                // srwi r0, r0, 28
                {
                    let v = g[0].get().rotate_left(4) & 0xf_u32;
                    g[0].set(v);
                }
                // add r0, r3, r0
                {
                    let (v, ca, ov) = c::add3(g[3].get(), g[0].get(), 0);
                    g[0].set(v);
                    let _ = (ca, ov);
                }
                // stw r0, 0x2c(r4)
                {
                    let ea = g[4].get().wrapping_add(0x2c_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // bl __OSInitMemoryProtection
                c::call(ctx, 0x80347dbc_u32, 0x803431a4_u32);
                pc = 0x803431a4_u32;
            }
            0x803431a4_u32 => {
                // mr r3, r31
                {
                    let v = g[31].get() | g[31].get();
                    g[3].set(v);
                }
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x803431b0_u32);
                pc = 0x803431b0_u32;
            }
            0x803431b0_u32 => {
                // addi r3, r31, 0x20
                g[3].set(g[31].get().wrapping_add(0x20_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // addi r4, r31, 0x38
                g[4].set(g[31].get().wrapping_add(0x38_u32));
                // addi r5, r31, 0x44
                g[5].set(g[31].get().wrapping_add(0x44_u32));
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x803431c4_u32);
                pc = 0x803431c4_u32;
            }
            0x803431c4_u32 => {
                // addi r3, r31, 0x50
                g[3].set(g[31].get().wrapping_add(0x50_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x803431d0_u32);
                pc = 0x803431d0_u32;
            }
            0x803431d0_u32 => {
                // lwz r3, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_803431E8
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x803431e8_u32;
                    continue;
                }
                pc = 0x803431dc_u32;
            }
            0x803431dc_u32 => {
                // lwz r4, 0x2c(r3)
                {
                    let ea = g[3].get().wrapping_add(0x2c_u32);
                    g[4].set(ctx.read_u32(ea));
                }
                // cmplwi r4, 0x0
                {
                    let (x, y) = (g[4].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_803431F4
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803431f4_u32;
                    continue;
                }
                pc = 0x803431e8_u32;
            }
            0x803431e8_u32 => {
                // lis r3, 0x1000
                g[3].set(0x10000000_u32);
                // addi r4, r3, 0x2
                g[4].set(g[3].get().wrapping_add(0x2_u32));
                // b .L_803431F4
                pc = 0x803431f4_u32;
                continue;
                pc = 0x803431f4_u32;
            }
            0x803431f4_u32 => {
                // rlwinm r0, r4, 0, 3, 3
                {
                    let v = g[4].get().rotate_left(0) & 0x10000000_u32;
                    g[0].set(v);
                }
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bne .L_80343210
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x80343210_u32;
                    continue;
                }
                pc = 0x80343200_u32;
            }
            0x80343200_u32 => {
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // addi r3, r31, 0x60
                g[3].set(g[31].get().wrapping_add(0x60_u32));
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x8034320c_u32);
                pc = 0x8034320c_u32;
            }
            0x8034320c_u32 => {
                // b .L_80343298
                pc = 0x80343298_u32;
                continue;
                pc = 0x80343210_u32;
            }
            0x80343210_u32 => {
                // lis r3, 0x1000
                g[3].set(0x10000000_u32);
                // addi r0, r3, 0x2
                g[0].set(g[3].get().wrapping_add(0x2_u32));
                // cmpw r4, r0
                {
                    let (x, y) = (g[4].get() as i32, g[0].get() as i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343264
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343264_u32;
                    continue;
                }
                pc = 0x80343220_u32;
            }
            0x80343220_u32 => {
                // bge .L_80343234
                if (c::cr_bit(ctx, 0) == false) {
                    pc = 0x80343234_u32;
                    continue;
                }
                pc = 0x80343224_u32;
            }
            0x80343224_u32 => {
                // cmpw r4, r3
                {
                    let (x, y) = (g[4].get() as i32, g[3].get() as i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343244
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343244_u32;
                    continue;
                }
                pc = 0x8034322c_u32;
            }
            0x8034322c_u32 => {
                // bge .L_80343254
                if (c::cr_bit(ctx, 0) == false) {
                    pc = 0x80343254_u32;
                    continue;
                }
                pc = 0x80343230_u32;
            }
            0x80343230_u32 => {
                // b .L_80343284
                pc = 0x80343284_u32;
                continue;
                pc = 0x80343234_u32;
            }
            0x80343234_u32 => {
                // addi r0, r3, 0x4
                g[0].set(g[3].get().wrapping_add(0x4_u32));
                // cmpw r4, r0
                {
                    let (x, y) = (g[4].get() as i32, g[0].get() as i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // bge .L_80343284
                if (c::cr_bit(ctx, 0) == false) {
                    pc = 0x80343284_u32;
                    continue;
                }
                pc = 0x80343240_u32;
            }
            0x80343240_u32 => {
                // b .L_80343274
                pc = 0x80343274_u32;
                continue;
                pc = 0x80343244_u32;
            }
            0x80343244_u32 => {
                // addi r3, r31, 0x6c
                g[3].set(g[31].get().wrapping_add(0x6c_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x80343250_u32);
                pc = 0x80343250_u32;
            }
            0x80343250_u32 => {
                // b .L_80343298
                pc = 0x80343298_u32;
                continue;
                pc = 0x80343254_u32;
            }
            0x80343254_u32 => {
                // addi r3, r31, 0x7c
                g[3].set(g[31].get().wrapping_add(0x7c_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x80343260_u32);
                pc = 0x80343260_u32;
            }
            0x80343260_u32 => {
                // b .L_80343298
                pc = 0x80343298_u32;
                continue;
                pc = 0x80343264_u32;
            }
            0x80343264_u32 => {
                // addi r3, r31, 0x8c
                g[3].set(g[31].get().wrapping_add(0x8c_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x80343270_u32);
                pc = 0x80343270_u32;
            }
            0x80343270_u32 => {
                // b .L_80343298
                pc = 0x80343298_u32;
                continue;
                pc = 0x80343274_u32;
            }
            0x80343274_u32 => {
                // addi r3, r31, 0x9c
                g[3].set(g[31].get().wrapping_add(0x9c_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x80343280_u32);
                pc = 0x80343280_u32;
            }
            0x80343280_u32 => {
                // b .L_80343298
                pc = 0x80343298_u32;
                continue;
                pc = 0x80343284_u32;
            }
            0x80343284_u32 => {
                // subis r4, r4, 0x1000
                g[4].set(g[4].get().wrapping_add(0xf0000000_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // addi r3, r31, 0xac
                g[3].set(g[31].get().wrapping_add(0xac_u32));
                // subi r4, r4, 0x3
                g[4].set(g[4].get().wrapping_add(0xfffffffd_u32));
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x80343298_u32);
                pc = 0x80343298_u32;
            }
            0x80343298_u32 => {
                // lwz r4, BootInfo@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc98_u32);
                    g[4].set(ctx.read_u32(ea));
                }
                // addi r3, r31, 0xc0
                g[3].set(g[31].get().wrapping_add(0xc0_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // lwz r0, 0x28(r4)
                {
                    let ea = g[4].get().wrapping_add(0x28_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // srwi r4, r0, 20
                {
                    let v = g[0].get().rotate_left(12) & 0xfff_u32;
                    g[4].set(v);
                }
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x803432b0_u32);
                pc = 0x803432b0_u32;
            }
            0x803432b0_u32 => {
                // bl OSGetArenaHi
                c::call(ctx, 0x803444c8_u32, 0x803432b4_u32);
                pc = 0x803432b4_u32;
            }
            0x803432b4_u32 => {
                // mr r30, r3
                {
                    let v = g[3].get() | g[3].get();
                    g[30].set(v);
                }
                // bl OSGetArenaLo
                c::call(ctx, 0x803444d0_u32, 0x803432bc_u32);
                pc = 0x803432bc_u32;
            }
            0x803432bc_u32 => {
                // mr r4, r3
                {
                    let v = g[3].get() | g[3].get();
                    g[4].set(v);
                }
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // mr r5, r30
                {
                    let v = g[30].get() | g[30].get();
                    g[5].set(v);
                }
                // addi r3, r31, 0xd0
                g[3].set(g[31].get().wrapping_add(0xd0_u32));
                // bl OSReport
                c::call(ctx, 0x803456a8_u32, 0x803432d0_u32);
                pc = 0x803432d0_u32;
            }
            0x803432d0_u32 => {
                // lwz r3, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_803432EC
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x803432ec_u32;
                    continue;
                }
                pc = 0x803432dc_u32;
            }
            0x803432dc_u32 => {
                // lwz r0, 0x0(r3)
                {
                    let ea = g[3].get();
                    g[0].set(ctx.read_u32(ea));
                }
                // cmplwi r0, 0x2
                {
                    let (x, y) = (g[0].get(), 0x2_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // blt .L_803432EC
                if (c::cr_bit(ctx, 0) == true) {
                    pc = 0x803432ec_u32;
                    continue;
                }
                pc = 0x803432e8_u32;
            }
            0x803432e8_u32 => {
                // bl EnableMetroTRKInterrupts
                c::call(ctx, 0x8032a6bc_u32, 0x803432ec_u32);
                pc = 0x803432ec_u32;
            }
            0x803432ec_u32 => {
                // bl ClearArena
                c::call(ctx, 0x80342ebc_u32, 0x803432f0_u32);
                pc = 0x803432f0_u32;
            }
            0x803432f0_u32 => {
                // bl OSEnableInterrupts
                c::call(ctx, 0x80347378_u32, 0x803432f4_u32);
                pc = 0x803432f4_u32;
            }
            0x803432f4_u32 => {
                // lwz r0, 0x14(r1)
                {
                    let ea = g[1].get().wrapping_add(0x14_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // lwz r31, 0xc(r1)
                {
                    let ea = g[1].get().wrapping_add(0xc_u32);
                    g[31].set(ctx.read_u32(ea));
                }
                // lwz r30, 0x8(r1)
                {
                    let ea = g[1].get().wrapping_add(0x8_u32);
                    g[30].set(ctx.read_u32(ea));
                }
                // mtlr r0
                ctx.regs.set_spr(8, g[0].get());
                // addi r1, r1, 0x10
                g[1].set(g[1].get().wrapping_add(0x10_u32));
                // blr
                let to = ctx.regs.lr.get() & !3;
                if to != lr0 & !3 {
                    c::tail_call(ctx, to);
                }
                return;
                panic!("ran off the end of OSInit");
            }
            _ => unreachable!("OSInit: no block at {pc:#010x}"),
        }
    }
}

pub fn OSExceptionInit<'a>(ctx: &'a Ctx) {
    // Transliterated from its machine code: label without a symbol.
    ().put_regs(ctx);
    asm_OSExceptionInit(ctx);
}

fn asm_OSExceptionInit(ctx: &Ctx) {
    let g = &ctx.regs.gpr;
    let f = &ctx.regs.fpr;
    let lr0 = ctx.regs.lr.get();
    let _ = (g, f, lr0);
    let mut pc: u32 = 0x8034330c_u32;
    loop {
        match pc {
            0x8034330c_u32 => {
                // mflr r0
                g[0].set(ctx.regs.get_spr(8));
                // stw r0, 0x4(r1)
                {
                    let ea = g[1].get().wrapping_add(0x4_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // stwu r1, -0x38(r1)
                {
                    let ea = g[1].get().wrapping_add(0xffffffc8_u32);
                    ctx.stack_allocated(ea, g[1].get());
                    ctx.write_u32(ea, g[1].get());
                    g[1].set(ea);
                }
                // stmw r20, 0x8(r1)
                {
                    let ea = g[1].get().wrapping_add(0x8_u32);
                    for (i, reg) in (20..32).enumerate() {
                        ctx.write_u32(ea.wrapping_add(4 * i as u32), g[reg].get());
                    }
                }
                // lis r3, 0x8000
                g[3].set(0x80000000_u32);
                // lwz r0, 0x60(r3)
                {
                    let ea = g[3].get().wrapping_add(0x60_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // lis r4, __OSEVSetNumber@ha
                g[4].set(0x80340000_u32);
                // addi r30, r4, __OSEVSetNumber@l
                g[30].set(g[4].get().wrapping_add(0x364c_u32));
                // lis r5, __OSEVStart@ha
                g[5].set(0x80340000_u32);
                // lwz r25, 0x0(r30)
                {
                    let ea = g[30].get();
                    g[25].set(ctx.read_u32(ea));
                }
                // lis r4, __OSEVEnd@ha
                g[4].set(0x80340000_u32);
                // addi r5, r5, __OSEVStart@l
                g[5].set(g[5].get().wrapping_add(0x35e4_u32));
                // addi r4, r4, __OSEVEnd@l
                g[4].set(g[4].get().wrapping_add(0x367c_u32));
                // lis r6, "@73"@ha
                g[6].set(0x80400000_u32);
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // mr r24, r5
                {
                    let v = g[5].get() | g[5].get();
                    g[24].set(v);
                }
                // addi r29, r6, "@73"@l
                g[29].set(g[6].get().wrapping_add(0x1618_u32));
                // subf r23, r5, r4
                {
                    let (v, ca, ov) = c::add3(!g[5].get(), g[4].get(), 1);
                    g[23].set(v);
                    let _ = (ca, ov);
                }
                // addi r20, r3, 0x60
                g[20].set(g[3].get().wrapping_add(0x60_u32));
                // bne .L_803433A4
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x803433a4_u32;
                    continue;
                }
                pc = 0x8034335c_u32;
            }
            0x8034335c_u32 => {
                // addi r3, r29, 0x124
                g[3].set(g[29].get().wrapping_add(0x124_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl DBPrintf
                c::call(ctx, 0x80335f78_u32, 0x80343368_u32);
                pc = 0x80343368_u32;
            }
            0x80343368_u32 => {
                // lis r4, __OSDBINTSTART@ha
                g[4].set(0x80340000_u32);
                // lis r3, __OSDBINTEND@ha
                g[3].set(0x80340000_u32);
                // addi r0, r3, __OSDBINTEND@l
                g[0].set(g[3].get().wrapping_add(0x35b0_u32));
                // addi r4, r4, __OSDBINTSTART@l
                g[4].set(g[4].get().wrapping_add(0x358c_u32));
                // subf r21, r4, r0
                {
                    let (v, ca, ov) = c::add3(!g[4].get(), g[0].get(), 1);
                    g[21].set(v);
                    let _ = (ca, ov);
                }
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r5, r21
                {
                    let v = g[21].get() | g[21].get();
                    g[5].set(v);
                }
                // bl memcpy
                c::call(ctx, 0x800031f4_u32, 0x80343388_u32);
                pc = 0x80343388_u32;
            }
            0x80343388_u32 => {
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r4, r21
                {
                    let v = g[21].get() | g[21].get();
                    g[4].set(v);
                }
                // bl DCFlushRangeNoSync
                c::call(ctx, 0x80344874_u32, 0x80343394_u32);
                pc = 0x80343394_u32;
            }
            0x80343394_u32 => {
                // sync
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r4, r21
                {
                    let v = g[21].get() | g[21].get();
                    g[4].set(v);
                }
                // bl ICInvalidateRange
                c::call(ctx, 0x803448d4_u32, 0x803433a4_u32);
                pc = 0x803433a4_u32;
            }
            0x803433a4_u32 => {
                // lis r4, __OSDBINTEND@ha
                g[4].set(0x80340000_u32);
                // lis r3, __OSDBJUMPEND@ha
                g[3].set(0x80340000_u32);
                // addi r31, r4, __OSDBINTEND@l
                g[31].set(g[4].get().wrapping_add(0x35b0_u32));
                // addi r0, r3, __OSDBJUMPEND@l
                g[0].set(g[3].get().wrapping_add(0x35b4_u32));
                // addi r28, r29, 0xe8
                g[28].set(g[29].get().wrapping_add(0xe8_u32));
                // subf r27, r31, r0
                {
                    let (v, ca, ov) = c::add3(!g[31].get(), g[0].get(), 1);
                    g[27].set(v);
                    let _ = (ca, ov);
                }
                // li r26, 0x0
                g[26].set(0_u32);
                // b .L_803433C4
                pc = 0x803433c4_u32;
                continue;
                pc = 0x803433c4_u32;
            }
            0x803433c4_u32 => {
                // lis r3, __DBVECTOR@ha
                g[3].set(0x80340000_u32);
                // addi r21, r3, __DBVECTOR@l
                g[21].set(g[3].get().wrapping_add(0x363c_u32));
                // lis r22, 0x6000
                g[22].set(0x60000000_u32);
                // b .L_803433D4
                pc = 0x803433d4_u32;
                continue;
                pc = 0x803433d4_u32;
            }
            0x803433d4_u32 => {
                // b .L_8034351C
                pc = 0x8034351c_u32;
                continue;
                pc = 0x803433d8_u32;
            }
            0x803433d8_u32 => {
                // lwz r3, BI2DebugFlag@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbc9c_u32);
                    g[3].set(ctx.read_u32(ea));
                }
                // cmplwi r3, 0x0
                {
                    let (x, y) = (g[3].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343414
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343414_u32;
                    continue;
                }
                pc = 0x803433e4_u32;
            }
            0x803433e4_u32 => {
                // lwz r0, 0x0(r3)
                {
                    let ea = g[3].get();
                    g[0].set(ctx.read_u32(ea));
                }
                // cmplwi r0, 0x2
                {
                    let (x, y) = (g[0].get(), 0x2_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // blt .L_80343414
                if (c::cr_bit(ctx, 0) == true) {
                    pc = 0x80343414_u32;
                    continue;
                }
                pc = 0x803433f0_u32;
            }
            0x803433f0_u32 => {
                // mr r3, r26
                {
                    let v = g[26].get() | g[26].get();
                    g[3].set(v);
                }
                // bl __DBIsExceptionMarked
                c::call(ctx, 0x80335f5c_u32, 0x803433f8_u32);
                pc = 0x803433f8_u32;
            }
            0x803433f8_u32 => {
                // cmpwi r3, 0x0
                {
                    let (x, y) = (g[3].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343414
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343414_u32;
                    continue;
                }
                pc = 0x80343400_u32;
            }
            0x80343400_u32 => {
                // addi r3, r29, 0x140
                g[3].set(g[29].get().wrapping_add(0x140_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // clrlwi r4, r26, 24
                {
                    let v = g[26].get().rotate_left(0) & 0xff_u32;
                    g[4].set(v);
                }
                // bl DBPrintf
                c::call(ctx, 0x80335f78_u32, 0x80343410_u32);
                pc = 0x80343410_u32;
            }
            0x80343410_u32 => {
                // b .L_80343514
                pc = 0x80343514_u32;
                continue;
                pc = 0x80343414_u32;
            }
            0x80343414_u32 => {
                // clrlwi r20, r26, 24
                {
                    let v = g[26].get().rotate_left(0) & 0xff_u32;
                    g[20].set(v);
                }
                // or r0, r25, r20
                {
                    let v = g[25].get() | g[20].get();
                    g[0].set(v);
                }
                // stw r0, 0x0(r30)
                {
                    let ea = g[30].get();
                    ctx.write_u32(ea, g[0].get());
                }
                // mr r3, r26
                {
                    let v = g[26].get() | g[26].get();
                    g[3].set(v);
                }
                // bl __DBIsExceptionMarked
                c::call(ctx, 0x80335f5c_u32, 0x80343428_u32);
                pc = 0x80343428_u32;
            }
            0x80343428_u32 => {
                // cmpwi r3, 0x0
                {
                    let (x, y) = (g[3].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80343454
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80343454_u32;
                    continue;
                }
                pc = 0x80343430_u32;
            }
            0x80343430_u32 => {
                // mr r4, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[4].set(v);
                }
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // addi r3, r29, 0x170
                g[3].set(g[29].get().wrapping_add(0x170_u32));
                // bl DBPrintf
                c::call(ctx, 0x80335f78_u32, 0x80343440_u32);
                pc = 0x80343440_u32;
            }
            0x80343440_u32 => {
                // mr r3, r21
                {
                    let v = g[21].get() | g[21].get();
                    g[3].set(v);
                }
                // mr r4, r31
                {
                    let v = g[31].get() | g[31].get();
                    g[4].set(v);
                }
                // mr r5, r27
                {
                    let v = g[27].get() | g[27].get();
                    g[5].set(v);
                }
                // bl memcpy
                c::call(ctx, 0x800031f4_u32, 0x80343450_u32);
                pc = 0x80343450_u32;
            }
            0x80343450_u32 => {
                // b .L_803434E0
                pc = 0x803434e0_u32;
                continue;
                pc = 0x80343454_u32;
            }
            0x80343454_u32 => {
                // mr r4, r21
                {
                    let v = g[21].get() | g[21].get();
                    g[4].set(v);
                }
                // b .L_8034345C
                pc = 0x8034345c_u32;
                continue;
                pc = 0x8034345c_u32;
            }
            0x8034345c_u32 => {
                // cmplwi r27, 0x0
                {
                    let (x, y) = (g[27].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // addi r3, r27, 0x3
                g[3].set(g[27].get().wrapping_add(0x3_u32));
                // srwi r3, r3, 2
                {
                    let v = g[3].get().rotate_left(30) & 0x3fffffff_u32;
                    g[3].set(v);
                }
                // ble .L_803434E0
                if (c::cr_bit(ctx, 1) == false) {
                    pc = 0x803434e0_u32;
                    continue;
                }
                pc = 0x8034346c_u32;
            }
            0x8034346c_u32 => {
                // srwi r0, r3, 3
                {
                    let v = g[3].get().rotate_left(29) & 0x1fffffff_u32;
                    g[0].set(v);
                }
                // cmplwi r0, 0x0
                {
                    let (x, y) = (g[0].get(), 0x0_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // mtctr r0
                ctx.regs.set_spr(9, g[0].get());
                // beq .L_803434CC
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x803434cc_u32;
                    continue;
                }
                pc = 0x8034347c_u32;
            }
            0x8034347c_u32 => {
                // b .L_80343480
                pc = 0x80343480_u32;
                continue;
                pc = 0x80343480_u32;
            }
            0x80343480_u32 => {
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // bdnz .L_80343480
                if c::ctr_ok(ctx, 16) {
                    pc = 0x80343480_u32;
                    continue;
                }
                pc = 0x803434c4_u32;
            }
            0x803434c4_u32 => {
                // andi. r3, r3, 0x7
                {
                    let v = g[3].get() & 0x7_u32;
                    g[3].set(v);
                    c::update_cr0(ctx, v);
                }
                // beq .L_803434E0
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x803434e0_u32;
                    continue;
                }
                pc = 0x803434cc_u32;
            }
            0x803434cc_u32 => {
                // mtctr r3
                ctx.regs.set_spr(9, g[3].get());
                // b .L_803434D4
                pc = 0x803434d4_u32;
                continue;
                pc = 0x803434d4_u32;
            }
            0x803434d4_u32 => {
                // stw r22, 0x0(r4)
                {
                    let ea = g[4].get();
                    ctx.write_u32(ea, g[22].get());
                }
                // addi r4, r4, 0x4
                g[4].set(g[4].get().wrapping_add(0x4_u32));
                // bdnz .L_803434D4
                if c::ctr_ok(ctx, 16) {
                    pc = 0x803434d4_u32;
                    continue;
                }
                pc = 0x803434e0_u32;
            }
            0x803434e0_u32 => {
                // lwz r3, 0x0(r28)
                {
                    let ea = g[28].get();
                    g[3].set(ctx.read_u32(ea));
                }
                // mr r4, r24
                {
                    let v = g[24].get() | g[24].get();
                    g[4].set(v);
                }
                // mr r5, r23
                {
                    let v = g[23].get() | g[23].get();
                    g[5].set(v);
                }
                // addis r20, r3, 0x8000
                g[20].set(g[3].get().wrapping_add(0x80000000_u32));
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // bl memcpy
                c::call(ctx, 0x800031f4_u32, 0x803434f8_u32);
                pc = 0x803434f8_u32;
            }
            0x803434f8_u32 => {
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r4, r23
                {
                    let v = g[23].get() | g[23].get();
                    g[4].set(v);
                }
                // bl DCFlushRangeNoSync
                c::call(ctx, 0x80344874_u32, 0x80343504_u32);
                pc = 0x80343504_u32;
            }
            0x80343504_u32 => {
                // sync
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r4, r23
                {
                    let v = g[23].get() | g[23].get();
                    g[4].set(v);
                }
                // bl ICInvalidateRange
                c::call(ctx, 0x803448d4_u32, 0x80343514_u32);
                pc = 0x80343514_u32;
            }
            0x80343514_u32 => {
                // addi r28, r28, 0x4
                g[28].set(g[28].get().wrapping_add(0x4_u32));
                // addi r26, r26, 0x1
                g[26].set(g[26].get().wrapping_add(0x1_u32));
                pc = 0x8034351c_u32;
            }
            0x8034351c_u32 => {
                // clrlwi r0, r26, 24
                {
                    let v = g[26].get().rotate_left(0) & 0xff_u32;
                    g[0].set(v);
                }
                // cmplwi r0, 0xf
                {
                    let (x, y) = (g[0].get(), 0xf_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // blt .L_803433D8
                if (c::cr_bit(ctx, 0) == true) {
                    pc = 0x803433d8_u32;
                    continue;
                }
                pc = 0x80343528_u32;
            }
            0x80343528_u32 => {
                // lis r3, 0x8000
                g[3].set(0x80000000_u32);
                // addi r0, r3, 0x3000
                g[0].set(g[3].get().wrapping_add(0x3000_u32));
                // stw r0, OSExceptionTable@sda21(r0)
                {
                    let ea = g[13].get().wrapping_add(0xffffbca8_u32);
                    ctx.write_u32(ea, g[0].get());
                }
                // li r20, 0x0
                g[20].set(0_u32);
                // b .L_8034353C
                pc = 0x8034353c_u32;
                continue;
                pc = 0x8034353c_u32;
            }
            0x8034353c_u32 => {
                // lis r3, OSDefaultExceptionHandler@ha
                g[3].set(0x80340000_u32);
                // addi r23, r3, OSDefaultExceptionHandler@l
                g[23].set(g[3].get().wrapping_add(0x3680_u32));
                // b .L_80343548
                pc = 0x80343548_u32;
                continue;
                pc = 0x80343548_u32;
            }
            0x80343548_u32 => {
                // b .L_8034355C
                pc = 0x8034355c_u32;
                continue;
                pc = 0x8034354c_u32;
            }
            0x8034354c_u32 => {
                // mr r3, r20
                {
                    let v = g[20].get() | g[20].get();
                    g[3].set(v);
                }
                // mr r4, r23
                {
                    let v = g[23].get() | g[23].get();
                    g[4].set(v);
                }
                // bl __OSSetExceptionHandler
                c::call(ctx, 0x803435b4_u32, 0x80343558_u32);
                pc = 0x80343558_u32;
            }
            0x80343558_u32 => {
                // addi r20, r20, 0x1
                g[20].set(g[20].get().wrapping_add(0x1_u32));
                pc = 0x8034355c_u32;
            }
            0x8034355c_u32 => {
                // clrlwi r0, r20, 24
                {
                    let v = g[20].get().rotate_left(0) & 0xff_u32;
                    g[0].set(v);
                }
                // cmplwi r0, 0xf
                {
                    let (x, y) = (g[0].get(), 0xf_u32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // blt .L_8034354C
                if (c::cr_bit(ctx, 0) == true) {
                    pc = 0x8034354c_u32;
                    continue;
                }
                pc = 0x80343568_u32;
            }
            0x80343568_u32 => {
                // stw r25, 0x0(r30)
                {
                    let ea = g[30].get();
                    ctx.write_u32(ea, g[25].get());
                }
                // addi r3, r29, 0x1a0
                g[3].set(g[29].get().wrapping_add(0x1a0_u32));
                // crclr cr1eq
                {
                    let (x, y) = (c::cr_bit(ctx, 6), c::cr_bit(ctx, 6));
                    c::set_cr_bit(ctx, 6, x ^ y);
                }
                // bl DBPrintf
                c::call(ctx, 0x80335f78_u32, 0x80343578_u32);
                pc = 0x80343578_u32;
            }
            0x80343578_u32 => {
                // lmw r20, 0x8(r1)
                {
                    let ea = g[1].get().wrapping_add(0x8_u32);
                    for (i, reg) in (20..32).enumerate() {
                        g[reg].set(ctx.read_u32(ea.wrapping_add(4 * i as u32)));
                    }
                }
                // lwz r0, 0x3c(r1)
                {
                    let ea = g[1].get().wrapping_add(0x3c_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r1, r1, 0x38
                g[1].set(g[1].get().wrapping_add(0x38_u32));
                // mtlr r0
                ctx.regs.set_spr(8, g[0].get());
                // blr
                let to = ctx.regs.lr.get() & !3;
                if to != lr0 & !3 {
                    c::tail_call(ctx, to);
                }
                return;
                panic!("ran off the end of OSExceptionInit");
            }
            _ => unreachable!("OSExceptionInit: no block at {pc:#010x}"),
        }
    }
}

pub fn __OSSetExceptionHandler<'a>(ctx: &'a Ctx, exception: u8, handler: FnPtr<'a>) -> FnPtr<'a> {
    let mut exception = exception;
    let mut handler = handler;
    let mut oldHandler: FnPtr<'a> = null(ctx);
    oldHandler = (Handle::add(
        statics::dolphin__os__OS::OSExceptionTable(ctx).get(),
        (exception as i32),
    ))
    .get();
    (Handle::add(
        statics::dolphin__os__OS::OSExceptionTable(ctx).get(),
        (exception as i32),
    ))
    .set(handler);
    return oldHandler;
}

pub fn __OSGetExceptionHandler<'a>(ctx: &'a Ctx, exception: u8) -> FnPtr<'a> {
    let mut exception = exception;
    return (Handle::add(
        statics::dolphin__os__OS::OSExceptionTable(ctx).get(),
        (exception as i32),
    ))
    .get();
}

pub fn __OSGetDIConfig<'a>(ctx: &'a Ctx) -> u32 {
    return ((Handle::add((ptr::<Val<'a, u32>>(ctx, 0xcc006000_u32 as u32)), 9_i32)).get()
        & (255_i32 as u32));
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x80343680,
        |ctx| {
            let (a0, a1): (u8, OSContext<'_>) = Args::take_all(ctx);
            Ret::put(manual::OSDefaultExceptionHandler(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80342e94,
        |ctx| {
            Ret::put(OSGetConsoleType(ctx), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80342ebc,
        |ctx| {
            Ret::put(ClearArena(ctx), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(0x80342fc8, asm_OSInit, Returns::Nothing);
    ctx.register_port(0x8034330c, asm_OSExceptionInit, Returns::Nothing);
    ctx.register_port(
        0x803435b4,
        |ctx| {
            let (a0, a1): (u8, FnPtr<'_>) = Args::take_all(ctx);
            Ret::put(__OSSetExceptionHandler(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803435d0,
        |ctx| {
            let (a0,): (u8,) = Args::take_all(ctx);
            Ret::put(__OSGetExceptionHandler(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x803436d4,
        |ctx| {
            Ret::put(manual::__OSPSInit(ctx), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8034370c,
        |ctx| {
            Ret::put(__OSGetDIConfig(ctx), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(0x8034358c, manual::__OSDBIntegrator, Returns::Unknown);
    ctx.register_port(0x803435b0, manual::__OSDBJump, Returns::Unknown);
    ctx.register_port(0x803435e4, manual::OSExceptionVector, Returns::Unknown);
}
