// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from libs/dolphin/src/dolphin/os/OSSync.c. Do not edit; fix the translator or port by hand.
// unit: dolphin/os/OSSync
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::manual::dolphin__os__OSSync as manual;
use crate::support::*;

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x8034ab80,
        |ctx| {
            Ret::put(manual::SystemCallVector(ctx), ctx);
        },
        Returns::Nothing,
    );
}
