// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftKoopa/ftkoopaspeciallw.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftKoopa/ftkoopaspeciallw
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn fn_80134518<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !((fp).x2219_b0() != 0) {
        let _ = fns::efSync_Spawn(
            ctx,
            0x4d8_i32,
            gobj,
            &[VarArg::Int(Handle::addr((fp).cur_pos()))],
        );
        (fp).set_x2219_b0((1_i32 as u8));
    }
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
}

pub fn fn_80134590<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    if !((fp).x2219_b0() != 0) {
        let _ = fns::efSync_Spawn(
            ctx,
            0x4df_i32,
            gobj,
            &[VarArg::Int(Handle::addr(((fp).parts()).joint()))],
        );
        (fp).set_x2219_b0((1_i32 as u8));
    }
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
}

pub fn ftKp_SpecialLw_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    (fp).self_vel().set_x({
        let __t1 = 0.0;
        (fp).self_vel().set_y(__t1);
        __t1
    });
    fns::ftCommon_8007D5D4(ctx, fp);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        0x169_i32,
        0_u32,
        0.0,
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::ftAnim_8006EBA4(ctx, gobj);
    inl_ftKp_SpecialLw_Enter_inline_unfused(ctx, gobj);
}

pub fn ftKp_SpecialAirLw_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: _ftKoopaAttributes<'a> = Handle::cast::<_ftKoopaAttributes<'a>>((fp).dat_attrs());
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    (fp).self_vel()
        .set_x(fp::fmuls((fp).self_vel().x(), (da).x80()));
    (fp).self_vel()
        .set_y(fp::fmuls((fp).self_vel().y(), (da).x84()));
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        0x16a_i32,
        0_u32,
        0.0,
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::ftAnim_8006EBA4(ctx, gobj);
    inl_ftKp_SpecialLw_Enter_inline_unfused(ctx, gobj);
}

pub fn ftKp_SpecialLw_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftKp_SpecialLw_80134988(ctx, gobj);
    }
}

pub fn ftKp_SpecialAirLw_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        (fp).cmd_vars().at(1_i32).set((1_i32 as u32));
    }
}

pub fn ftKp_SpecialLw_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    fns::ft_80085134(ctx, gobj);
    if (fp).self_vel().y() < 0.0 {
        (fp).self_vel().set_y(0.0);
    }
}

pub fn ftKp_SpecialAirLw_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: _ftKoopaAttributes<'a> = Handle::cast::<_ftKoopaAttributes<'a>>((fp).dat_attrs());
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    fns::ftCommon_Fall(ctx, fp, (da).x8C(), (da).x90());
    fns::ftCommon_CalcSelfAccel_Deaccel(ctx, fp, (da).x88());
    if ((fp).self_vel().y() < (da).x94()) || ((fp).cmd_vars().at(1_i32).get() != (0_i32 as u32)) {
        (fp).self_vel().set_y((da).x94());
    }
    if (fp).cmd_vars().at(1_i32).get() != (0_i32 as u32) {
        (fp).self_vel().set_x(0.0);
        if !((fp).x2219_b0() != 0) {
            (fp).set_accessory4_cb(fnptr(ctx, 0x80134590));
        }
    }
}

pub fn ftKp_SpecialLw_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ftKp_SpecialAirLw_Coll(ctx, gobj);
}

pub fn ftKp_SpecialAirLw_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if (fns::ft_CheckGroundAndLedge(ctx, gobj, inl_ftGetFacingDirInt_unfused(ctx, fp)) != 0) {
        if ((fp).cmd_vars().at(0_i32).get() != (0_i32 as u32)) && ((fp).self_vel().y() <= 0.0) {
            fns::ftKp_SpecialLw_80134A5C(ctx, gobj);
        } else {
            fns::ftCommon_8007D5D4(ctx, fp);
            fns::ftCommon_UnlockECB(ctx, fp);
        }
    } else if ((fp).cmd_vars().at(0_i32).get() != (0_i32 as u32))
        && (fns::ftCliffCommon_80081298(ctx, gobj) != 0_i32)
    {
        fns::ftCliffCommon_80081370(ctx, gobj);
    }
}

pub fn ftKp_SpecialLw_80134988<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftKp_MS_SpecialAirLw as i32),
        (0xc4c5088_i32 as u32),
        30.0,
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
}

pub fn ftKp_SpecialLwLanding_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ft_8008A2BC(ctx, gobj);
    }
}

pub fn ftKp_SpecialLwLanding_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
}

pub fn ftKp_SpecialLwLanding_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if (fns::ft_80082708(ctx, gobj) as u32) == ((enums::GA_Ground as i32) as u32) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftKp_SpecialLw_80134A5C<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).set_gr_vel(0.0);
    fns::ftCommon_8007D7FC(ctx, fp);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        0x16b_i32,
        0_u32,
        0.0,
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
    (fp).set_accessory4_cb(fnptr(ctx, 0x80134518));
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_Fighter_SetEffectHitlagCallbacks_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) {
    let mut fp = fp;
    (fp).set_pre_hitlag_cb(fnptr(ctx, 0x8005ba40));
    (fp).set_post_hitlag_cb(fnptr(ctx, 0x8005bac4));
}

fn inl_ftKp_SpecialLw_Enter_inline_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).cmd_vars().at(1_i32).set((0_i32 as u32));
    (fp).cmd_vars().at(0_i32).set((0_i32 as u32));
    (fp).x2210().x0().set_throw_flags_b0((0_i32 as u8));
    (fp).x6A4_transNOffset().set_y(0.0);
    (fp).set_x2223_b4((1_i32 as u8));
}

fn inl_ftGetFacingDirInt_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) -> i32 {
    let mut fp = fp;
    if (fp).facing_dir() < 0.0 {
        return 1_i32.wrapping_neg();
    } else {
        return 1_i32;
    }
    #[allow(unreachable_code)]
    return 0;
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x80134518,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_80134518(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134590,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_80134590(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8013460c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x801346a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialAirLw_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8013474c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134788,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialAirLw_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x801347c4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134804,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialAirLw_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x801348a0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x801348c0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialAirLw_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134988,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_80134988(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x801349c4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLwLanding_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134a00,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLwLanding_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134a20,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLwLanding_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80134a5c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftKp_SpecialLw_80134A5C(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
