// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/it/kinds/ittomato.c. Do not edit; fix the translator or port by hand.
// unit: melee/it/kinds/ittomato
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn it_802841B4<'a>(
    ctx: &'a Ctx,
    parent_gobj: HSD_GObj<'a>,
    pos: Vec<'a>,
    arg2: i32,
) -> HSD_GObj<'a> {
    let __frame = ctx.stack_frame(0x70);
    let spawn: SpawnItem<'a> = frame_at(ctx, &__frame, 0x0);
    let mut parent_gobj = parent_gobj;
    let mut pos = pos;
    let mut arg2 = arg2;
    let mut gobj: HSD_GObj<'a> = null::<HSD_GObj<'a>>(ctx);
    if !Handle::is_null(parent_gobj) {
        spawn.set_kind((enums::It_Kind_Tomato as i32));
        inl_Item_InitSpawnPosition_unfused(ctx, spawn, pos, 1_i32);
        inl_Item_InitSpawnCommonFields_unfused(
            ctx,
            spawn,
            null::<HSD_GObj<'a>>(ctx),
            fp::fneg(1.0),
            1_i32,
        );
        gobj = fns::Item_80268B18(ctx, spawn);
    }
    if !Handle::is_null(gobj) {
        let mut ip: Item<'a> =
            (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
        (ip).xDD4_itemVar().tomato().set_x4_b0(1_i32);
        (ip).xDD4_itemVar().tomato().set_x8((arg2 as u32));
    }
    return gobj;
}

pub fn it_8028428C<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut sa: MaximTomatoSpecialAttr<'a> = Handle::cast::<MaximTomatoSpecialAttr<'a>>(
        ((ip).xC4_article_data()).x4_specialAttributes(),
    );
    (ip).xDD4_itemVar()
        .tomato()
        .set_heal_amount((sa).heal_amount_1());
}

pub fn itTomato_Logic9_Spawned<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut sa: MaximTomatoSpecialAttr<'a> = Handle::cast::<MaximTomatoSpecialAttr<'a>>(
        ((ip).xC4_article_data()).x4_specialAttributes(),
    );
    fns::it_8026B390(ctx, gobj);
    (ip).x40_vel().set_x(0.0);
    (ip).x40_vel().set_y((sa).x14());
    (ip).x40_vel().set_z(0.0);
    (ip).xDD4_itemVar()
        .tomato()
        .set_heal_amount((sa).heal_amount_0());
    (ip).xDD4_itemVar().tomato().set_x4_b0(0_i32);
    (ip).xDD4_itemVar().tomato().set_x8((0_i32 as u32));
    statics::melee__it__kinds__ittomato::it_80284358(ctx, gobj);
}

pub fn itTomato_Logic9_Destroyed<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut item: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((item).xDD4_itemVar().tomato().x4_b0() != 0) {
        fns::gm_80473A18(ctx)
            .x90()
            .at(((item).xDD4_itemVar().tomato().x8() as i32))
            .set((0_i32 as u8));
    }
}

pub fn it_80284358<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 0_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itTomato_UnkMotion0_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itTomato_UnkMotion0_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut attr: ItemAttr<'a> = null(ctx);
    let mut item: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    attr = (item).xCC_item_attr();
    fns::it_80272860(
        ctx,
        gobj,
        (attr).x10_fall_speed(),
        (attr).x14_fall_speed_max(),
    );
}

pub fn itTomato_UnkMotion0_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::it_8026E15C(ctx, gobj, fnptr(ctx, 0x802843e4));
    return 0_i32;
}

pub fn it_802843E4<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut item: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (item).x40_vel().set_z({
        let __t2 = {
            let __t1 = fp::frsp(0_i32 as f64);
            (item).x40_vel().set_x(__t1);
            __t1
        };
        (item).x40_vel().set_y(__t2);
        __t2
    });
    fns::Item_80268E5C(ctx, gobj, 1_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itTomato_UnkMotion1_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itTomato_UnkMotion1_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn itTomato_UnkMotion1_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::it_8026D62C(ctx, gobj, fnptr(ctx, 0x80284458));
    return 0_i32;
}

pub fn it_80284458<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 2_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itTomato_UnkMotion4_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itTomato_UnkMotion4_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut attr: ItemAttr<'a> = (ip).xCC_item_attr();
    fns::it_80272860(
        ctx,
        gobj,
        (attr).x10_fall_speed(),
        (attr).x14_fall_speed_max(),
    );
}

pub fn itTomato_UnkMotion4_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::it_8026E15C(ctx, gobj, fnptr(ctx, 0x802843e4));
    return 0_i32;
}

pub fn itTomato_Logic9_PickedUp<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut jobj: HSD_JObj<'a> =
        (Handle::cast::<HSD_JObj<'a>>(inl_HSD_GObjGetHSDObj_unfused(ctx, gobj)));
    let mut child: HSD_JObj<'a> = inl_HSD_JObjGetChild_unfused(ctx, jobj);
    fns::HSD_JObjClearFlagsAll(ctx, child, ((shl_i32(1_i32, (4_i32 as u32))) as u32));
    fns::Item_80268E5C(ctx, gobj, 3_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itTomato_UnkMotion3_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itTomato_UnkMotion3_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn itTomato_Logic9_Dropped<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut jobj: HSD_JObj<'a> =
        (Handle::cast::<HSD_JObj<'a>>(inl_HSD_GObjGetHSDObj_unfused(ctx, gobj)));
    let mut jobj2: HSD_JObj<'a> = inl_HSD_JObjGetChild_unfused(ctx, jobj);
    fns::it_8026B390(ctx, gobj);
    fns::HSD_JObjClearFlagsAll(ctx, jobj2, ((shl_i32(1_i32, (4_i32 as u32))) as u32));
    fns::Item_80268E5C(
        ctx,
        gobj,
        4_i32,
        ((enums::ITEM_ANIM_UPDATE as i32) | (enums::ITEM_DROP_UPDATE as i32)),
    );
}

pub fn itTomato_Logic9_EnteredAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 5_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itTomato_UnkMotion5_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itTomato_UnkMotion5_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn itTomato_UnkMotion5_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::it_8026E8C4(ctx, gobj, fnptr(ctx, 0x802843e4), fnptr(ctx, 0x80284458));
    return 0_i32;
}

pub fn itTomato_Logic9_EvtUnk<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, gobj_ref: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut gobj_ref = gobj_ref;
    let _ = fns::it_8026B894(ctx, gobj, gobj_ref);
}

fn inl_Item_InitSpawnPosition_unfused<'a>(
    ctx: &'a Ctx,
    spawn: SpawnItem<'a>,
    pos: Vec<'a>,
    on_plane: i32,
) {
    let mut spawn = spawn;
    let mut pos = pos;
    let mut on_plane = on_plane;
    Handle::copy_from((spawn).prev_pos(), (pos));
    if (on_plane != 0) {
        (spawn).prev_pos().set_z(0.0);
    }
    Handle::copy_from((spawn).pos(), (spawn).prev_pos());
}

fn inl_Item_InitSpawnCommonFields_unfused<'a>(
    ctx: &'a Ctx,
    spawn: SpawnItem<'a>,
    parent: HSD_GObj<'a>,
    facing_dir: f64,
    initial_collision: i32,
) {
    let mut spawn = spawn;
    let mut parent = parent;
    let mut facing_dir = facing_dir;
    let mut initial_collision = initial_collision;
    (spawn).set_facing_dir(facing_dir);
    (spawn).set_x3C_damage((0_i32 as i16));
    (spawn).vel().set_x({
        let __t2 = {
            let __t1 = 0.0;
            (spawn).vel().set_z(__t1);
            __t1
        };
        (spawn).vel().set_y(__t2);
        __t2
    });
    (spawn).set_x0_parent_gobj(parent);
    (spawn).set_x4_parent_gobj2((spawn).x0_parent_gobj());
    (spawn).x44_flag().x0().set_b0((initial_collision as u8));
    (spawn).set_x40(0_i32);
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_HSD_GObjGetHSDObj_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).hsd_obj();
}

fn inl_HSD_JObjGetChild_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>) -> HSD_JObj<'a> {
    let mut jobj = jobj;
    if Handle::is_null(jobj) {
        return null::<HSD_JObj<'a>>(ctx);
    } else {
        return (jobj).child();
    }
    #[allow(unreachable_code)]
    return null(ctx);
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x802841b4,
        |ctx| {
            let (a0, a1, a2): (HSD_GObj<'_>, Vec<'_>, i32) = Args::take_all(ctx);
            Ret::put(it_802841B4(ctx, a0, a1, a2), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028428c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028428C(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802842a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_Spawned(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284324,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_Destroyed(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284358,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80284358(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284380,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion0_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284388,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion0_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802843b8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion0_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x802843e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802843E4(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284420,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion1_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284428,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion1_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028442c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion1_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284458,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80284458(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284480,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion4_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284488,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion4_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802844b8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion4_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x802844e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_PickedUp(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80284540,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion3_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284548,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion3_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028454c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_Dropped(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802845bc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_EnteredAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802845e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion5_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x802845ec,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion5_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802845f0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itTomato_UnkMotion5_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80284624,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, HSD_GObj<'_>) = Args::take_all(ctx);
            Ret::put(itTomato_Logic9_EvtUnk(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
}
