// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftCaptain/ftcaptainspecials.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftCaptain/ftcaptainspecials
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn ftCa_SpecialS_RemoveGFX<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    fns::efLib_DestroyAll(ctx, gobj);
    (fp).u().ca().set_during_specials((0_i32 as u32));
    (fp).u().ca().set_during_specials_start((0_i32 as u32));
}

pub fn ftCa_SpecialS_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_resetCmdVarsGround_unfused(ctx, gobj);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftCa_MS_SpecialSStart as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_setCallbacks_unfused(ctx, gobj);
    fns::ftAnim_8006EBA4(ctx, gobj);
    's1: {
        let __case = match (fns::ftLib_GetKind(ctx, gobj) as u32) {
            2_u32 => 0,
            25_u32 => 1,
            _ => 2,
        };
        if __case <= 0 {
            {
                let _ = fns::efSync_Spawn(
                    ctx,
                    0x491_i32,
                    gobj,
                    &[VarArg::Int(Handle::addr(
                        (Handle::add((fp).parts(), (enums::FtPart_HeadN as i32))).joint(),
                    ))],
                );
                (fp).u().ca().set_during_specials_start((1_i32 as u32));
                break 's1;
            }
        }
        if __case <= 1 {
            let _ = fns::efSync_Spawn(
                ctx,
                0x50d_i32,
                gobj,
                &[VarArg::Int(Handle::addr(
                    (Handle::add((fp).parts(), (enums::FtPart_L2ndNb as i32))).joint(),
                ))],
            );
            (fp).u().ca().set_during_specials_start((1_i32 as u32));
            break 's1;
        }
        if __case <= 2 {
            break 's1;
        }
    }
    (fp).u().ca().set_during_specials((0_i32 as u32));
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_hurtbox_detect_cb(fnptr(ctx, 0x800e350c));
    inl_resetVel_unfused(ctx, fp);
    (fp).set_gr_vel(fp::frsp(0_i32 as f64));
}

pub fn ftCa_SpecialAirS_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_setupAirStart_unfused(ctx, gobj);
    (fp).mv().ca().specials().set_grav(fp::frsp(0_i32 as f64));
    fns::ftCommon_8007D60C(ctx, fp);
}

pub fn ftCa_SpecialS_OnDetect<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x78);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if (fp).cmd_vars().at(0_i32).get() != (0_i32 as u32) {
        let mut detected_gobj: HSD_GObj<'a> = (fp).unk_gobj();
        if (((fp).unk_gobj()).classifier() as i32) == 4_i32 {
            's1: {
                let __case = match (fp).motion_id() {
                    0x15d_i32 => 0,
                    0x15f_i32 => 1,
                    _ => 2,
                };
                if __case <= 0 {
                    {
                        inl_onDetectGround_unfused(ctx, gobj);
                        break 's1;
                    }
                }
                if __case <= 1 {
                    {
                        inl_onDetectAir_unfused(ctx, gobj);
                        break 's1;
                    }
                }
            }
        } else if (((fp).unk_gobj()).classifier() as i32) == 6_i32 {
            if fns::itGetKind(ctx, detected_gobj) < (enums::It_Kind_BombHei as i32) {
                's2: {
                    let __case = match (fp).motion_id() {
                        0x15d_i32 => 0,
                        0x15f_i32 => 1,
                        _ => 2,
                    };
                    if __case <= 0 {
                        {
                            inl_onDetectGround_unfused(ctx, gobj);
                            break 's2;
                        }
                    }
                    if __case <= 1 {
                        {
                            inl_onDetectAir_unfused(ctx, gobj);
                            break 's2;
                        }
                    }
                }
            } else if (((fns::itGetKind(ctx, detected_gobj) >= (enums::It_Kind_Kuriboh as i32))
                && (fns::itGetKind(ctx, detected_gobj) < (enums::It_Kind_Octarock_Stone as i32)))
                || ((fns::itGetKind(ctx, detected_gobj) >= (enums::It_Kind_Old_Kuri as i32))
                    && (fns::itGetKind(ctx, detected_gobj) < (enums::It_Kind_Arwing_Laser as i32))))
                || (fns::itGetKind(ctx, detected_gobj) == (enums::It_PKind_Random as i32))
            {
                's3: {
                    let __case = match (fp).motion_id() {
                        0x15d_i32 => 0,
                        0x15f_i32 => 1,
                        _ => 2,
                    };
                    if __case <= 0 {
                        {
                            inl_onDetectGround_unfused(ctx, gobj);
                            break 's3;
                        }
                    }
                    if __case <= 1 {
                        {
                            inl_onDetectAir_unfused(ctx, gobj);
                            break 's3;
                        }
                    }
                }
            }
        }
    }
}

pub fn ftCa_SpecialSStart_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ft_8008A2BC(ctx, gobj);
    }
}

pub fn ftCa_SpecialS_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !((fp).u().ca().during_specials() != 0) {
        's1: {
            let __case = match (fns::ftLib_GetKind(ctx, gobj) as u32) {
                2_u32 => 0,
                25_u32 => 1,
                _ => 2,
            };
            if __case <= 0 {
                {
                    let _ = fns::efSync_Spawn(
                        ctx,
                        0x492_i32,
                        gobj,
                        &[
                            VarArg::Int(Handle::addr(
                                (Handle::add((fp).parts(), (enums::FtPart_TransN as i32))).joint(),
                            )),
                            VarArg::Int(Handle::addr((fp).facing_dir_ref())),
                        ],
                    );
                    (fp).u().ca().set_during_specials((1_i32 as u32));
                    break 's1;
                }
            }
            if __case <= 1 {
                let _ = fns::efSync_Spawn(
                    ctx,
                    0x50e_i32,
                    gobj,
                    &[
                        VarArg::Int(Handle::addr(
                            (Handle::add((fp).parts(), (enums::FtPart_TransN as i32))).joint(),
                        )),
                        VarArg::Int(Handle::addr((fp).facing_dir_ref())),
                    ],
                );
                (fp).u().ca().set_during_specials((1_i32 as u32));
                break 's1;
            }
            if __case <= 2 {
                break 's1;
            }
        }
        inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    }
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ft_8008A2BC(ctx, gobj);
    }
}

pub fn ftCa_SpecialAirSStart_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftCaptain_DatAttrs<'a> = Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCommon_8007D60C(ctx, fp);
        if (da).specials_miss_landing_lag() == fp::frsp(0_i32 as f64) {
            fns::ftCo_Fall_Enter(ctx, gobj);
        } else {
            fns::ftCo_80096900(
                ctx,
                gobj,
                1_i32,
                1_i32,
                0_i32,
                fp::frsp(1_i32 as f64),
                (da).specials_miss_landing_lag(),
            );
        }
    }
}

pub fn ftCa_SpecialAirS_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut captainAttrs: ftCaptain_DatAttrs<'a> =
        Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    if !((fp).u().ca().during_specials() != 0) {
        's1: {
            let __case = match (fns::ftLib_GetKind(ctx, gobj) as u32) {
                2_u32 => 0,
                25_u32 => 1,
                _ => 2,
            };
            if __case <= 0 {
                {
                    let _ = fns::efSync_Spawn(
                        ctx,
                        0x493_i32,
                        gobj,
                        &[
                            VarArg::Int(Handle::addr(
                                (Handle::add((fp).parts(), (enums::FtPart_TransN as i32))).joint(),
                            )),
                            VarArg::Int(Handle::addr((fp).facing_dir_ref())),
                        ],
                    );
                    (fp).u().ca().set_during_specials((1_i32 as u32));
                    break 's1;
                }
            }
            if __case <= 1 {
                {
                    let _ = fns::efSync_Spawn(
                        ctx,
                        0x50f_i32,
                        gobj,
                        &[
                            VarArg::Int(Handle::addr(
                                (Handle::add((fp).parts(), (enums::FtPart_TransN as i32))).joint(),
                            )),
                            VarArg::Int(Handle::addr((fp).facing_dir_ref())),
                        ],
                    );
                    (fp).u().ca().set_during_specials((1_i32 as u32));
                    break 's1;
                }
            }
            if __case <= 2 {
                break 's1;
            }
        }
        inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    }
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCommon_8007D60C(ctx, fp);
        if (captainAttrs).specials_hit_landing_lag() == fp::frsp(0_i32 as f64) {
            fns::ftCo_Fall_Enter(ctx, gobj);
        } else {
            fns::ftCo_80096900(
                ctx,
                gobj,
                1_i32,
                1_i32,
                0_i32,
                fp::frsp(1_i32 as f64),
                (captainAttrs).specials_hit_landing_lag(),
            );
        }
    }
}

pub fn ftCa_SpecialSStart_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftCa_SpecialS_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftCa_SpecialAirSStart_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftCa_SpecialAirS_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftCa_SpecialSStart_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084FA8(ctx, gobj);
}

pub fn ftCa_SpecialS_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084FA8(ctx, gobj);
}

pub fn ftCa_SpecialAirSStart_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut captainAttrs: ftCaptain_DatAttrs<'a> =
        Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    fns::ft_80085134(ctx, gobj);
    if (fp).cmd_vars().at(1_i32).get() == (1_i32 as u32) {
        (fp).mv().ca().specials().set_grav(fp::fsubs(
            (fp).mv().ca().specials().grav(),
            (captainAttrs).specials_grav(),
        ));
        if (fp).mv().ca().specials().grav() < fp::fneg((captainAttrs).specials_terminal_vel()) {
            (fp).mv()
                .ca()
                .specials()
                .set_grav(fp::fneg((captainAttrs).specials_terminal_vel()));
        }
        (fp).self_vel().set_y((fp).mv().ca().specials().grav());
    }
}

pub fn ftCa_SpecialAirS_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftCaptain_DatAttrs<'a> = Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    fns::ft_80085134(ctx, gobj);
    (fp).mv().ca().specials().set_grav(fp::fsubs(
        (fp).mv().ca().specials().grav(),
        (da).specials_grav(),
    ));
    if (fp).mv().ca().specials().grav() < fp::fneg((da).specials_terminal_vel()) {
        (fp).mv()
            .ca()
            .specials()
            .set_grav(fp::fneg((da).specials_terminal_vel()));
    }
    (fp).self_vel().set_y((fp).mv().ca().specials().grav());
}

pub fn ftCa_SpecialSStart_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftCaptain_DatAttrs<'a> = Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    if (fp).cmd_vars().at(2_i32).get() == (0_i32 as u32) {
        fns::ft_80084104(ctx, gobj);
        return;
    }
    if fns::ft_80082708(ctx, gobj) == ((0_i32 as u32) as i32) {
        fns::efLib_DestroyAll(ctx, gobj);
        fns::ftCommon_8007D60C(ctx, fp);
        if (da).specials_miss_landing_lag() == fp::frsp(0_i32 as f64) {
            fns::ftCo_Fall_Enter(ctx, gobj);
            return;
        }
        fns::ftCommon_ClampAirDrift(ctx, fp);
        fns::ftCo_80096900(
            ctx,
            gobj,
            1_i32,
            1_i32,
            0_i32,
            fp::frsp(1_i32 as f64),
            (da).specials_miss_landing_lag(),
        );
        return;
    }
    if (fp).cmd_vars().at(0_i32).get() == (1_i32 as u32) {
        let mut unused: f64 = (fp).facing_dir();
        if (((fp).facing_dir() == fp::frsp(1_i32 as f64))
            && (((fp).coll_data().env_flags() & 63_i32) != 0))
            || (((fp).facing_dir() == fp::frsp(1_i32.wrapping_neg() as f64))
                && (((fp).coll_data().env_flags() & 0xfc0_i32) != 0))
        {
            fns::efLib_DestroyAll(ctx, gobj);
            fns::ft_8008A2BC(ctx, gobj);
        }
    }
}

pub fn ftCa_SpecialS_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    let mut fp0: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    {
        let mut fp1: Fighter<'a> = null(ctx);
        let mut da: ftCaptain_DatAttrs<'a> =
            Handle::cast::<ftCaptain_DatAttrs<'a>>((fp0).dat_attrs());
        fp1 = fp0;
        if !(fns::ft_80082708(ctx, gobj) != 0) {
            fns::efLib_DestroyAll(ctx, gobj);
            fns::ftCommon_8007D60C(ctx, fp1);
            if (da).specials_hit_landing_lag() == fp::frsp(0_i32 as f64) {
                fns::ftCo_Fall_Enter(ctx, gobj);
                return;
            } else {
                fns::ftCommon_ClampAirDrift(ctx, fp1);
                fns::ftCo_80096900(
                    ctx,
                    gobj,
                    1_i32,
                    1_i32,
                    0_i32,
                    fp::frsp(1_i32 as f64),
                    (da).specials_hit_landing_lag(),
                );
            }
        }
    }
}

pub fn ftCa_SpecialAirSStart_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftCaptain_DatAttrs<'a> = Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    if fns::ft_80081D0C(ctx, gobj) == ((1_i32 as u32) as i32) {
        fns::efLib_DestroyAll(ctx, gobj);
        fns::ftCo_LandingFallSpecial_Enter(ctx, gobj, 0_i32, (da).specials_miss_landing_lag());
    }
}

pub fn ftCa_SpecialAirS_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftCaptain_DatAttrs<'a> = Handle::cast::<ftCaptain_DatAttrs<'a>>((fp).dat_attrs());
    if fns::ft_80081D0C(ctx, gobj) == ((1_i32 as u32) as i32) {
        (fp).set_gr_vel((fp).self_vel().x());
        fns::efLib_DestroyAll(ctx, gobj);
        fns::ftCo_LandingFallSpecial_Enter(ctx, gobj, 0_i32, (da).specials_hit_landing_lag());
    }
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_resetCmdVarsGround_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut vars: Val<'a, u32> = ((fp).cmd_vars().at(0_i32));
    (Handle::add(vars, 0_i32)).set({
        let __t3 = {
            let __t2 = {
                let __t1 = (0_i32 as u32);
                (Handle::add(vars, 3_i32)).set(__t1);
                __t1
            };
            (Handle::add(vars, 2_i32)).set(__t2);
            __t2
        };
        (Handle::add(vars, 1_i32)).set(__t3);
        __t3
    });
    fns::ftCommon_8007D7FC(ctx, fp);
}

fn inl_setCallbacks_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).set_take_dmg_cb(fnptr(ctx, 0x800e28c8));
    (fp).set_death2_cb(fnptr(ctx, 0x800e28c8));
}

fn inl_Fighter_SetEffectHitlagCallbacks_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) {
    let mut fp = fp;
    (fp).set_pre_hitlag_cb(fnptr(ctx, 0x8005ba40));
    (fp).set_post_hitlag_cb(fnptr(ctx, 0x8005bac4));
}

fn inl_resetVel_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) {
    let mut fp = fp;
    let mut vel: Vec<'a> = (fp).self_vel();
    (vel).set_x({
        let __t2 = {
            let __t1 = fp::frsp(0_i32 as f64);
            (vel).set_z(__t1);
            __t1
        };
        (vel).set_y(__t2);
        __t2
    });
}

fn inl_setupAirStart_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    {
        let mut vars: Val<'a, u32> = (fp).cmd_vars().at(0_i32);
        (Handle::add(vars, 0_i32)).set({
            let __t3 = {
                let __t2 = {
                    let __t1 = (0_i32 as u32);
                    (Handle::add(vars, 3_i32)).set(__t1);
                    __t1
                };
                (Handle::add(vars, 2_i32)).set(__t2);
                __t2
            };
            (Handle::add(vars, 1_i32)).set(__t3);
            __t3
        });
    }
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftCa_MS_SpecialAirSStart as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_setCallbacks_unfused(ctx, gobj);
    fns::ftAnim_8006EBA4(ctx, gobj);
    's1: {
        let __case = match (fns::ftLib_GetKind(ctx, gobj) as u32) {
            2_u32 => 0,
            25_u32 => 1,
            _ => 2,
        };
        if __case <= 0 {
            {
                let _ = fns::efSync_Spawn(
                    ctx,
                    0x491_i32,
                    gobj,
                    &[VarArg::Int(Handle::addr(
                        (Handle::add((fp).parts(), (enums::FtPart_HeadN as i32))).joint(),
                    ))],
                );
                (fp).u().ca().set_during_specials_start((1_i32 as u32));
                break 's1;
            }
        }
        if __case <= 1 {
            {
                let _ = fns::efSync_Spawn(
                    ctx,
                    0x50d_i32,
                    gobj,
                    &[VarArg::Int(Handle::addr(
                        (Handle::add((fp).parts(), (enums::FtPart_L2ndNb as i32))).joint(),
                    ))],
                );
                (fp).u().ca().set_during_specials_start((1_i32 as u32));
                break 's1;
            }
        }
        if __case <= 2 {
            break 's1;
        }
    }
    (fp).u().ca().set_during_specials((0_i32 as u32));
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_hurtbox_detect_cb(fnptr(ctx, 0x800e350c));
    {
        let mut vel: Vec<'a> = (fp).self_vel();
        (vel).set_x({
            let __t5 = {
                let __t4 = fp::frsp(0_i32 as f64);
                (vel).set_z(__t4);
                __t4
            };
            (vel).set_y(__t5);
            __t5
        });
    }
}

fn inl_getFtSpecialAttrsD_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) -> Addr<'a> {
    let mut fp = fp;
    return (fp).dat_attrs();
}

fn inl_onDetectGround_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut sa: ftCaptain_DatAttrs<'a> =
        Handle::cast::<ftCaptain_DatAttrs<'a>>(inl_getFtSpecialAttrsD_unfused(ctx, fp));
    fns::ftCommon_8007D7FC(ctx, fp);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftCa_MS_SpecialS as i32),
        0xc4c5082_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_setCallbacks_unfused(ctx, gobj);
    {
        let mut vel: Vec<'a> = (fp).self_vel();
        (vel).set_y({
            let __t1 = fp::frsp(0_i32 as f64);
            (vel).set_z(__t1);
            __t1
        });
    }
    (fp).set_gr_vel(fp::fmuls((fp).gr_vel(), (sa).specials_gr_vel_x()));
}

fn inl_onDetectAir_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftCa_MS_SpecialAirS as i32),
        0xc4c5082_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_setCallbacks_unfused(ctx, gobj);
    (fp).self_vel().set_z(fp::frsp(0_i32 as f64));
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x800e3278,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_RemoveGFX(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e32b0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e33e0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirS_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e350c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_OnDetect(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e384c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialSStart_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3888,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3964,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirSStart_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e39f0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirS_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b0c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialSStart_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b10,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b14,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirSStart_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b18,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirS_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b1c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialSStart_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b3c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3b5c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirSStart_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3bd0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirS_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3c38,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialSStart_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3d44,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialS_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3de4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirSStart_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e3e40,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCa_SpecialAirS_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
