// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftKirby/ftkirbyyoshiegg.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftKirby/ftkirbyyoshiegg
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn fn_8010AA64<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x38);
    let vec1: Vec<'a> = frame_at(ctx, &__frame, 0x0);
    let vec0: Vec<'a> = frame_at(ctx, &__frame, 0xc);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut jobj: HSD_JObj<'a> = Handle::cast::<HSD_JObj<'a>>((gobj).hsd_obj());
    if (fp).mv().co().yoshiegg().x14() <= 0.0 {
        fns::Fighter_UpdateModelScale(ctx, gobj);
        (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
        return;
    }
    (fp).mv()
        .co()
        .yoshiegg()
        .set_x14(fp::fsubs((fp).mv().co().yoshiegg().x14(), 1.0));
    {
        let mut temp0: f64 = fp::fdivs(
            (fp::fsubs(
                (fp).mv().co().yoshiegg().x10(),
                (fp).mv().co().yoshiegg().x14(),
            )),
            (fp).mv().co().yoshiegg().x10(),
        );
        temp0 = fp::fmuls(temp0, (fp).mv().co().yoshiegg().xC());
        {
            let mut temp1: f64 = fp::fadds((fp::fsubs(1.0, (fp).mv().co().yoshiegg().xC())), temp0);
            vec1.set_x({
                let __t2 = {
                    let __t1 = temp1;
                    vec1.set_z(__t1);
                    __t1
                };
                vec1.set_y(__t2);
                __t2
            });
            Handle::copy_from(vec0, vec1);
            vec1.set_x(fp::fmuls(vec1.x(), (fp).mv().co().yoshiegg().x18().x()));
            vec1.set_y(fp::fmuls(vec1.y(), (fp).mv().co().yoshiegg().x18().y()));
            vec1.set_z(fp::fmuls(vec1.z(), (fp).mv().co().yoshiegg().x18().z()));
            inl_HSD_JObjSetScale_unfused(ctx, jobj, vec1);
            vec0.set_x(fp::fmuls(vec0.x(), (fp).mv().co().yoshiegg().scale().x()));
            vec0.set_y(fp::fmuls(vec0.y(), (fp).mv().co().yoshiegg().scale().y()));
            vec0.set_z(fp::fmuls(vec0.z(), (fp).mv().co().yoshiegg().scale().z()));
            inl_HSD_JObjSetScale_unfused(ctx, (fp).x20A0_accessory(), vec0);
        }
    }
}

pub fn ftKb_SpecialNYs_8010AC78<'a>(ctx: &'a Ctx, victim: HSD_GObj<'a>, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x78);
    let scale: Vec<'a> = frame_at(ctx, &__frame, 0x0);
    let hurt: ftHurtboxInit<'a> = frame_at(ctx, &__frame, 0xc);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x34);
    let mut victim = victim;
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, victim)));
    let mut jobj: HSD_JObj<'a> =
        (Handle::cast::<HSD_JObj<'a>>(inl_HSD_GObjGetHSDObj_unfused(ctx, victim)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
        fns::ftCommon_8007D5D4(ctx, fp);
    }
    fns::Fighter_ChangeMotionState(
        ctx,
        victim,
        (enums::ftCo_MS_KirbyYoshiEgg as i32),
        64_u32,
        0.0,
        1.0,
        0.0,
        gobj,
    );
    (fp).set_take_dmg_cb(fnptr(ctx, 0x8010b1d4));
    fns::ftCommon_8007E2F4(ctx, fp, (0x1ff_i32 as i16));
    (fp).set_invisible((1_i32 as u8));
    scale.set_x({
        let __t2 = {
            let __t1 = (fp).co_attrs().xBC().size();
            scale.set_z(__t1);
            __t1
        };
        scale.set_y(__t2);
        __t2
    });
    fns::ftCommon_SetAccessory(
        ctx,
        fp,
        Handle::cast::<HSD_Joint<'a>>(fns::ftKb_SpecialNYs_801093A0(ctx, gobj)),
    );
    inl_HSD_JObjSetScale_unfused(ctx, (fp).x20A0_accessory(), scale);
    fns::lb_8000C2F8(
        ctx,
        inl_HSD_JObjGetChild_unfused(ctx, (fp).x20A0_accessory()),
        (Handle::add(
            (fp).parts(),
            fns::ftParts_GetBoneIndex(ctx, fp, (enums::FtPart_TransN as i32)),
        ))
        .joint(),
    );
    Handle::copy_from((fp).mv().co().yoshiegg().scale(), scale);
    inl_inlineB0_unfused(ctx, victim, hurt);
    fns::ftKb_SpecialNYs_80109260(ctx, gobj, (fp).self_vel());
    (fp).set_facing_dir(fns::ftKb_SpecialNYs_80109290(ctx, gobj));
    (fp).dmg()
        .set_x182c_behavior(fns::ftKb_SpecialNYs_8010929C(ctx, gobj));
    (fp).mv().ca().specialhi().vel().set_y(0.0);
    (fp).mv().co().yoshiegg().set_x0(gobj);
    (fp).set_take_dmg_2_cb(fnptr(ctx, 0x8010b16c));
    fns::ftCommon_8007EFC0(ctx, fp, (1_i32 as u32));
    (fp).mv()
        .co()
        .walk()
        .set_fast_anim_frame(fns::ftKb_SpecialNYs_801092BC(ctx, gobj));
    (fp).mv()
        .co()
        .common()
        .set_x14((fp).mv().co().walk().fast_anim_frame());
    (fp).mv()
        .co()
        .common()
        .x4()
        .set_z(fns::ftKb_SpecialNYs_801092AC(ctx, gobj));
    fns::ftCommon_InitGrab(ctx, fp, 0_i32, fns::ftKb_SpecialNYs_801092CC(ctx, gobj));
    inl_HSD_JObjGetScale_unfused(ctx, jobj, (fp).mv().co().yoshiegg().x18());
    (fp).set_accessory4_cb(fnptr(ctx, 0x8010aa64));
}

pub fn ftCo_KirbyYoshiEgg_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut temp_ret: f64 = 0.0;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    temp_ret = fns::ftKb_SpecialNYs_801092DC(ctx);
    (fp).set_grab_timer(fp::fsubs((fp).grab_timer(), temp_ret));
    (fp).mv().kb().specialhi().set_x4(fns::ftCommon_GrabMash(
        ctx,
        fp,
        fns::ftKb_SpecialNYs_801092F4(ctx),
    ));
    if (fp).grab_timer() <= 0.0 {
        let mut fp2: Fighter<'a> = null(ctx);
        let mut xBCp: ftCo_DatAttrs_xBC_t<'a> = null(ctx);
        fns::ft_PlaySFX(ctx, fp, 0x44618_i32, (127_i32 as u8), (64_i32 as u8));
        fp2 = Handle::cast::<Fighter<'a>>((gobj).user_data());
        fns::efAsync_Spawn(
            ctx,
            gobj,
            (fp2).x60C_ref(),
            (4_i32 as u32),
            (0x4cf_i32 as u32),
            (Handle::add((fp).parts(), 0_i32)).joint(),
            &[VarArg::Int(Handle::addr(
                ({
                    let __t1 = (fp).co_attrs().xBC();
                    xBCp = __t1;
                    __t1
                }),
            ))],
        );
        fns::ftKb_SpecialNYs_80109354(ctx, (fp).self_vel());
        fns::ftCommon_8007D5D4(ctx, fp);
        fns::ftColl_8007B760(ctx, gobj, fns::ftKb_SpecialNYs_8010933C(ctx));
        fns::ftCo_Fall_Enter_YoshiEgg_Kirby(ctx, gobj);
        return;
    }
    if ((fp).mv().kb().specialhi().x8().f() != 0.0) {
        (fp).mv().kb().specialhi().x8().set_f(fp::fsubs(
            (fp).mv().kb().specialhi().x8().f(),
            fp::frsp(1.0),
        ));
        if ((fp).mv().kb().specialhi().x8().f() <= 0.0)
            && ((fp).mv().kb().specialhi().x4() == 0_i32)
        {
            fns::ftAnim_SetAnimRate(ctx, gobj, 1.0);
            (fp).mv().kb().specialhi().x8().set_f(0.0);
        }
    }
    if ((fp).mv().kb().specialhi().x8().f() <= 0.0) && ((fp).mv().kb().specialhi().x4() != 0_i32) {
        (fp).mv()
            .kb()
            .specialhi()
            .x8()
            .set_f(fns::ftKb_SpecialNYs_8010930C(ctx));
        fns::ftAnim_SetAnimRate(ctx, gobj, fns::ftKb_SpecialNYs_80109324(ctx));
    }
}

pub fn ftCo_KirbyYoshiEgg_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftCo_KirbyYoshiEgg_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
        fns::ft_80084F3C(ctx, gobj);
        return;
    }
    fns::ft_80084DB0(ctx, gobj);
}

pub fn ftCo_KirbyYoshiEgg_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
        fns::ft_8008403C(ctx, gobj, fnptr(ctx, 0x8010b148));
        return;
    }
    fns::ft_80082C74(ctx, gobj, fnptr(ctx, 0x8010b124));
}

pub fn fn_8010B124<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ftCommon_8007D7FC(
        ctx,
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj))),
    );
}

pub fn fn_8010B148<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ftCommon_8007D5D4(
        ctx,
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj))),
    );
}

pub fn fn_8010B16C<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    (fp).set_grab_timer(fp::fnmsubs(
        (fp).dmg().x1838_percentTemp(),
        fns::ftKb_SpecialNYs_80109380(ctx),
        (fp).grab_timer(),
    ));
    if ((fp).dmg().x18CC() == 3_i32) && (fns::ftCo_800C0C88(ctx, (fp).dmg().x18D0()) != 0_i32) {
        (fp).set_grab_timer(0.0);
    }
    (fp).set_x1828(4_i32);
}

pub fn fn_8010B1D4<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Fighter_UpdateModelScale(ctx, gobj);
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_HSD_JObjSetScale_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>, scale: Vec<'a>) {
    let mut jobj = jobj;
    let mut scale = scale;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x804d3df4),
            (0x17e_i32 as u32),
            cstr(ctx, 0x804d3df4),
        )
    });
    (if !Handle::is_null((scale)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x804d3df4),
            (0x17f_i32 as u32),
            cstr(ctx, 0x804d3df4),
        )
    });
    Handle::copy_from((jobj).scale(), (scale));
    if !(((jobj).flags() & ((shl_i32(1_i32, (25_i32 as u32))) as u32)) != 0) {
        {
            if (!Handle::is_null(jobj)) && (!(inl_HSD_JObjMtxIsDirty_unfused(ctx, jobj) != 0)) {
                fns::HSD_JObjSetMtxDirtySub(ctx, jobj);
            }
        }
    }
}

fn inl_HSD_JObjMtxIsDirty_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>) -> i32 {
    let mut jobj = jobj;
    let mut result: i32 = 0;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x804d3df4),
            (228_i32 as u32),
            cstr(ctx, 0x804d3df4),
        )
    });
    result = 0_i32;
    if (!(((jobj).flags() & ((shl_i32(1_i32, (23_i32 as u32))) as u32)) != 0))
        && (((jobj).flags() & ((shl_i32(1_i32, (6_i32 as u32))) as u32)) != 0)
    {
        result = 1_i32;
    }
    return result;
}

fn inl_HSD_GObjGetHSDObj_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).hsd_obj();
}

fn inl_HSD_JObjGetChild_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>) -> HSD_JObj<'a> {
    let mut jobj = jobj;
    if Handle::is_null(jobj) {
        return null::<HSD_JObj<'a>>(ctx);
    } else {
        return (jobj).child();
    }
    #[allow(unreachable_code)]
    return null(ctx);
}

fn inl_inlineB0_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, hurt: ftHurtboxInit<'a>) {
    let mut gobj = gobj;
    let mut hurt = hurt;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut xBCp: ftCo_DatAttrs_xBC_t<'a> = null(ctx);
    fns::ftColl_8007B0C0(ctx, gobj, (enums::HurtCapsule_Intangible as i32));
    xBCp = (fp).co_attrs().xBC();
    (hurt).set_bone_idx(fns::ftParts_GetBoneIndex(
        ctx,
        fp,
        (enums::FtPart_TransN as i32),
    ));
    (hurt).set_height((enums::HurtHeight_Mid as i32));
    (hurt).set_is_grabbable((0_i32 as u32));
    Handle::copy_from((hurt).a_offset(), (xBCp).x4());
    Handle::copy_from((hurt).b_offset(), (xBCp).x10());
    (hurt).set_scale((xBCp).x1C());
    fns::ftColl_HurtboxInit(ctx, fp, (fp).hurt_capsules().get(0), hurt);
}

fn inl_HSD_JObjGetScale_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>, scale: Vec<'a>) {
    let mut jobj = jobj;
    let mut scale = scale;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x804d3df4),
            (0x1c8_i32 as u32),
            cstr(ctx, 0x804d3df4),
        )
    });
    (if !Handle::is_null((scale)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x804d3df4),
            (0x1c9_i32 as u32),
            cstr(ctx, 0x804d3df4),
        )
    });
    Handle::copy_from((scale), (jobj).scale());
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x8010aa64,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_8010AA64(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010ac78,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, HSD_GObj<'_>) = Args::take_all(ctx);
            Ret::put(ftKb_SpecialNYs_8010AC78(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010af54,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_KirbyYoshiEgg_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b0a0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_KirbyYoshiEgg_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b0a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_KirbyYoshiEgg_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b0dc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_KirbyYoshiEgg_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b124,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_8010B124(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b148,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_8010B148(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b16c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_8010B16C(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8010b1d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(fn_8010B1D4(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
