// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftSamus/ftsamusspecials.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftSamus/ftsamusspecials
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn ftSs_SpecialS_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut samus_attr: _ftSamusAttributes<'a> =
        Handle::cast::<_ftSamusAttributes<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    (fp).set_gr_vel(fp::fdivs((fp).gr_vel(), (samus_attr).x2C()));
    (fp).self_vel().set_y(0.0);
    if fp::frsp(((fp).active_sticky().lstick().x() as i32) as f64) < (samus_attr).x28() {
        fns::Fighter_ChangeMotionState(
            ctx,
            gobj,
            0x15e_i32,
            0_u32,
            0.0,
            1.0,
            0.0,
            null::<HSD_GObj<'a>>(ctx),
        );
        fns::ftAnim_8006EBA4(ctx, gobj);
    } else {
        fns::Fighter_ChangeMotionState(
            ctx,
            gobj,
            0x15d_i32,
            0_u32,
            0.0,
            1.0,
            0.0,
            null::<HSD_GObj<'a>>(ctx),
        );
        fns::ftAnim_8006EBA4(ctx, gobj);
    }
    inl_ftSamus_ClearThrowFlagsUnk_unfused(ctx, gobj);
}

pub fn ftSs_SpecialAirS_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut samus_attr: _ftSamusAttributes<'a> =
        Handle::cast::<_ftSamusAttributes<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    (fp).self_vel()
        .set_x(fp::fdivs((fp).self_vel().x(), (samus_attr).x2C()));
    if fp::frsp(((fp).active_sticky().lstick().x() as i32) as f64) < (samus_attr).x28() {
        fns::Fighter_ChangeMotionState(
            ctx,
            gobj,
            0x160_i32,
            0_u32,
            0.0,
            1.0,
            0.0,
            null::<HSD_GObj<'a>>(ctx),
        );
        fns::ftAnim_8006EBA4(ctx, gobj);
    } else {
        fns::Fighter_ChangeMotionState(
            ctx,
            gobj,
            0x15f_i32,
            0_u32,
            0.0,
            1.0,
            0.0,
            null::<HSD_GObj<'a>>(ctx),
        );
        fns::ftAnim_8006EBA4(ctx, gobj);
    }
    inl_ftSamus_ClearThrowFlagsUnk_unfused(ctx, gobj);
}

pub fn ftSs_SpecialS_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ft_8008A2BC(ctx, gobj);
    }
}

pub fn ftSs_SpecialAirS_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftSs_SpecialS_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftSs_SpecialAirS_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftSs_SpecialS_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
}

pub fn ftSs_SpecialAirS_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x40);
    let unused: ArrV<'a, u8, 24> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut samus_attr: _ftSamusAttributes<'a> =
        Handle::cast::<_ftSamusAttributes<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    let mut fighter2: Fighter<'a> = null(ctx);
    fns::ftCommon_FallBasic(ctx, fp);
    fighter2 = fp;
    fns::ftCommon_CalcSelfAccel_Deaccel(ctx, fighter2, (samus_attr).x30());
}

pub fn ftSs_SpecialS_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ft_800827A0(ctx, gobj) != 0) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftSs_SpecialAirS_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) != 0) {
        fns::ft_80082B1C(ctx, gobj);
    }
}

pub fn ftSs_SpecialSSmash_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ft_8008A2BC(ctx, gobj);
    }
}

pub fn ftSs_SpecialAirSSmash_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftSs_SpecialSSmash_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftSs_SpecialAirSSmash_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn ftSs_SpecialSSmash_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
}

pub fn ftSs_SpecialAirSSmash_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x50);
    let unused: ArrV<'a, u8, 40> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fighter2: Fighter<'a> = null(ctx);
    let mut fp: Fighter<'a> = null(ctx);
    let mut samus_attr: _ftSamusAttributes<'a> = null(ctx);
    let mut samus_attr2: _ftSamusAttributes<'a> = null(ctx);
    fp = {
        let __t1 = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
        fighter2 = __t1;
        __t1
    };
    samus_attr = Handle::cast::<_ftSamusAttributes<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    fns::ftCommon_FallBasic(ctx, fp);
    samus_attr2 = samus_attr;
    fns::ftCommon_CalcSelfAccel_Deaccel(ctx, fp, (samus_attr2).x30());
}

pub fn ftSs_SpecialSSmash_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ft_80082708(ctx, gobj) != 0) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftSs_SpecialAirSSmash_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) != 0) {
        fns::ft_80082B1C(ctx, gobj);
    }
}

pub fn ftSs_SpecialS_8012A640<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    fns::efLib_DestroyAll(ctx, gobj);
    (fp).u().ss().set_x2244((0_i32 as u32));
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_getFtSpecialAttrs_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) -> Addr<'a> {
    let mut fp = fp;
    let mut fighter_attr: Addr<'a> = (fp).dat_attrs();
    return fighter_attr;
}

fn inl_ftSamus_ClearThrowFlagsUnk_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).x2210().set_throw_flags((0_i32 as u32));
    (fp).set_accessory4_cb(fnptr(ctx, 0x8012a074));
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x8012a1d8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a2ac,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirS_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a380,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a3bc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirS_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a3f8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a3fc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirS_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a400,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a420,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirS_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a468,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a4a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirS_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a4e0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialSSmash_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a51c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirSSmash_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a558,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialSSmash_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a55c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirSSmash_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a560,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialSSmash_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a580,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirSSmash_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a5c8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialSSmash_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a604,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialAirSSmash_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8012a640,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftSs_SpecialS_8012A640(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
