// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/it/ithitbox.c. Do not edit; fix the translator or port by hand.
// unit: melee/it/ithitbox
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;
use ssbm_rt::cpu as c;

pub fn it_802753DC<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).set_xC34_damageDealt(0_i32);
    (item).set_xC40(1.0);
    (item).set_xC44(1.0);
    (item).set_xC3C(1.0);
    (item).set_xC48(0_i32);
    (item).set_xC4C(0_i32);
    (item).set_xC50(0_i32);
    (item).xDCE_flag().x0().set_b6((0_i32 as u8));
}

pub fn it_80275414<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCD_flag().x0().set_b7((1_i32 as u8));
}

pub fn it_8027542C<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCD_flag().x0().set_b7((0_i32 as u8));
}

pub fn it_80275444<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCD_flag().x0().set_b5((1_i32 as u8));
    (item).xDCD_flag().x0().set_b7((1_i32 as u8));
    (item).xDCD_flag().x0().set_b6((1_i32 as u8));
}

pub fn it_80275474<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCD_flag().x0().set_b5((0_i32 as u8));
    (item).xDCD_flag().x0().set_b7((0_i32 as u8));
    (item).xDCD_flag().x0().set_b6((0_i32 as u8));
}

pub fn it_802754A4<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCE_flag().x0().set_b2((1_i32 as u8));
}

pub fn it_802754BC<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCE_flag().x0().set_b2((0_i32 as u8));
}

pub fn it_802754D4<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCE_flag().x0().set_b0((1_i32 as u8));
    (item).xDCE_flag().x0().set_b2((1_i32 as u8));
    (item).xDCE_flag().x0().set_b1((1_i32 as u8));
}

pub fn it_80275504<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item).xDCE_flag().x0().set_b0((0_i32 as u8));
    (item).xDCE_flag().x0().set_b2((0_i32 as u8));
    (item).xDCE_flag().x0().set_b1((0_i32 as u8));
}

pub fn it_80275534<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, scale: f64) {
    let mut item_gobj = item_gobj;
    let mut scale = scale;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    let mut var_ctr: u32 = 0;
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    {
        var_ctr = 0_u32;
        'l1: while var_ctr < 4_u32 {
            'c2: {
                hitcapsule = (item).x5D4_hitboxes().get((var_ctr as i32)).hit();
                if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
                    (hitcapsule).set_scale(scale);
                }
            }
            var_ctr = var_ctr.wrapping_add(1);
        }
    }
}

pub fn it_80275594<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, idx: i32, mult: f64) {
    let mut item_gobj = item_gobj;
    let mut idx = idx;
    let mut mult = mult;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    hitcapsule = (item).x5D4_hitboxes().get(idx).hit();
    if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
        (hitcapsule).set_scale(fp::fmuls((hitcapsule).scale(), mult));
    }
}

pub fn it_802755C0<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, scale: f64) {
    let mut item_gobj = item_gobj;
    let mut scale = scale;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    let mut var_ctr: u32 = 0;
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    {
        var_ctr = 0_u32;
        'l1: while var_ctr < 4_u32 {
            'c2: {
                hitcapsule = (item).x5D4_hitboxes().get((var_ctr as i32)).hit();
                if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
                    (hitcapsule).set_scale(fp::fmuls((hitcapsule).scale(), scale));
                }
            }
            var_ctr = var_ctr.wrapping_add(1);
        }
    }
}

pub fn it_80275640<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, arg1: f64) {
    let __frame = ctx.stack_frame(0x30);
    let mut item_gobj = item_gobj;
    let mut arg1 = arg1;
    let mut item: Item<'a> =
        (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, item_gobj)));
    let mut i: u32 = 0;
    {
        i = (0_i32 as u32);
        'l1: while i < (4_i32 as u32) {
            'c2: {
                let mut hitcapsule: HitCapsule<'a> = (item).x5D4_hitboxes().get((i as i32)).hit();
                if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
                    fns::it_80272460(
                        ctx,
                        hitcapsule,
                        fns::__cvt_fp2unsigned(ctx, fp::fmuls((hitcapsule).damage(), arg1)),
                        item_gobj,
                    );
                }
            }
            i = i.wrapping_add(1);
        }
    }
}

pub fn it_802756D0<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    (Handle::cast::<Item<'a>>((item_gobj).user_data())).set_xD0C(2_i32);
}

pub fn it_802756E0<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut item_gobj = item_gobj;
    (Handle::cast::<Item<'a>>((item_gobj).user_data())).set_xD0C(0_i32);
    fns::it_802714C0(ctx, item_gobj);
}

pub fn it_8027570C<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, idx: i32) {
    let mut item_gobj = item_gobj;
    let mut idx = idx;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item)
        .x5D4_hitboxes()
        .get(idx)
        .hit()
        .set_x40_b0((0_i32 as u16));
}

pub fn it_8027572C<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>, idx: i32) {
    let mut item_gobj = item_gobj;
    let mut idx = idx;
    let mut item: Item<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    (item)
        .x5D4_hitboxes()
        .get(idx)
        .hit()
        .set_x40_b0((1_i32 as u16));
}

pub fn it_8027574C<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = Handle::cast::<Item<'a>>((item_gobj).user_data());
    fns::it_80274D04(ctx, item_gobj, (item).xB54());
    fns::it_80274D6C(ctx, item_gobj);
}

pub fn it_80275788<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    let mut state: i32 = 0;
    let mut var_ctr: u32 = 0;
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    state = (enums::HitCapsule_Unk4 as i32);
    {
        var_ctr = 0_u32;
        'l1: while var_ctr < 4_u32 {
            'c2: {
                hitcapsule = ({ (item).x5D4_hitboxes().get((var_ctr as i32)).hit() });
                if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
                    (hitcapsule).set_state(state);
                    (item).xDAA().xDAA_flag().x0().set_b2((1_i32 as u8));
                }
            }
            var_ctr = var_ctr.wrapping_add(1);
        }
    }
}

pub fn it_80275820<'a>(
    ctx: &'a Ctx,
    item_gobj: HSD_GObj<'a>,
    arg1: Vec<'a>,
    arg2: Vec<'a>,
    idx: i32,
) {
    let mut item_gobj = item_gobj;
    let mut arg1 = arg1;
    let mut arg2 = arg2;
    let mut idx = idx;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    hitcapsule = (item).x5D4_hitboxes().get(idx).hit();
    if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
        Handle::copy_from((hitcapsule).x58(), (arg2));
        Handle::copy_from((hitcapsule).x4C(), (arg1));
    }
}

pub fn it_80275870<'a>(ctx: &'a Ctx, item_gobj: HSD_GObj<'a>) -> i32 {
    let mut item_gobj = item_gobj;
    let mut item: Item<'a> = null(ctx);
    let mut hitcapsule: HitCapsule<'a> = null(ctx);
    let mut var_ctr: u32 = 0;
    item = Handle::cast::<Item<'a>>((item_gobj).user_data());
    {
        var_ctr = 0_u32;
        'l1: while var_ctr < 4_u32 {
            'c2: {
                hitcapsule = (item).x5D4_hitboxes().get((var_ctr as i32)).hit();
                if (hitcapsule).state() != (((enums::HitCapsule_Disabled as i32) as u32) as i32) {
                    return 1_i32;
                }
            }
            var_ctr = var_ctr.wrapping_add(1);
        }
    }
    return 0_i32;
}

pub fn it_802758D4<'a>(ctx: &'a Ctx, a0: HSD_GObj<'a>) -> f64 {
    // Transliterated from its machine code: returns or uses a value its C never sets.
    (a0,).put_regs(ctx);
    asm_it_802758D4(ctx);
    Ret::get(ctx)
}

fn asm_it_802758D4(ctx: &Ctx) {
    let g = &ctx.regs.gpr;
    let f = &ctx.regs.fpr;
    let lr0 = ctx.regs.lr.get();
    let _ = (g, f, lr0);
    let mut pc: u32 = 0x802758d4_u32;
    loop {
        match pc {
            0x802758d4_u32 => {
                // lwz r4, 0x2c(r3)
                {
                    let ea = g[3].get().wrapping_add(0x2c_u32);
                    g[4].set(ctx.read_u32(ea));
                }
                // lfs f1, "@243"@sda21(r0)
                {
                    let ea = g[2].get().wrapping_add(0xffffcd54_u32);
                    c::fill(ctx, 1, fp::lfs(ctx.read_u32(ea)));
                }
                // lwz r0, 0x5d4(r4)
                {
                    let ea = g[4].get().wrapping_add(0x5d4_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_802758F0
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x802758f0_u32;
                    continue;
                }
                pc = 0x802758e8_u32;
            }
            0x802758e8_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // b .L_80275938
                pc = 0x80275938_u32;
                continue;
                pc = 0x802758f0_u32;
            }
            0x802758f0_u32 => {
                // addi r3, r4, 0x13c
                g[3].set(g[4].get().wrapping_add(0x13c_u32));
                // lwz r0, 0x710(r4)
                {
                    let ea = g[4].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80275908
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80275908_u32;
                    continue;
                }
                pc = 0x80275900_u32;
            }
            0x80275900_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // b .L_80275938
                pc = 0x80275938_u32;
                continue;
                pc = 0x80275908_u32;
            }
            0x80275908_u32 => {
                // lwz r0, 0x710(r3)
                {
                    let ea = g[3].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r3, r3, 0x13c
                g[3].set(g[3].get().wrapping_add(0x13c_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80275920
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80275920_u32;
                    continue;
                }
                pc = 0x80275918_u32;
            }
            0x80275918_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // b .L_80275938
                pc = 0x80275938_u32;
                continue;
                pc = 0x80275920_u32;
            }
            0x80275920_u32 => {
                // lwz r0, 0x710(r3)
                {
                    let ea = g[3].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80275934
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80275934_u32;
                    continue;
                }
                pc = 0x8027592c_u32;
            }
            0x8027592c_u32 => {
                // li r0, 0x1
                g[0].set(0x1_u32);
                // b .L_80275938
                pc = 0x80275938_u32;
                continue;
                pc = 0x80275934_u32;
            }
            0x80275934_u32 => {
                // li r0, 0x0
                g[0].set(0_u32);
                pc = 0x80275938_u32;
            }
            0x80275938_u32 => {
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beqlr
                if (c::cr_bit(ctx, 2) == true) {
                    let to = ctx.regs.lr.get() & !3;
                    if to != lr0 & !3 {
                        c::tail_call(ctx, to);
                    }
                    return;
                }
                pc = 0x80275940_u32;
            }
            0x80275940_u32 => {
                // lwz r0, 0x5d4(r4)
                {
                    let ea = g[4].get().wrapping_add(0x5d4_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r5, r4, 0x5d4
                g[5].set(g[4].get().wrapping_add(0x5d4_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_80275964
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x80275964_u32;
                    continue;
                }
                pc = 0x80275950_u32;
            }
            0x80275950_u32 => {
                // lfs f0, 0xc(r5)
                {
                    let ea = g[5].get().wrapping_add(0xc_u32);
                    c::fill(ctx, 0, fp::lfs(ctx.read_u32(ea)));
                }
                // fcmpo cr0, f1, f0
                c::fp_compare(ctx, 0, ctx.regs.f(1), ctx.regs.f(0));
                // cror eq, lt, eq
                {
                    let (x, y) = (c::cr_bit(ctx, 0), c::cr_bit(ctx, 2));
                    c::set_cr_bit(ctx, 2, x | y);
                }
                // bne .L_80275964
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x80275964_u32;
                    continue;
                }
                pc = 0x80275960_u32;
            }
            0x80275960_u32 => {
                // fmr f1, f0
                {
                    let v = ctx.regs.f(0);
                    ctx.regs.set_f(1, v);
                }
                pc = 0x80275964_u32;
            }
            0x80275964_u32 => {
                // addi r3, r4, 0x13c
                g[3].set(g[4].get().wrapping_add(0x13c_u32));
                // lwz r0, 0x710(r4)
                {
                    let ea = g[4].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r5, r3, 0x5d4
                g[5].set(g[3].get().wrapping_add(0x5d4_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_8027598C
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x8027598c_u32;
                    continue;
                }
                pc = 0x80275978_u32;
            }
            0x80275978_u32 => {
                // lfs f0, 0xc(r5)
                {
                    let ea = g[5].get().wrapping_add(0xc_u32);
                    c::fill(ctx, 0, fp::lfs(ctx.read_u32(ea)));
                }
                // fcmpo cr0, f1, f0
                c::fp_compare(ctx, 0, ctx.regs.f(1), ctx.regs.f(0));
                // cror eq, lt, eq
                {
                    let (x, y) = (c::cr_bit(ctx, 0), c::cr_bit(ctx, 2));
                    c::set_cr_bit(ctx, 2, x | y);
                }
                // bne .L_8027598C
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x8027598c_u32;
                    continue;
                }
                pc = 0x80275988_u32;
            }
            0x80275988_u32 => {
                // fmr f1, f0
                {
                    let v = ctx.regs.f(0);
                    ctx.regs.set_f(1, v);
                }
                pc = 0x8027598c_u32;
            }
            0x8027598c_u32 => {
                // lwz r0, 0x710(r3)
                {
                    let ea = g[3].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r5, r3, 0x710
                g[5].set(g[3].get().wrapping_add(0x710_u32));
                // addi r3, r3, 0x13c
                g[3].set(g[3].get().wrapping_add(0x13c_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beq .L_802759B4
                if (c::cr_bit(ctx, 2) == true) {
                    pc = 0x802759b4_u32;
                    continue;
                }
                pc = 0x802759a0_u32;
            }
            0x802759a0_u32 => {
                // lfs f0, 0xc(r5)
                {
                    let ea = g[5].get().wrapping_add(0xc_u32);
                    c::fill(ctx, 0, fp::lfs(ctx.read_u32(ea)));
                }
                // fcmpo cr0, f1, f0
                c::fp_compare(ctx, 0, ctx.regs.f(1), ctx.regs.f(0));
                // cror eq, lt, eq
                {
                    let (x, y) = (c::cr_bit(ctx, 0), c::cr_bit(ctx, 2));
                    c::set_cr_bit(ctx, 2, x | y);
                }
                // bne .L_802759B4
                if (c::cr_bit(ctx, 2) == false) {
                    pc = 0x802759b4_u32;
                    continue;
                }
                pc = 0x802759b0_u32;
            }
            0x802759b0_u32 => {
                // fmr f1, f0
                {
                    let v = ctx.regs.f(0);
                    ctx.regs.set_f(1, v);
                }
                pc = 0x802759b4_u32;
            }
            0x802759b4_u32 => {
                // lwz r0, 0x710(r3)
                {
                    let ea = g[3].get().wrapping_add(0x710_u32);
                    g[0].set(ctx.read_u32(ea));
                }
                // addi r5, r3, 0x710
                g[5].set(g[3].get().wrapping_add(0x710_u32));
                // cmpwi r0, 0x0
                {
                    let (x, y) = (g[0].get() as i32, 0_i32);
                    c::compare(ctx, 0, x < y, x > y);
                }
                // beqlr
                if (c::cr_bit(ctx, 2) == true) {
                    let to = ctx.regs.lr.get() & !3;
                    if to != lr0 & !3 {
                        c::tail_call(ctx, to);
                    }
                    return;
                }
                pc = 0x802759c4_u32;
            }
            0x802759c4_u32 => {
                // lfs f0, 0xc(r5)
                {
                    let ea = g[5].get().wrapping_add(0xc_u32);
                    c::fill(ctx, 0, fp::lfs(ctx.read_u32(ea)));
                }
                // fcmpo cr0, f1, f0
                c::fp_compare(ctx, 0, ctx.regs.f(1), ctx.regs.f(0));
                // cror eq, lt, eq
                {
                    let (x, y) = (c::cr_bit(ctx, 0), c::cr_bit(ctx, 2));
                    c::set_cr_bit(ctx, 2, x | y);
                }
                // bnelr
                if (c::cr_bit(ctx, 2) == false) {
                    let to = ctx.regs.lr.get() & !3;
                    if to != lr0 & !3 {
                        c::tail_call(ctx, to);
                    }
                    return;
                }
                pc = 0x802759d4_u32;
            }
            0x802759d4_u32 => {
                // fmr f1, f0
                {
                    let v = ctx.regs.f(0);
                    ctx.regs.set_f(1, v);
                }
                // blr
                let to = ctx.regs.lr.get() & !3;
                if to != lr0 & !3 {
                    c::tail_call(ctx, to);
                }
                return;
                panic!("ran off the end of it_802758D4");
            }
            _ => unreachable!("it_802758D4: no block at {pc:#010x}"),
        }
    }
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x802753dc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802753DC(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275414,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275414(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8027542c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8027542C(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275444,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275444(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275474,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275474(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802754a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802754A4(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802754bc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802754BC(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802754d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802754D4(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275504,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275504(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275534,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, Single) = Args::take_all(ctx);
            Ret::put(it_80275534(ctx, a0, a1.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275594,
        |ctx| {
            let (a0, a1, a2): (HSD_GObj<'_>, i32, Single) = Args::take_all(ctx);
            Ret::put(it_80275594(ctx, a0, a1, a2.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802755c0,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, Single) = Args::take_all(ctx);
            Ret::put(it_802755C0(ctx, a0, a1.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275640,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, Single) = Args::take_all(ctx);
            Ret::put(it_80275640(ctx, a0, a1.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802756d0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802756D0(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802756e0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802756E0(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8027570c,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, i32) = Args::take_all(ctx);
            Ret::put(it_8027570C(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8027572c,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, i32) = Args::take_all(ctx);
            Ret::put(it_8027572C(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8027574c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8027574C(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275788,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275788(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275820,
        |ctx| {
            let (a0, a1, a2, a3): (HSD_GObj<'_>, Vec<'_>, Vec<'_>, i32) = Args::take_all(ctx);
            Ret::put(it_80275820(ctx, a0, a1, a2, a3), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80275870,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_80275870(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x802758d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802758D4(ctx, a0), ctx);
        },
        Returns::Float,
    );
}
