// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/it/kinds/itfreeze.c. Do not edit; fix the translator or port by hand.
// unit: melee/it/kinds/itfreeze
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn it_8028EB88<'a>(
    ctx: &'a Ctx,
    ref_gobj: HSD_GObj<'a>,
    pos: Vec<'a>,
    facing_dir: f64,
    decel: f64,
) -> HSD_GObj<'a> {
    let __frame = ctx.stack_frame(0x78);
    let spawn: SpawnItem<'a> = frame_at(ctx, &__frame, 0x0);
    let mut ref_gobj = ref_gobj;
    let mut pos = pos;
    let mut facing_dir = facing_dir;
    let mut decel = decel;
    let mut gobj: HSD_GObj<'a> = null(ctx);
    let mut ip: Item<'a> = null(ctx);
    if !Handle::is_null(ref_gobj) {
        ip = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, ref_gobj)));
    }
    spawn.set_kind((enums::It_Kind_Freeze as i32));
    Handle::copy_from(spawn.prev_pos(), (pos));
    if !Handle::is_null(ip) {
        Handle::copy_from(spawn.pos(), (ip).pos());
    } else {
        Handle::copy_from(spawn.pos(), spawn.prev_pos());
    }
    inl_Item_InitSpawnCommonFields_unfused(
        ctx,
        spawn,
        null::<HSD_GObj<'a>>(ctx),
        facing_dir,
        1_i32,
    );
    gobj = fns::Item_80268B18(ctx, spawn);
    if !Handle::is_null(gobj) {
        fns::it_3F14_Logic17_Spawned(ctx, gobj);
        fns::it_8028F434(ctx, gobj, decel, ref_gobj);
        return gobj;
    }
    return null::<HSD_GObj<'a>>(ctx);
}

pub fn it_8028EC98<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, vel: f64) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut vel = vel;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (ip).xDD4_itemVar().freeze().set_x10(vel);
    fns::it_80275158(
        ctx,
        gobj,
        fp::frsp((fns::it_804D6D28(ctx).get()).x30_lifetime() as f64),
    );
}

pub fn it_8028ECE0<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)))
        .xDD4_itemVar()
        .freeze()
        .set_unk_1C(null::<HSD_GObj<'a>>(ctx));
}

pub fn it_8028ECF0<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, v: Vec<'a>) -> Item<'a> {
    let mut gobj = gobj;
    let mut v = v;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (v).set_x((ip).pos().x());
    (v).set_y((ip).pos().y());
    (v).set_z((ip).pos().z());
    return ip;
}

pub fn itFreeze_Logic17_Destroyed<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !Handle::is_null((ip).xDD4_itemVar().freeze().unk_1C()) {
        fns::it_802E37A4(ctx, (ip).xDD4_itemVar().freeze().unk_1C());
        (ip).xDD4_itemVar()
            .freeze()
            .set_unk_1C(null::<HSD_GObj<'a>>(ctx));
    }
}

pub fn it_3F14_Logic17_Spawned<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if (ip).pos().x() > 0.0 {
        (ip).set_facing_dir(fp::fneg(1.0));
    } else {
        (ip).set_facing_dir(1.0);
    }
    (ip).set_xD5C((0_i32 as u32));
    (ip).xDD4_itemVar().freeze().set_x0(0.0);
    (ip).xDD4_itemVar().freeze().x4().set_x(0.0);
    (ip).xDD4_itemVar().freeze().x4().set_y(1.0);
    (ip).xDD4_itemVar().freeze().x4().set_z(0.0);
    (ip).xDD4_itemVar()
        .freeze()
        .set_unk_1C(null::<HSD_GObj<'a>>(ctx));
    fns::it_8028F1D8(ctx, gobj);
}

pub fn it_8028EDBC<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData(ctx, gobj)));
    let mut attrs: itUnkAttributes<'a> =
        Handle::cast::<itUnkAttributes<'a>>(((ip).xC4_article_data()).x4_specialAttributes());
    if ((ip).ground_or_air() as u32) != ((enums::GA_Air as i32) as u32) {
        if (if ((ip).xDD4_itemVar().freeze().x4().x()) < fp::frsp(0_i32 as f64) {
            fp::fneg(((ip).xDD4_itemVar().freeze().x4().x()))
        } else {
            ((ip).xDD4_itemVar().freeze().x4().x())
        }) > 0.10000000149011612
        {
            if (ip).xDD4_itemVar().freeze().x0() == 0.0 {
                if (ip).xDD4_itemVar().freeze().x4().x() > 0.0 {
                    (ip).set_facing_dir(1.0);
                } else {
                    (ip).set_facing_dir(fp::fneg(1.0));
                }
                (ip).xDD4_itemVar()
                    .freeze()
                    .set_x0(fp::fmuls((attrs).x4_float(), (ip).facing_dir()));
            } else {
                (ip).xDD4_itemVar().freeze().set_x0(fp::fmadds(
                    (ip).xDD4_itemVar().freeze().x4().x(),
                    (attrs).xC(),
                    (ip).xDD4_itemVar().freeze().x0(),
                ));
            }
        } else {
            if (if ((ip).xDD4_itemVar().freeze().x0()) < fp::frsp(0_i32 as f64) {
                fp::fneg(((ip).xDD4_itemVar().freeze().x0()))
            } else {
                ((ip).xDD4_itemVar().freeze().x0())
            }) < (attrs).x4_float()
            {
                (ip).xDD4_itemVar()
                    .freeze()
                    .set_x0(fp::fmuls((attrs).x4_float(), (ip).facing_dir()));
            } else if (ip).xDD4_itemVar().freeze().x0() > 0.0 {
                (ip).xDD4_itemVar()
                    .freeze()
                    .set_x0(fp::fsubs((ip).xDD4_itemVar().freeze().x0(), (attrs).x10()));
            } else {
                (ip).xDD4_itemVar()
                    .freeze()
                    .set_x0(fp::fadds((ip).xDD4_itemVar().freeze().x0(), (attrs).x10()));
            }
        }
        if (ip).xDD4_itemVar().freeze().x0() > (attrs).x8() {
            (ip).xDD4_itemVar().freeze().set_x0((attrs).x8());
        } else if (ip).xDD4_itemVar().freeze().x0() < fp::fneg((attrs).x8()) {
            (ip).xDD4_itemVar().freeze().set_x0(fp::fneg((attrs).x8()));
        }
        if (((ip).xDD4_itemVar().freeze().x0() > 0.0) && ((ip).facing_dir() < 0.0))
            || (((ip).xDD4_itemVar().freeze().x0() < 0.0) && ((ip).facing_dir() > 0.0))
        {
            (ip).set_facing_dir(fp::fmuls((ip).facing_dir(), fp::fneg(1.0)));
        }
        (ip).x40_vel().set_x(fp::fmuls(
            (ip).xDD4_itemVar().freeze().x0(),
            (ip).xDD4_itemVar().freeze().x4().y(),
        ));
    }
}

pub fn it_8028EF34<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    (ip).x40_vel().set_x((ip).xDD4_itemVar().freeze().x0());
    (ip).x40_vel().set_z(0.0);
    (ip).x40_vel().set_y(0.0);
    fns::it_8026B390(ctx, gobj);
    fns::Item_80268E5C(ctx, gobj, 0_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itFreeze_UnkMotion0_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itFreeze_UnkMotion0_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::it_8028EDBC(ctx, gobj);
}

pub fn itFreeze_UnkMotion0_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x30);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut jobj: HSD_JObj<'a> =
        (Handle::cast::<HSD_JObj<'a>>(inl_HSD_GObjGetHSDObj_unfused(ctx, gobj)));
    let mut cd: CollData<'a> = (ip).x378_itemColl();
    fns::it_8026D62C(ctx, gobj, fnptr(ctx, 0x8028f1d8));
    if ((ip).ground_or_air() as u32) != ((enums::GA_Air as i32) as u32) {
        if (((cd).env_flags() & 0x18000_i32) != 0) {
            fns::it_80276408(ctx, gobj, cd, (ip).xDD4_itemVar().freeze().x4());
        } else {
            (ip).xDD4_itemVar().freeze().x4().set_x(0.0);
        }
        {
            let mut env: i32 = (cd).env_flags();
            if ((env & 63_i32) != 0) || ((env & 0xfc0_i32) != 0) {
                (ip).set_facing_dir(fp::fneg((ip).facing_dir()));
                (ip).xDD4_itemVar()
                    .freeze()
                    .set_x0(fp::fneg((ip).xDD4_itemVar().freeze().x0()));
                (ip).x40_vel().set_x(fp::fmuls(
                    (ip).xDD4_itemVar().freeze().x0(),
                    (ip).xDD4_itemVar().freeze().x4().y(),
                ));
            }
        }
        if (ip).facing_dir() == fp::fneg(1.0) {
            inl_HSD_JObjSetRotationZ_unfused(ctx, jobj, fns::it_8027649C(ctx, gobj));
        } else {
            inl_HSD_JObjSetRotationZ_unfused_2(
                ctx,
                jobj,
                fp::fneg(1.0),
                fns::it_8027649C(ctx, gobj),
            );
        }
    }
    return 0_i32;
}

pub fn it_8028F1D8<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 1_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itFreeze_UnkMotion3_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itFreeze_UnkMotion1_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut attrs: ItemAttr<'a> = (ip).xCC_item_attr();
    fns::it_80272860(
        ctx,
        gobj,
        (attrs).x10_fall_speed(),
        (attrs).x14_fall_speed_max(),
    );
}

pub fn itFreeze_UnkMotion1_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut it: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut cd: CollData<'a> = (it).x378_itemColl();
    fns::it_8026E414(ctx, gobj, fnptr(ctx, 0x8028ef34));
    if (((it).ground_or_air() as u32) != ((enums::GA_Air as i32) as u32))
        && (((cd).env_flags() & (0x8000_i32 | 0x10000_i32)) != 0)
    {
        fns::it_80276408(ctx, gobj, cd, (it).xDD4_itemVar().freeze().x4());
    }
    return 0_i32;
}

pub fn itFreeze_Logic17_PickedUp<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut item: Item<'a> = Handle::cast::<Item<'a>>((gobj).user_data());
    let mut linked: HSD_GObj<'a> = null(ctx);
    if !Handle::is_null(
        ({
            let __t1 = (item).xDD4_itemVar().freeze().unk_1C();
            linked = __t1;
            __t1
        }),
    ) {
        fns::it_802E37A4(ctx, linked);
        (item)
            .xDD4_itemVar()
            .freeze()
            .set_unk_1C(null::<HSD_GObj<'a>>(ctx));
    }
    fns::Item_80268E5C(ctx, gobj, 2_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itFreeze_UnkMotion2_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itFreeze_Logic17_Dropped<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 1_i32, 6_i32);
}

pub fn itFreeze_Logic17_Thrown<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 3_i32, 6_i32);
}

pub fn itFreeze_UnkMotion3_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ip: Item<'a> = null(ctx);
    let mut it_attr: ItemAttr<'a> = null(ctx);
    ip = Handle::cast::<Item<'a>>((gobj).user_data());
    it_attr = (ip).xCC_item_attr();
    fns::it_80272860(
        ctx,
        gobj,
        (it_attr).x10_fall_speed(),
        (it_attr).x14_fall_speed_max(),
    );
}

pub fn itFreeze_UnkMotion3_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    if fns::it_8026DAA8(ctx, gobj) != 0_i32 {
        return 1_i32;
    }
    return 0_i32;
}

pub fn itFreeze_Logic17_DmgDealt<'a>(ctx: &'a Ctx, arg0: HSD_GObj<'a>) -> i32 {
    let mut arg0 = arg0;
    return 1_i32;
}

pub fn itFreeze_Logic17_Clanked<'a>(ctx: &'a Ctx, arg0: HSD_GObj<'a>) -> i32 {
    let mut arg0 = arg0;
    return 1_i32;
}

pub fn itFreeze_Logic17_HitShield<'a>(ctx: &'a Ctx, arg0: HSD_GObj<'a>) -> i32 {
    let mut arg0 = arg0;
    return 1_i32;
}

pub fn itFreeze_Logic17_Absorbed<'a>(ctx: &'a Ctx, arg0: HSD_GObj<'a>) -> i32 {
    let mut arg0 = arg0;
    return 1_i32;
}

pub fn itFreeze_Logic17_Reflected<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    return fns::it_80273030(ctx, gobj);
}

pub fn itFreeze_Logic17_ShieldBounced<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    return fns::itColl_BounceOffShield(ctx, gobj);
}

pub fn itFreeze_Logic17_DmgReceived<'a>(ctx: &'a Ctx, arg0: HSD_GObj<'a>) -> i32 {
    let mut arg0 = arg0;
    return 1_i32;
}

pub fn it_8028F434<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, vel: f64, ref_gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut vel = vel;
    let mut ref_gobj = ref_gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    inl_itResetVelocity_unfused(ctx, ip);
    if vel < 0.0 {
        vel = fp::fneg(vel);
    }
    (ip).xDD4_itemVar().freeze().set_x14(vel);
    (ip).xDD4_itemVar().freeze().set_unk_1C(ref_gobj);
    fns::it_8026B390(ctx, gobj);
    fns::it_802762B0(ctx, ip);
    fns::Item_80268E5C(ctx, gobj, 4_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itFreeze_UnkMotion4_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itFreeze_UnkMotion4_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut decel: f64 = 0.0;
    let mut abs_decel: f64 = 0.0;
    let mut vel: f64 = 0.0;
    let mut abs_vel: f64 = 0.0;
    {
        let mut x10: f64 = (ip).xDD4_itemVar().freeze().x10();
        if (x10 != 0.0) {
            (ip).x40_vel().set_x(x10);
            (ip).xDD4_itemVar().freeze().set_x10(fp::fmuls(0.0, 0.0));
        }
    }
    decel = (ip).xDD4_itemVar().freeze().x14();
    abs_decel = (if (decel) < fp::frsp(0_i32 as f64) {
        fp::fneg((decel))
    } else {
        (decel)
    });
    vel = (ip).x40_vel().x();
    abs_vel = (if (vel) < fp::frsp(0_i32 as f64) {
        fp::fneg((vel))
    } else {
        (vel)
    });
    if abs_vel < abs_decel {
        (ip).x40_vel().set_x(0.0);
        return;
    }
    if vel > 0.0 {
        if (ip).xDD4_itemVar().freeze().x14() < 0.0 {
            decel = fp::fneg(decel);
        }
        (ip).x40_vel().set_x(fp::fsubs((ip).x40_vel().x(), decel));
    } else {
        if decel < 0.0 {
            decel = fp::fneg(decel);
        }
        (ip).x40_vel().set_x(fp::fadds((ip).x40_vel().x(), decel));
    }
}

pub fn itFreeze_UnkMotion4_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x40);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut jobj: HSD_JObj<'a> =
        (Handle::cast::<HSD_JObj<'a>>(inl_HSD_GObjGetHSDObj_unfused(ctx, gobj)));
    let mut cd: CollData<'a> = (ip).x378_itemColl();
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    fns::it_8026D62C(ctx, gobj, fnptr(ctx, 0x8028f1d8));
    if ((ip).ground_or_air() as u32) == ((enums::GA_Air as i32) as u32) {
        inl_itFreeze_ClearLinkedItem_unfused(ctx, gobj);
    } else {
        let mut env: i32 = (cd).env_flags();
        if ((env & 63_i32) != 0) || ((env & 0xfc0_i32) != 0) {
            fns::it_8028F7C8(ctx, gobj);
            inl_itFreeze_ClearLinkedItem_unfused(ctx, gobj);
            return 0_i32;
        }
        if Handle::is_null((ip).xDD4_itemVar().freeze().unk_1C()) {
            inl_itFreeze_ResetToMotion0_unfused(ctx, gobj);
            return 0_i32;
        }
        if (ip).facing_dir() == fp::fneg(1.0) {
            inl_HSD_JObjSetRotationZ_unfused(ctx, jobj, fns::it_8027649C(ctx, gobj));
        } else {
            inl_HSD_JObjSetRotationZ_unfused_2(
                ctx,
                jobj,
                fp::fneg(1.0),
                fns::it_8027649C(ctx, gobj),
            );
        }
    }
    return 0_i32;
}

pub fn it_8028F7C8<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    inl_itResetVelocity_unfused(ctx, ip);
    fns::it_8026B390(ctx, gobj);
    (ip).xDD4_itemVar().freeze().set_x18(90_i32);
    fns::Item_80268E5C(ctx, gobj, 5_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn itFreeze_UnkMotion5_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    return 0_i32;
}

pub fn itFreeze_UnkMotion5_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
}

pub fn itFreeze_UnkMotion5_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    fns::it_8026D62C(ctx, gobj, fnptr(ctx, 0x8028f1d8));
    if (ip).xDD4_itemVar().freeze().x18() <= 0_i32 {
        let mut ip2: Item<'a> =
            (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
        (ip2).x40_vel().set_x((ip2).xDD4_itemVar().freeze().x0());
        (ip2).x40_vel().set_z(0.0);
        (ip2).x40_vel().set_y(0.0);
        fns::it_8026B390(ctx, gobj);
        fns::Item_80268E5C(ctx, gobj, 0_i32, (enums::ITEM_ANIM_UPDATE as i32));
    } else {
        (ip).xDD4_itemVar()
            .freeze()
            .set_x18((ip).xDD4_itemVar().freeze().x18().wrapping_sub(1));
    }
    return 0_i32;
}

pub fn itFreeze_Logic17_EvtUnk<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, ref_gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ref_gobj = ref_gobj;
    let _ = fns::it_8026B894(ctx, gobj, ref_gobj);
}

pub fn it_8028F8E4<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let pos: Vec<'a> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (ip).xDCC_flag().set_b3((1_i32 as u8));
    fns::it_8026B390(ctx, gobj);
    Handle::copy_from((ip).x378_itemColl().cur_pos(), (ip).pos());
    Handle::copy_from(pos, (ip).pos());
    fns::it_80276100(ctx, gobj, pos);
}

pub fn it_8028F968<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    fns::it_80273454(ctx, gobj);
    (ip).xDCC_flag().set_b3((0_i32 as u8));
    fns::it_8026B3A8(ctx, gobj);
}

pub fn it_8028F9B8<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_8026A8EC(ctx, gobj);
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_Item_InitSpawnCommonFields_unfused<'a>(
    ctx: &'a Ctx,
    spawn: SpawnItem<'a>,
    parent: HSD_GObj<'a>,
    facing_dir: f64,
    initial_collision: i32,
) {
    let mut spawn = spawn;
    let mut parent = parent;
    let mut facing_dir = facing_dir;
    let mut initial_collision = initial_collision;
    (spawn).set_facing_dir(facing_dir);
    (spawn).set_x3C_damage((0_i32 as i16));
    (spawn).vel().set_x({
        let __t2 = {
            let __t1 = 0.0;
            (spawn).vel().set_z(__t1);
            __t1
        };
        (spawn).vel().set_y(__t2);
        __t2
    });
    (spawn).set_x0_parent_gobj(parent);
    (spawn).set_x4_parent_gobj2((spawn).x0_parent_gobj());
    (spawn).x44_flag().x0().set_b0((initial_collision as u8));
    (spawn).set_x40(0_i32);
}

fn inl_HSD_GObjGetUserData<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_HSD_GObjGetHSDObj_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).hsd_obj();
}

fn inl_HSD_JObjMtxIsDirty_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>) -> i32 {
    let mut jobj = jobj;
    let mut result: i32 = 0;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x803f5d28),
            (228_i32 as u32),
            cstr(ctx, 0x803f5d28),
        )
    });
    result = 0_i32;
    if (!(((jobj).flags() & ((shl_i32(1_i32, (23_i32 as u32))) as u32)) != 0))
        && (((jobj).flags() & ((shl_i32(1_i32, (6_i32 as u32))) as u32)) != 0)
    {
        result = 1_i32;
    }
    return result;
}

fn inl_HSD_JObjSetRotationZ_unfused<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>, z: f64) {
    let mut jobj = jobj;
    let mut z = z;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x803f5d28),
            (0x151_i32 as u32),
            cstr(ctx, 0x803f5d28),
        )
    });
    (if !(((jobj).flags() & ((shl_i32(1_i32, (17_i32 as u32))) as u32)) != 0) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x803f5d28),
            (0x152_i32 as u32),
            cstr(ctx, 0x803f5d28),
        )
    });
    (jobj).rotate().set_z(z);
    if !(((jobj).flags() & ((shl_i32(1_i32, (25_i32 as u32))) as u32)) != 0) {
        {
            if (!Handle::is_null(jobj)) && (!(inl_HSD_JObjMtxIsDirty_unfused(ctx, jobj) != 0)) {
                fns::HSD_JObjSetMtxDirtySub(ctx, jobj);
            }
        }
    }
}

fn inl_HSD_JObjSetRotationZ_unfused_2<'a>(ctx: &'a Ctx, jobj: HSD_JObj<'a>, z__a: f64, z__c: f64) {
    let mut jobj = jobj;
    (if !Handle::is_null((jobj)) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x803f5d28),
            (0x151_i32 as u32),
            cstr(ctx, 0x803f5d28),
        )
    });
    (if !(((jobj).flags() & ((shl_i32(1_i32, (17_i32 as u32))) as u32)) != 0) {
        ({ () })
    } else {
        fns::__assert(
            ctx,
            cstr(ctx, 0x803f5d28),
            (0x152_i32 as u32),
            cstr(ctx, 0x803f5d28),
        )
    });
    (jobj).rotate().set_z(fp::fmuls(z__a, z__c));
    if !(((jobj).flags() & ((shl_i32(1_i32, (25_i32 as u32))) as u32)) != 0) {
        {
            if (!Handle::is_null(jobj)) && (!(inl_HSD_JObjMtxIsDirty_unfused(ctx, jobj) != 0)) {
                fns::HSD_JObjSetMtxDirtySub(ctx, jobj);
            }
        }
    }
}

fn inl_itResetVelocity_unfused<'a>(ctx: &'a Ctx, ip: Item<'a>) {
    let mut ip = ip;
    (ip).x40_vel().set_x({
        let __t2 = {
            let __t1 = 0.0;
            (ip).x40_vel().set_z(__t1);
            __t1
        };
        (ip).x40_vel().set_y(__t2);
        __t2
    });
}

fn inl_itFreeze_ClearLinkedItem_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut linked: HSD_GObj<'a> = (ip).xDD4_itemVar().freeze().unk_1C();
    if !Handle::is_null(linked) {
        fns::it_802E37A4(ctx, linked);
        (ip).xDD4_itemVar()
            .freeze()
            .set_unk_1C(null::<HSD_GObj<'a>>(ctx));
    }
}

fn inl_itFreeze_ResetToMotion0_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ip: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (ip).x40_vel().set_x((ip).xDD4_itemVar().freeze().x0());
    (ip).x40_vel().set_z(0.0);
    (ip).x40_vel().set_y(0.0);
    fns::it_8026B390(ctx, gobj);
    fns::Item_80268E5C(ctx, gobj, 0_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x8028eb88,
        |ctx| {
            let (a0, a1, a2, a3): (HSD_GObj<'_>, Vec<'_>, Single, Single) = Args::take_all(ctx);
            Ret::put(it_8028EB88(ctx, a0, a1, a2.0, a3.0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028ec98,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, Single) = Args::take_all(ctx);
            Ret::put(it_8028EC98(ctx, a0, a1.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028ece0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028ECE0(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028ecf0,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, Vec<'_>) = Args::take_all(ctx);
            Ret::put(it_8028ECF0(ctx, a0, a1), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028ed10,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Destroyed(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028ed50,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_3F14_Logic17_Spawned(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028edbc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028EDBC(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028ef34,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028EF34(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028ef88,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion0_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028ef90,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion0_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028efb0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion0_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f1d8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028F1D8(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f200,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion3_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f208,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion1_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f238,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion1_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f2b4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_PickedUp(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f310,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion2_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f318,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Dropped(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f340,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Thrown(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f368,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion3_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f398,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion3_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f3cc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_DmgDealt(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f3d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Clanked(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f3dc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_HitShield(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f3e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Absorbed(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f3ec,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_Reflected(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f40c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_ShieldBounced(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f42c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_DmgReceived(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f434,
        |ctx| {
            let (a0, a1, a2): (HSD_GObj<'_>, Single, HSD_GObj<'_>) = Args::take_all(ctx);
            Ret::put(it_8028F434(ctx, a0, a1.0, a2), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f4ac,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion4_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f4b4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion4_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f560,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion4_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f7c8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028F7C8(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f828,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion5_Anim(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f830,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion5_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f834,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itFreeze_UnkMotion5_Coll(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8028f8c4,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, HSD_GObj<'_>) = Args::take_all(ctx);
            Ret::put(itFreeze_Logic17_EvtUnk(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f8e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028F8E4(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f968,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028F968(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8028f9b8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_8028F9B8(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
