// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftCommon/ftCo_Pass.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftCommon/ftCo_Pass
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn ftCo_80099F1C<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if (((fp).input().lstick().get(0_i32).y() <= fp::fneg((fns::p_ftCommonData(ctx).get()).x464()))
        && (fp::frsp(((fp).active_timer().lstick().y() as i32) as f64)
            < (fns::p_ftCommonData(ctx).get()).x468()))
        && (fns::mpColl_IsOnPlatform(ctx, (fp).coll_data()) != 0)
    {
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftCo_80099F9C<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if (fns::ftCo_800C5240(ctx, gobj) != 0) {
        return fns::ftCo_800C60C8(ctx, gobj);
    }
    if (!((fp).mv().co().pass().x0() != 0)) && (inl_ftCo_80099F1C_unfused(ctx, gobj) != 0) {
        (fp).mv().co().pass().set_x0(1_i32);
        (fp).mv()
            .co()
            .pass()
            .set_x4((fns::p_ftCommonData(ctx).get()).x470());
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftCo_8009A080<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if (((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (31_i32 as u32))) as u32))
        != 0)
        && (inl_ftCo_80099F1C_unfused(ctx, gobj) != 0)
    {
        fns::ftCo_8009A228(ctx, gobj);
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftCo_8009A134<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    let mut coll: CollData<'a> = (fp).coll_data();
    if (fns::mpColl_IsOnPlatform(ctx, coll) != 0) {
        fns::mpUpdateFloorSkip(ctx, coll);
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftCo_8009A184<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, msid: i32, mf: u32, anim_start: f64) {
    let __frame = ctx.stack_frame(0x38);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut msid = msid;
    let mut mf = mf;
    let mut anim_start = anim_start;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    fns::ftCommon_8007D5D4(ctx, fp);
    fns::ftCommon_ClampAirDrift(ctx, fp);
    (fp).self_vel()
        .set_y((fns::p_ftCommonData(ctx).get()).x46C());
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        msid,
        mf,
        anim_start,
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::mpUpdateFloorSkip(ctx, (fp).coll_data());
    (fp).active_timer().lstick().set_y((254_i32 as u8));
}

pub fn ftCo_8009A228<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    ctx.fill(Handle::addr(unused), 0, 0x8);
    unused.at(0).set((0_i32 as u8));
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    fns::ftCommon_8007D5D4(ctx, fp);
    fns::ftCommon_ClampAirDrift(ctx, fp);
    (fp).self_vel()
        .set_y((fns::p_ftCommonData(ctx).get()).x46C());
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftCo_MS_Pass as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::mpUpdateFloorSkip(ctx, (fp).coll_data());
    (fp).active_timer().lstick().set_y((254_i32 as u8));
}

pub fn ftCo_Pass_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCo_Fall_Enter(ctx, gobj);
    }
}

pub fn ftCo_Pass_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    'l1: loop {
        'c2: {
            if ((fns::ftCo_SpecialAir_CheckInput(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    'l3: loop {
        'c4: {
            if ((fns::ftCo_80095328(ctx, gobj, null::<Val<'a, i32>>(ctx))) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l3;
        }
    }
    'l5: loop {
        'c6: {
            if ((fns::ftCo_800D7100(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l5;
        }
    }
    'l7: loop {
        'c8: {
            if ((fns::ftCo_800C3B10(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l7;
        }
    }
    'l9: loop {
        'c10: {
            if ((fns::ftCo_80099A58(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l9;
        }
    }
    'l11: loop {
        'c12: {
            if ((fns::ftCo_AttackAir_CheckItemThrowInput(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l11;
        }
    }
    'l13: loop {
        'c14: {
            if ((fns::ftCo_800D705C(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l13;
        }
    }
    'l15: loop {
        'c16: {
            if ((fns::ftCo_800CB870(ctx, gobj)) != 0) {
                return;
            }
        }
        if !(0_i32 != 0) {
            break 'l15;
        }
    }
}

pub fn ftCo_Pass_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084DB0(ctx, gobj);
}

pub fn ftCo_Pass_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80082F28(ctx, gobj);
}

fn inl_ftCo_80099F1C_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if (((fp).input().lstick().get(0_i32).y() <= fp::fneg((fns::p_ftCommonData(ctx).get()).x464()))
        && (fp::frsp(((fp).active_timer().lstick().y() as i32) as f64)
            < (fns::p_ftCommonData(ctx).get()).x468()))
        && (fns::mpColl_IsOnPlatform(ctx, (fp).coll_data()) != 0)
    {
        return 1_i32;
    }
    return 0_i32;
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x80099f1c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_80099F1C(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80099f9c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_80099F9C(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8009a080,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_8009A080(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8009a134,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_8009A134(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x8009a184,
        |ctx| {
            let (a0, a1, a2, a3): (HSD_GObj<'_>, i32, u32, Single) = Args::take_all(ctx);
            Ret::put(ftCo_8009A184(ctx, a0, a1, a2, a3.0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8009a228,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_8009A228(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8009a2a8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_Pass_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8009a2e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_Pass_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8009a388,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_Pass_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x8009a3a8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftCo_Pass_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
