// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/it/kinds/itkirbyhammer.c. Do not edit; fix the translator or port by hand.
// unit: melee/it/kinds/itkirbyhammer
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn itKirbyHammer_Logic8_Destroyed<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut it: Item<'a> = (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if Handle::is_null((it).owner()) {
        return;
    }
    fns::ftKb_SpecialAirLw_800F539C(ctx, (it).owner());
}

pub fn it_802ADC34<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_8026A8EC(ctx, gobj);
}

pub fn it_802ADC54<'a>(
    ctx: &'a Ctx,
    parent: HSD_GObj<'a>,
    pos: Vec<'a>,
    sfx: i32,
    vars: u32,
    dir: f64,
) -> HSD_GObj<'a> {
    let __frame = ctx.stack_frame(0x98);
    let spawn: SpawnItem<'a> = frame_at(ctx, &__frame, 0x28);
    let unused: ArrV<'a, u8, 12> = frame_at(ctx, &__frame, 0x0);
    let mut parent = parent;
    let mut pos = pos;
    let mut sfx = sfx;
    let mut vars = vars;
    let mut dir = dir;
    let mut item_gobj: HSD_GObj<'a> = null(ctx);
    'l1: loop {
        'c2: {}
        if !(0_i32 != 0) {
            break 'l1;
        }
    }
    spawn.set_kind((enums::It_Kind_Kirby_Hammer as i32));
    Handle::copy_from(spawn.prev_pos(), (pos));
    fns::it_8026BB68(ctx, parent, spawn.pos());
    inl_Item_InitSpawnCommonFields_unfused(ctx, spawn, parent, dir, 1_i32);
    item_gobj = fns::Item_80268B18(ctx, spawn);
    if !Handle::is_null(item_gobj) {
        inl_setupHammerParticles_unfused(ctx, parent, item_gobj, sfx, vars);
    }
    return item_gobj;
}

pub fn itKirbyHammer_Logic8_PickedUp<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Item_80268E5C(ctx, gobj, 0_i32, (enums::ITEM_ANIM_UPDATE as i32));
}

pub fn it_802ADDB0<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, ref_gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut ref_gobj = ref_gobj;
    let _ = fns::it_8026B894(ctx, gobj, ref_gobj);
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_Item_InitSpawnCommonFields_unfused<'a>(
    ctx: &'a Ctx,
    spawn: SpawnItem<'a>,
    parent: HSD_GObj<'a>,
    facing_dir: f64,
    initial_collision: i32,
) {
    let mut spawn = spawn;
    let mut parent = parent;
    let mut facing_dir = facing_dir;
    let mut initial_collision = initial_collision;
    (spawn).set_facing_dir(facing_dir);
    (spawn).set_x3C_damage((0_i32 as i16));
    (spawn).vel().set_x({
        let __t2 = {
            let __t1 = 0.0;
            (spawn).vel().set_z(__t1);
            __t1
        };
        (spawn).vel().set_y(__t2);
        __t2
    });
    (spawn).set_x0_parent_gobj(parent);
    (spawn).set_x4_parent_gobj2((spawn).x0_parent_gobj());
    (spawn).x44_flag().x0().set_b0((initial_collision as u8));
    (spawn).set_x40(0_i32);
}

fn inl_setupHammerParticles_unfused<'a>(
    ctx: &'a Ctx,
    parent: HSD_GObj<'a>,
    item_gobj: HSD_GObj<'a>,
    sfx: i32,
    vars: u32,
) {
    let mut parent = parent;
    let mut item_gobj = item_gobj;
    let mut sfx = sfx;
    let mut vars = vars;
    let mut jobj: HSD_JObj<'a> = null(ctx);
    let mut particle_id: u32 = 0;
    let mut it: Item<'a> =
        (Handle::cast::<Item<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, item_gobj)));
    (it).xDD4_itemVar().kirbyhammer().set_x0(vars);
    fns::db_80225DD8(ctx, item_gobj, parent);
    fns::Item_8026AB54(ctx, item_gobj, parent, sfx);
    if (Handle::cast::<Item<'a>>((item_gobj).user_data()))
        .xDD4_itemVar()
        .kirbyhammer()
        .x0()
        == (1_i32 as u32)
    {
        particle_id = (0x499_i32 as u32);
    } else {
        particle_id = (0x498_i32 as u32);
    }
    jobj = fns::it_80272C90(ctx, item_gobj);
    fns::efAsync_Spawn(
        ctx,
        item_gobj,
        (Handle::cast::<Item<'a>>((item_gobj).user_data())).xBC0_ref(),
        (0_i32 as u32),
        particle_id,
        jobj,
        &[],
    );
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x802adc04,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itKirbyHammer_Logic8_Destroyed(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802adc34,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(it_802ADC34(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802adc54,
        |ctx| {
            let (a0, a1, a2, a3, a4): (HSD_GObj<'_>, Vec<'_>, i32, u32, Single) =
                Args::take_all(ctx);
            Ret::put(it_802ADC54(ctx, a0, a1, a2, a3, a4.0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x802add88,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(itKirbyHammer_Logic8_PickedUp(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x802addb0,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, HSD_GObj<'_>) = Args::take_all(ctx);
            Ret::put(it_802ADDB0(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
}
