// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/melee/ft/kinds/ftFox/ftfoxspeciallw.c. Do not edit; fix the translator or port by hand.
// unit: melee/ft/kinds/ftFox/ftfoxspeciallw
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn ftFx_SpecialLw_CreateLoopGFX<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if ((fp).x2219_b0() as i32) == 0_i32 {
        let _ = fns::efSync_Spawn(
            ctx,
            0x488_i32,
            gobj,
            &[VarArg::Int(Handle::addr(
                (Handle::add((fp).parts(), (enums::FtPart_HipN as i32))).joint(),
            ))],
        );
        (fp).set_x2219_b0((1_i32 as u8));
    }
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
}

pub fn ftFx_SpecialLw_CreateStartGFX<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if ((fp).x2219_b0() as i32) == 0_i32 {
        let _ = fns::efSync_Spawn(
            ctx,
            0x489_i32,
            gobj,
            &[VarArg::Int(Handle::addr(
                (Handle::add((fp).parts(), (enums::FtPart_HipN as i32))).joint(),
            ))],
        );
        (fp).set_x2219_b0((1_i32 as u8));
    }
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
}

pub fn ftFx_SpecialLw_CreateReflectGFX<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if ((fp).x2219_b0() as i32) == 0_i32 {
        let _ = fns::efSync_Spawn(
            ctx,
            0x48a_i32,
            gobj,
            &[VarArg::Int(Handle::addr(
                (Handle::add((fp).parts(), (enums::FtPart_HipN as i32))).joint(),
            ))],
        );
        (fp).set_x2219_b0((1_i32 as u8));
        (fp).set_x2219_b0((1_i32 as u8));
    }
    inl_Fighter_SetEffectHitlagCallbacks_unfused(ctx, fp);
    (fp).set_accessory4_cb(null::<FnPtr<'a>>(ctx));
}

pub fn ftFx_SpecialLw_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x38);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialLwStart as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::ftAnim_8006EBA4(ctx, gobj);
    inl_ftFox_SpecialLw_SetVars_unfused(ctx, gobj);
}

pub fn ftFx_SpecialAirLw_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x38);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftFox_DatAttrs<'a> = Handle::cast::<ftFox_DatAttrs<'a>>((fp).dat_attrs());
    (fp).self_vel().set_y(fp::frsp(0_i32 as f64));
    (fp).self_vel().set_x(fp::fdivs(
        (fp).self_vel().x(),
        (da).xA8_FOX_REFLECTOR_MOMENTUM_PRESERVE_X(),
    ));
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwStart as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::ftAnim_8006EBA4(ctx, gobj);
    inl_ftFox_SpecialLw_SetVars_unfused(ctx, gobj);
}

pub fn ftFx_SpecialLwStart_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        == (0_i32 as u32)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_Enter(ctx, gobj);
        } else {
            statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialAirLwLoop_Enter(
                ctx, gobj,
            );
        }
        fns::ftCommon_8007DB24(ctx, gobj);
        (fp).set_accessory4_cb(fnptr(ctx, 0x800e83e0));
    }
}

pub fn ftFx_SpecialAirLwStart_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !(((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        != 0)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_Enter(ctx, gobj);
        } else {
            statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialAirLwLoop_Enter(
                ctx, gobj,
            );
        }
        fns::ftCommon_8007DB24(ctx, gobj);
        (fp).set_accessory4_cb(fnptr(ctx, 0x800e83e0));
    }
}

pub fn ftFx_SpecialLwStart_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    if (fns::ftFx_SpecialLwStart_CheckPass(ctx, gobj) != 0) {
        return;
    }
}

pub fn ftFx_SpecialAirLwStart_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialLwStart_CheckPass<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if fns::ftCo_80099F1C(ctx, gobj) != 0_i32 {
        fns::ftFx_SpecialLwStart_Pass(ctx, gobj);
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftFx_SpecialLwStart_Pass<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    fns::ftCo_8009A184(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwStart as i32),
        0xc4c5082_u32,
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj))).cur_anim_frame(),
    );
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialLwStart_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
}

pub fn ftFx_SpecialAirLwStart_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    let mut ca: ftCo_DatAttrs<'a> = (fp).co_attrs();
    let mut da: ftFox_DatAttrs<'a> = Handle::cast::<ftFox_DatAttrs<'a>>((fp).dat_attrs());
    if (fp).mv().fx().SpecialLw().gravityDelay() != 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_gravityDelay((fp).mv().fx().SpecialLw().gravityDelay().wrapping_sub(1));
    } else {
        fns::ftCommon_Fall(
            ctx,
            fp,
            (da).xAC_FOX_REFLECTOR_FALL_ACCEL(),
            (ca).terminal_velocity(),
        );
    }
    let _ = fns::ftCommon_CalcSelfAccel_DeaccelQuickAir(ctx, fp);
}

pub fn ftFx_SpecialLwStart_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80082708(ctx, gobj) as u32) == (0_i32 as u32) {
        fns::ftFx_SpecialLwStart_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwStart_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) as u32) != (0_i32 as u32) {
        fns::ftFx_SpecialAirLwStart_AirToGround(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwStart_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_ftCommon_GroundToAirStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialAirLwStart as i32),
        0xc4c5082_u32,
    );
}

pub fn ftFx_SpecialAirLwStart_AirToGround<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_ftCommon_AirToGroundStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialLwStart as i32),
        0xc4c5082_u32,
    );
    fns::ftCommon_ClampAirDrift(ctx, fp);
}

pub fn ftFx_SpecialLwLoop_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        == (0_i32 as u32)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if (fp).mv().fx().SpecialLw().releaseLag() > 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_releaseLag((fp).mv().fx().SpecialLw().releaseLag().wrapping_sub(1));
    }
    if ((fp).mv().fx().SpecialLw().releaseLag() <= 0_i32)
        && ((fp).mv().fx().SpecialLw().isRelease() != 0)
    {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            fns::ftFx_SpecialLwEnd_Enter(ctx, gobj);
            return;
        }
        fns::ftFx_SpecialAirLwEnd_Enter(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwLoop_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if ((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        == (0_i32 as u32)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if (fp).mv().fx().SpecialLw().releaseLag() > 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_releaseLag((fp).mv().fx().SpecialLw().releaseLag().wrapping_sub(1));
    }
    if ((fp).mv().fx().SpecialLw().releaseLag() <= 0_i32)
        && ((fp).mv().fx().SpecialLw().isRelease() != 0_i32)
    {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            fns::ftFx_SpecialLwEnd_Enter(ctx, gobj);
            return;
        }
        fns::ftFx_SpecialAirLwEnd_Enter(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwLoop_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ftFx_SpecialLwTurn_Check(ctx, gobj) == 0_i32)
        && (fns::ftCo_Jump_CheckInput(ctx, gobj) == 0_i32)
    {
        if (statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_CheckPass(
            ctx, gobj,
        ) != 0)
        {
            return;
        }
    }
}

pub fn ftFx_SpecialAirLwLoop_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ftFx_SpecialLwTurn_Check(ctx, gobj) == 0_i32) && (fns::ftCo_800CB870(ctx, gobj) != 0) {
        return;
    }
}

pub fn ftFx_SpecialLwLoop_CheckPass<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if fns::ftCo_80099F1C(ctx, gobj) != 0_i32 {
        statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_Pass(ctx, gobj);
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftFx_SpecialLwLoop_Pass<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    fns::ftCo_8009A184(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwLoop as i32),
        0xc4c5082_u32,
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj))).cur_anim_frame(),
    );
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialLwLoop_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialAirLwLoop_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let mut gobj = gobj;
    inl_ftFox_SpecialLw_InlinePhys_unfused(ctx, gobj);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialLwLoop_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80082708(ctx, gobj) as u32) == (0_i32 as u32) {
        statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwLoop_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) as u32) != (0_i32 as u32) {
        statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialAirLwLoop_AirToGround(
            ctx, gobj,
        );
    }
}

pub fn ftFx_SpecialLwLoop_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_ftCommon_GroundToAirStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialAirLwLoop as i32),
        0xc4c5082_u32,
    );
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialAirLwLoop_AirToGround<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    inl_ftCommon_AirToGroundStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialLwLoop as i32),
        0xc4c5082_u32,
    );
    fns::ftCommon_ClampAirDrift(ctx, fp);
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialLw_CreateReflectHit<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    let mut da: ftFox_DatAttrs<'a> =
        Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    fns::ftColl_CreateReflectHit(
        ctx,
        gobj,
        (da).xB0_FOX_REFLECTOR_REFLECTION(),
        fnptr(ctx, 0x800e9a68),
    );
}

pub fn ftFx_SpecialLwLoop_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialLwLoop as i32),
        2_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialAirLwLoop_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwLoop as i32),
        2_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_CreateReflectHit(ctx, gobj);
}

pub fn ftFx_SpecialLw_Turn<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    let mut da: ftFox_DatAttrs<'a> = Handle::cast::<ftFox_DatAttrs<'a>>((fp).dat_attrs());
    (fp).mv()
        .fx()
        .SpecialLw()
        .set_turnFrames((fp).mv().fx().SpecialLw().turnFrames().wrapping_sub(1));
    if ((fp).cmd_vars().at(0_i32).get() == (0_i32 as u32))
        && (fp::frsp((fp).mv().fx().SpecialLw().turnFrames() as f64)
            <= (da).x9C_FOX_REFLECTOR_TURN_FRAMES())
    {
        (fp).cmd_vars().at(0_i32).set((1_i32 as u32));
        (fp).set_facing_dir(fp::fneg((fp).facing_dir()));
    }
    fns::ftPartSetRotY(
        ctx,
        fp,
        0_i32,
        fp::fneg(
            (fp::fmsubs(
                (fp::fdivs(
                    fp::frsp(180_i32 as f64),
                    (da).x9C_FOX_REFLECTOR_TURN_FRAMES(),
                )),
                0.01745329238474369,
                fns::ftPartGetRotZ(ctx, fp, 0_i32),
            )),
        ),
    );
}

pub fn ftFx_SpecialLwTurn_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x38);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData(ctx, gobj)));
    inl_updateRelease(ctx, gobj);
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_Turn(ctx, gobj);
    if (fp).mv().fx().SpecialLw().turnFrames() <= 0_i32 {
        let _ = fns::ftFx_SpecialLwHit_Check(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwTurn_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x40);
    let unused: ArrV<'a, u8, 16> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData(ctx, gobj)));
    inl_updateRelease(ctx, gobj);
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_Turn(ctx, gobj);
    if (fp).mv().fx().SpecialLw().turnFrames() <= 0_i32 {
        let _ = fns::ftFx_SpecialLwHit_Check(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwTurn_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialAirLwTurn_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialLwTurn_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialAirLwTurn_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let unused: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftFox_DatAttrs<'a> =
        Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    let mut ca: ftCo_DatAttrs<'a> = inl_getFtAttrs_unfused(ctx, fp);
    if (fp).mv().fx().SpecialLw().gravityDelay() != 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_gravityDelay((fp).mv().fx().SpecialLw().gravityDelay().wrapping_sub(1));
    } else {
        fns::ftCommon_Fall(
            ctx,
            fp,
            (da).xAC_FOX_REFLECTOR_FALL_ACCEL(),
            (ca).terminal_velocity(),
        );
    }
    let _ = fns::ftCommon_CalcSelfAccel_DeaccelQuickAir(ctx, fp);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialLwTurn_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80082708(ctx, gobj) as u32) == (0_i32 as u32) {
        fns::ftFx_SpecialLwTurn_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwTurn_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) as u32) != (0_i32 as u32) {
        fns::ftFx_SpecialAirLwTurn_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwTurn_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_ftCommon_GroundToAirStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialAirLwTurn as i32),
        0xc4c5082_u32,
    );
    inl_ftFox_SpecialLw_SetReflectVars_unfused(ctx, gobj);
}

pub fn ftFx_SpecialAirLwTurn_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_ftCommon_AirToGroundStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialLwTurn as i32),
        0xc4c5082_u32,
    );
    fns::ftCommon_ClampAirDrift(ctx, fp);
    inl_ftFox_SpecialLw_SetReflectVars_unfused(ctx, gobj);
}

pub fn ftFx_SpecialLwTurn_Check<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x40);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if fns::ftCo_800C97A8(ctx, gobj) != 0_i32 {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            inl_enterGroundTurn_unfused(ctx, gobj);
        } else {
            inl_enterAirTurn_unfused(ctx, gobj);
        }
        (fp).set_accessory4_cb(fnptr(ctx, 0x800e83e0));
        return 1_i32;
    }
    return 0_i32;
}

pub fn ftFx_SpecialLwHit_Check<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> i32 {
    let __frame = ctx.stack_frame(0x40);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    if ((fp).mv().fx().SpecialLw().releaseLag() <= 0_i32)
        && ((fp).mv().fx().SpecialLw().isRelease() != 0)
    {
        if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
            fns::ftFx_SpecialLwEnd_Enter(ctx, gobj);
        } else {
            fns::ftFx_SpecialAirLwEnd_Enter(ctx, gobj);
        }
        return 0_i32;
    }
    if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
        statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLwLoop_Enter(ctx, gobj);
    } else {
        statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialAirLwLoop_Enter(ctx, gobj);
    }
    return 1_i32;
}

pub fn ftFx_SpecialLwHit_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x48);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    inl_updateRelease_unfused(ctx, gobj);
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        if (fns::ftFx_SpecialLwHit_Check(ctx, gobj) != 0) {
            fns::ftCommon_8007DB24(ctx, gobj);
            (fp).set_accessory4_cb(fnptr(ctx, 0x800e83e0));
        }
    }
}

pub fn ftFx_SpecialAirLwHit_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let mut gobj = gobj;
    fns::ftFx_SpecialLwHit_Anim(ctx, gobj);
}

pub fn ftFx_SpecialLwHit_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialAirLwHit_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialLwHit_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialAirLwHit_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let unused: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftFox_DatAttrs<'a> =
        Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    let mut ca: ftCo_DatAttrs<'a> = inl_getFtAttrs_unfused(ctx, fp);
    if (fp).mv().fx().SpecialLw().gravityDelay() != 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_gravityDelay((fp).mv().fx().SpecialLw().gravityDelay().wrapping_sub(1));
    } else {
        fns::ftCommon_Fall(
            ctx,
            fp,
            (da).xAC_FOX_REFLECTOR_FALL_ACCEL(),
            (ca).terminal_velocity(),
        );
    }
    let _ = fns::ftCommon_CalcSelfAccel_DeaccelQuickAir(ctx, fp);
    fns::ftColl_8007AEF8(ctx, gobj);
}

pub fn ftFx_SpecialLwHit_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if !(fns::ft_80082708(ctx, gobj) != 0) {
        fns::ftFx_SpecialLwHit_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwHit_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) != 0) {
        fns::ftFx_SpecialAirLwHit_AirToGround(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwHit_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    inl_ftCommon_GroundToAirStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialAirLwHit as i32),
        0xc4c5082_u32,
    );
    fns::ftFx_SpecialLwHit_SetCall(ctx, gobj);
}

pub fn ftFx_SpecialAirLwHit_AirToGround<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    inl_ftCommon_AirToGroundStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialLwHit as i32),
        0xc4c5082_u32,
    );
    fns::ftCommon_ClampAirDrift(ctx, fp);
    fns::ftFx_SpecialLwHit_SetCall(ctx, gobj);
}

pub fn ftFx_SpecialLwHit_SetCall<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).set_reflecting((1_i32 as u8));
    (fp).set_reflect_hit_cb(fnptr(ctx, 0x800e9a68));
}

pub fn ftFx_SpecialLwHit_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x28);
    let sp14: Vec<'a> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = null(ctx);
    fp = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut msid: i32 = 0;
    (fp).set_facing_dir((fp).ReflectAttr().x1A2C_reflectHitDirection());
    fns::lb_8000B1CC(
        ctx,
        (Handle::add(
            (fp).parts(),
            fns::ftParts_GetBoneIndex(ctx, fp, (enums::FtPart_HipN as i32)),
        ))
        .joint(),
        null::<Vec<'a>>(ctx),
        sp14,
    );
    fns::lb_800119DC(
        ctx,
        sp14,
        120_i32,
        fp::frsp(3_i32 as f64),
        fp::frsp(0.1),
        fp::frsp(fp::fdiv(3.141592653589793, (3_i32 as f64))),
    );
    if ((fp).ground_or_air() as u32) == ((enums::GA_Ground as i32) as u32) {
        msid = (enums::ftFx_MS_SpecialLwHit as i32);
    } else {
        msid = (enums::ftFx_MS_SpecialAirLwHit as i32);
    }
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        msid,
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    fns::ftFx_SpecialLwHit_SetCall(ctx, gobj);
    (fp).set_accessory4_cb(fnptr(ctx, 0x800e84d8));
}

pub fn ftFx_SpecialLwEnd_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCommon_8007DB24(ctx, gobj);
        fns::ftCommon_8007D92C(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwEnd_Anim<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x20);
    let unused: ArrV<'a, u8, 8> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    if !(fns::ftAnim_IsFramesRemaining(ctx, gobj) != 0) {
        fns::ftCommon_8007DB24(ctx, gobj);
        fns::ftCommon_8007D92C(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwEnd_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialAirLwEnd_IASA<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    return;
}

pub fn ftFx_SpecialLwEnd_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::ft_80084F3C(ctx, gobj);
}

pub fn ftFx_SpecialAirLwEnd_Phys<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x30);
    let unused: ArrV<'a, u8, 4> = frame_at(ctx, &__frame, 0x0);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = null(ctx);
    fp = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftFox_DatAttrs<'a> =
        Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    let mut ca: ftCo_DatAttrs<'a> = inl_getFtAttrs_unfused(ctx, fp);
    if (fp).mv().fx().SpecialLw().gravityDelay() != 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_gravityDelay((fp).mv().fx().SpecialLw().gravityDelay().wrapping_sub(1));
    } else {
        fns::ftCommon_Fall(
            ctx,
            fp,
            (da).xAC_FOX_REFLECTOR_FALL_ACCEL(),
            (ca).terminal_velocity(),
        );
    }
    let _ = fns::ftCommon_CalcSelfAccel_DeaccelQuickAir(ctx, fp);
}

pub fn ftFx_SpecialLwEnd_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80082708(ctx, gobj) as u32) == (0_i32 as u32) {
        fns::ftFx_SpecialLwEnd_GroundToAir(ctx, gobj);
    }
}

pub fn ftFx_SpecialAirLwEnd_Coll<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    if (fns::ft_80081D0C(ctx, gobj) as u32) != (0_i32 as u32) {
        fns::ftFx_SpecialAirLwEnd_AirToGround(ctx, gobj);
    }
}

pub fn ftFx_SpecialLwEnd_GroundToAir<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    inl_ftCommon_GroundToAirStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialAirLwEnd as i32),
        0x5000_u32,
    );
}

pub fn ftFx_SpecialAirLwEnd_AirToGround<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x18);
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    inl_ftCommon_AirToGroundStateChange_unfused(
        ctx,
        gobj,
        fp,
        (enums::ftFx_MS_SpecialLwEnd as i32),
        0x5000_u32,
    );
    fns::ftCommon_ClampAirDrift(ctx, fp);
}

pub fn ftFx_SpecialLwEnd_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialLwEnd as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
}

pub fn ftFx_SpecialAirLwEnd_Enter<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwEnd as i32),
        0_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
}

fn inl_Fighter_SetEffectHitlagCallbacks_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) {
    let mut fp = fp;
    (fp).set_pre_hitlag_cb(fnptr(ctx, 0x8005ba40));
    (fp).set_post_hitlag_cb(fnptr(ctx, 0x8005bac4));
}

fn inl_ftFox_SpecialLw_SetVars_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = null(ctx);
    fp = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    let mut da: ftFox_DatAttrs<'a> = null(ctx);
    da = Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    (fp).mv()
        .fx()
        .SpecialLw()
        .set_releaseLag(fp::fctiwz((da).x98_FOX_REFLECTOR_RELEASE_LAG()));
    (fp).mv().fx().SpecialLw().set_isRelease(0_i32);
    (fp).cmd_vars().at(1_i32).set((4_i32 as u32));
    (fp).mv()
        .fx()
        .SpecialLw()
        .set_gravityDelay((da).xA4_FOX_REFLECTOR_GRAVITY_DELAY());
    (fp).set_accessory4_cb(fnptr(ctx, 0x800e845c));
}

fn inl_HSD_GObjGetUserData_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_getFtSpecialAttrs_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) -> Addr<'a> {
    let mut fp = fp;
    let mut fighter_attr: Addr<'a> = (fp).dat_attrs();
    return fighter_attr;
}

fn inl_ftCommon_GroundToAirStateChange_unfused<'a>(
    ctx: &'a Ctx,
    gobj: HSD_GObj<'a>,
    fp: Fighter<'a>,
    msid: i32,
    flags: u32,
) {
    let mut gobj = gobj;
    let mut fp = fp;
    let mut msid = msid;
    let mut flags = flags;
    fns::ftCommon_8007D5D4(ctx, fp);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        msid,
        flags,
        (fp).cur_anim_frame(),
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
}

fn inl_ftCommon_AirToGroundStateChange_unfused<'a>(
    ctx: &'a Ctx,
    gobj: HSD_GObj<'a>,
    fp: Fighter<'a>,
    msid: i32,
    flags: u32,
) {
    let mut gobj = gobj;
    let mut fp = fp;
    let mut msid = msid;
    let mut flags = flags;
    fns::ftCommon_8007D7FC(ctx, fp);
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        msid,
        flags,
        (fp).cur_anim_frame(),
        1.0,
        0.0,
        null::<HSD_GObj<'a>>(ctx),
    );
}

fn inl_ftFox_SpecialLw_InlinePhys_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut ca: ftCo_DatAttrs<'a> = null(ctx);
    let mut da: ftFox_DatAttrs<'a> = null(ctx);
    let mut fp: Fighter<'a> = inl_getFighter_unfused(ctx, gobj);
    ca = inl_getFtAttrs_unfused(ctx, fp);
    da = Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    if (fp).mv().fx().SpecialLw().gravityDelay() != 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_gravityDelay((fp).mv().fx().SpecialLw().gravityDelay().wrapping_sub(1));
    } else {
        fns::ftCommon_Fall(
            ctx,
            fp,
            (da).xAC_FOX_REFLECTOR_FALL_ACCEL(),
            (ca).terminal_velocity(),
        );
    }
    let _ = fns::ftCommon_CalcSelfAccel_DeaccelQuickAir(ctx, fp);
}

fn inl_getFighter_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Fighter<'a> {
    let mut gobj = gobj;
    return Handle::cast::<Fighter<'a>>((gobj).user_data());
}

fn inl_getFtAttrs_unfused<'a>(ctx: &'a Ctx, fp: Fighter<'a>) -> ftCo_DatAttrs<'a> {
    let mut fp = fp;
    return (fp).co_attrs();
}

fn inl_HSD_GObjGetUserData<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) -> Addr<'a> {
    let mut gobj = gobj;
    return (gobj).user_data();
}

fn inl_updateRelease<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData(ctx, gobj)));
    if !(((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        != 0)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if (fp).mv().fx().SpecialLw().releaseLag() > 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_releaseLag((fp).mv().fx().SpecialLw().releaseLag().wrapping_sub(1));
    }
}

fn inl_ftFox_SpecialLw_SetReflectVars_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    (fp).set_reflecting((1_i32 as u8));
    (fp).set_reflect_hit_cb(fnptr(ctx, 0x800e9a68));
}

fn inl_enterGroundTurn_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialLwTurn as i32),
        2_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_ftFox_SpecialLwTurn_SetVarAll_unfused(ctx, gobj);
}

fn inl_ftFox_SpecialLwTurn_SetVarAll_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> = Handle::cast::<Fighter<'a>>((gobj).user_data());
    let mut da: ftFox_DatAttrs<'a> =
        Handle::cast::<ftFox_DatAttrs<'a>>(inl_getFtSpecialAttrs_unfused(ctx, fp));
    (fp).set_reflecting((1_i32 as u8));
    (fp).set_reflect_hit_cb(fnptr(ctx, 0x800e9a68));
    (fp).mv()
        .fx()
        .SpecialLw()
        .set_turnFrames(fp::fctiwz((da).x9C_FOX_REFLECTOR_TURN_FRAMES()));
    (fp).cmd_vars().at(0_i32).set((0_i32 as u32));
    statics::melee__ft__kinds__ftFox__ftfoxspeciallw::ftFx_SpecialLw_Turn(ctx, gobj);
}

fn inl_enterAirTurn_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    fns::Fighter_ChangeMotionState(
        ctx,
        gobj,
        (enums::ftFx_MS_SpecialAirLwTurn as i32),
        2_u32,
        fp::frsp(0_i32 as f64),
        fp::frsp(1_i32 as f64),
        fp::frsp(0_i32 as f64),
        null::<HSD_GObj<'a>>(ctx),
    );
    inl_ftFox_SpecialLwTurn_SetVarAll_unfused(ctx, gobj);
}

fn inl_updateRelease_unfused<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>) {
    let mut gobj = gobj;
    let mut fp: Fighter<'a> =
        (Handle::cast::<Fighter<'a>>(inl_HSD_GObjGetUserData_unfused(ctx, gobj)));
    if !(((fp).input().held_buttons().at(0_i32).get() & ((shl_i32(1_i32, (9_i32 as u32))) as u32))
        != 0)
    {
        (fp).mv().fx().SpecialLw().set_isRelease(1_i32);
    }
    if (fp).mv().fx().SpecialLw().releaseLag() > 0_i32 {
        (fp).mv()
            .fx()
            .SpecialLw()
            .set_releaseLag((fp).mv().fx().SpecialLw().releaseLag().wrapping_sub(1));
    }
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x800e83e0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_CreateLoopGFX(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e845c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_CreateStartGFX(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e84d8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_CreateReflectGFX(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8560,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e85ec,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLw_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8694,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8720,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwStart_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e87ac,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e87d0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwStart_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e87d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_CheckPass(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x800e881c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_Pass(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8864,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8884,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwStart_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e88e4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8920,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwStart_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e895c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwStart_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e89bc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwStart_AirToGround(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8a24,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8a9c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8b14,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8b64,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8ba4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_CheckPass(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x800e8bec,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_Pass(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8c34,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8c68,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8cdc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8d18,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8d54,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8dbc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_AirToGround(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8e2c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_CreateReflectHit(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8e60,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwLoop_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8ec0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwLoop_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8f20,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLw_Turn(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e8fdc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e90ec,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwTurn_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e91fc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9200,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwTurn_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9204,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9238,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwTurn_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e92ac,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e92e8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwTurn_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9324,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e93a4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwTurn_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e942c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwTurn_Check(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x800e9564,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_Check(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x800e965c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e97b4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwHit_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9844,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9848,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwHit_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e984c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9880,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwHit_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e98f4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9930,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwHit_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e996c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e99d4,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwHit_AirToGround(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9a44,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_SetCall(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9a68,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwHit_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9b40,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9b84,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_Anim(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9bc8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9bcc,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_IASA(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9bd0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9bf0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_Phys(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9c50,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9c8c,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_Coll(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9cc8,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_GroundToAir(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9d24,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_AirToGround(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9d88,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialLwEnd_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x800e9dc0,
        |ctx| {
            let (a0,): (HSD_GObj<'_>,) = Args::take_all(ctx);
            Ret::put(ftFx_SpecialAirLwEnd_Enter(ctx, a0), ctx);
        },
        Returns::Nothing,
    );
}
