// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/MetroTRK/mutex_TRK.c. Do not edit; fix the translator or port by hand.
// unit: MetroTRK/mutex_TRK
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn TRKInitializeMutex<'a>(ctx: &'a Ctx, p1: Addr<'a>) -> i32 {
    let mut p1 = p1;
    return (enums::kNoError as i32);
}

pub fn TRKAcquireMutex<'a>(ctx: &'a Ctx, p1: Addr<'a>) -> i32 {
    let mut p1 = p1;
    return (enums::kNoError as i32);
}

pub fn TRKReleaseMutex<'a>(ctx: &'a Ctx, p1: Addr<'a>) -> i32 {
    let mut p1 = p1;
    return (enums::kNoError as i32);
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x80328e60,
        |ctx| {
            let (a0,): (Addr<'_>,) = Args::take_all(ctx);
            Ret::put(TRKInitializeMutex(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80328e68,
        |ctx| {
            let (a0,): (Addr<'_>,) = Args::take_all(ctx);
            Ret::put(TRKAcquireMutex(ctx, a0), ctx);
        },
        Returns::Int,
    );
    ctx.register_port(
        0x80328e70,
        |ctx| {
            let (a0,): (Addr<'_>,) = Args::take_all(ctx);
            Ret::put(TRKReleaseMutex(ctx, a0), ctx);
        },
        Returns::Int,
    );
}
