// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs. Do not edit.
pub mod melee__ft__ft_0C31;

/// Registers a unit's ports.
pub type Register = fn(&ssbm_rt::Ctx);

/// (unit, register) for every translated unit.
pub static UNITS: &[(&str, Register)] = &[
    ("melee/ft/ft_0C31", melee__ft__ft_0C31::register),
];
