// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/c2rs from src/sysdolphin/baselib/hsd_3982.c. Do not edit; fix the translator or port by hand.
// unit: sysdolphin/baselib/hsd_3982
#![allow(
    unused_mut,
    unused_variables,
    unused_assignments,
    unused_parens,
    unused_braces
)]
#![allow(
    unused_labels,
    unreachable_code,
    unused_imports,
    unused_comparisons,
    non_snake_case
)]
#![allow(dead_code)]
#![allow(clippy::all)]
use gekko_fp as fp;
use ssbm_rt::*;
use ssbm_types::enums;
use ssbm_types::fns;
use ssbm_types::records::*;
use ssbm_types::tu as statics;

use crate::support::*;

pub fn fn_803982E4<'a>(ctx: &'a Ctx, gobj: HSD_GObj<'a>, unused: i32) {
    let __frame = ctx.stack_frame(0x8);
    let mut gobj = gobj;
    let mut unused = unused;
    let _ = fns::HSD_CObjSetCurrent(ctx, Handle::cast::<HSD_CObj<'a>>((gobj).hsd_obj()));
    fns::fn_80392934(ctx);
    fns::hsd_8039254C(ctx);
}

pub fn hsd_80398310<'a>(
    ctx: &'a Ctx,
    class_id: u16,
    p_link: u8,
    obj_kind: u8,
    gx_link: u32,
) -> HSD_GObj<'a> {
    let __frame = ctx.stack_frame(0x18);
    let mut class_id = class_id;
    let mut p_link = p_link;
    let mut obj_kind = obj_kind;
    let mut gx_link = gx_link;
    let mut gobj: HSD_GObj<'a> = null(ctx);
    let mut cobj: HSD_CObj<'a> = null(ctx);
    gobj = fns::GObj_Create(ctx, class_id, p_link, obj_kind);
    if Handle::is_null(gobj) {
        return null::<HSD_GObj<'a>>(ctx);
    }
    cobj = fns::HSD_CObjLoadDesc(
        ctx,
        Handle::cast::<HSD_CObjDesc<'a>>(statics::sysdolphin__baselib__hsd_3982::lbl_8040BF70(ctx)),
    );
    fns::HSD_GObjObject_80390A70(
        ctx,
        gobj,
        fns::HSD_GObj_CameraKind(ctx).get(),
        Handle::cast::<Addr<'a>>(cobj),
    );
    fns::GObj_SetupGXLinkMax(ctx, gobj, fnptr(ctx, 0x803982e4), gx_link);
    fns::hsd_80392528(ctx, fnptr(ctx, 0x80392a3c));
    fns::fn_80392A08(ctx, 4_i32, 1_i32, 0_i32);
    return gobj;
}

/// Registers this unit's ports.
pub fn register(ctx: &Ctx) {
    ctx.register_port(
        0x803982e4,
        |ctx| {
            let (a0, a1): (HSD_GObj<'_>, i32) = Args::take_all(ctx);
            Ret::put(fn_803982E4(ctx, a0, a1), ctx);
        },
        Returns::Nothing,
    );
    ctx.register_port(
        0x80398310,
        |ctx| {
            let (a0, a1, a2, a3): (u16, u8, u8, u32) = Args::take_all(ctx);
            Ret::put(hsd_80398310(ctx, a0, a1, a2, a3), ctx);
        },
        Returns::Int,
    );
}
